// Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
#include "../../person.h"
#include <jlcxx/jlcxx.hpp>
#include <jlcxx/stl.hpp>
#include <stdexcept>
#include <string>
#include <vector>

// CxxWrap.jl loads this entry point (default symbol `define_julia_module`)
// from Julia via `@wrapmodule(() -> libpath)`.
JLCXX_MODULE define_julia_module(jlcxx::Module &mod) {
    auto c_Person = mod.add_type<Person>("Person");
    {
    auto &c = c_Person;
    c.constructor<>();
    c.constructor<std::string, int, std::string>();
    c.method("name", [](const Person &s) { return s.name; });
    c.method("name!", [](Person &s, const std::string &v) { s.name = v; });
    c.method("age", [](const Person &s) { return s.age; });
    c.method("age!", [](Person &s, int v) {
        if (v < 0 || v > 150)
            throw std::out_of_range("age out of range [0, 150]");
        s.age = v;
    });
    c.method("id", [](const Person &s) { return s.id; });
    c.method("color", [](const Person &s) { return s.color; });
    c.method("color!", [](Person &s, const std::string &v) { s.color = v; });
    c.method("verified", [](const Person &s) { return s.verified; });
    c.method("verified!", [](Person &s, const int &v) { s.verified = v; });
    c.method("greet", static_cast<std::string (Person::*)(const std::string &) const>(&Person::greet));
    c.method("clear", static_cast<void (Person::*)()>(&Person::clear));
    }
}
