// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Dynamic object-model backend, emitter. Included by inline/generate.hxx after
// the shared render helpers and backends/python.h (for qualify_std).
//
// Output shape, per target:
//
//   dynamic/auto_dynamic.h    — declares register_all()
//   dynamic/auto_dynamic.cpp  — the TypeDesc / MetaField / MetaMethod / MetaClass
//                               tables and one thunk per member
//   dynamic/inspect.cpp       — a demo that prints the whole registry, i.e. the
//                               "menus without codegen" claim, executable
//   dynamic/CMakeLists.txt    — stock C++20, no reflection
//   dynamic/README.md
//
// One thing worth noticing in the emitted thunks: they call the member BY NAME
// with concrete, exactly-typed argument expressions (value_cast<int>(a[0])), so
// C++'s own overload resolution picks the right one. Every other backend has to
// spell a disambiguating static_cast to a member-function-pointer type
// (GenMethod::is_overloaded exists for that), and the ones that cannot register
// two same-named entries drop the siblings entirely. Here both problems just
// do not arise.

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        // -------- templates ------------------------------------------------

        constexpr std::string_view DYNX_CMAKE =
            R"CMK(# Generated by rosetta::generate (dynamic object model) — do not edit by hand.
# Stock C++20: NO reflection, NO <experimental/meta>. The only rosetta header
# used is <rosetta/dynamic.h>, which is itself ordinary C++.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_dynamic CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

set(ROSETTA_INCLUDE "{{ROSETTA_INCLUDE}}")

add_library({{LIB}}_dynamic STATIC auto_dynamic.cpp)
target_include_directories({{LIB}}_dynamic PUBLIC
    {{USER_INCLUDE}}
    ${ROSETTA_INCLUDE}
    ${CMAKE_CURRENT_SOURCE_DIR})
set(ROSETTA_BINDING_TARGET {{LIB}}_dynamic)
{{USER_DEFS_BLOCK}}{{USER_LIB_BLOCK}}

# The demo: walks the registry and prints every class, field and method. It
# includes no per-class header and names no bound type — that is the point.
add_executable({{LIB}}_inspect inspect.cpp)
target_link_libraries({{LIB}}_inspect PRIVATE {{LIB}}_dynamic)
{{OUT_DIR_BLOCK}}
)CMK";

        constexpr std::string_view DYNX_README_BUILD = R"MD(## Build

Prerequisites: a stock C++20 compiler and CMake >= 3.18. No C++26 / reflection
toolchain is needed — the metadata is emitted as plain aggregate initializers.

```sh
cmake -S . -B build
cmake --build build
./build/{{LIB}}_inspect
```

`{{LIB}}_inspect` prints the whole registry. Note that its source names no bound
type and includes none of your headers: everything it prints came from querying
`rosetta::dyn::registry()` at run time.

## Using it

```cpp
#include <rosetta/dynamic.h>
#include "auto_dynamic.h"

using namespace rosetta::dyn;

{{LIB}}::register_all();

const MetaClass *k = registry().find_class("YourClass");
Result made = Object::create(*k, {Any::text("hello"), Any::integer(3)});
Object obj  = Object::adopt(*k, made.value.as_object().ptr, made.value.as_object().owner);

Result r = obj.call("someMethod", {Any::real(0.5)});
if (!r.ok()) {
    // r.error names every overload it tried and why each one lost.
}
```
)MD";

        // The demo. Deliberately free of any reference to the bound library.
        constexpr std::string_view DYNX_INSPECT =
            R"CPP(// Generated by rosetta::generate (dynamic object model) — do not edit by hand.
//
// A property inspector, in text. It includes no user header and names no bound
// type: every line below is produced by querying the runtime metadata. Swap the
// printf calls for ImGui / Qt / QML widget calls and this is a GUI — which is
// the whole argument for the dynamic model.

#include <rosetta/dynamic.h>
#include <iostream>
#include "auto_dynamic.h"

using namespace rosetta::dyn;

static void print_params(const MetaParam *ps, std::size_t n) {
    std::cout << "(";
    for (std::size_t i = 0; i < n; ++i) {
        std::cout << (i ? ", " : "") << ps[i].type->spelling << " " << ps[i].name;
        if (ps[i].is_out) {
            std::cout << " [out]";
        }
    }
    std::cout << ")";
}

int main() {
    {{LIB}}::register_all();

    for (const MetaEnum *e : registry().enums()) {
        std::cout << "enum " << e->qualified << " {";
        for (std::size_t i = 0; i < e->n_values; ++i) {
            std::cout << (i ? ", " : " ") << e->values[i].name << " = " << e->values[i].value;
        }
        std::cout << " }\n";
    }

    for (const MetaClass *k : registry().classes()) {
        std::cout << "\nclass " << k->qualified;
        for (std::size_t i = 0; i < k->n_bases; ++i) {
            std::cout << (i ? ", " : " : ") << k->bases[i]->qualified;
        }
        std::cout << (k->is_abstract ? "  [abstract]" : "") << "\n";
        if (*k->doc) {
            std::cout << "    // " << k->doc << "\n";
        }

        for (std::size_t i = 0; i < k->n_ctors; ++i) {
            std::cout << "    ctor ";
            print_params(k->ctors[i].params, k->ctors[i].n_params);
            std::cout << "\n";
        }

        for (std::size_t i = 0; i < k->n_fields; ++i) {
            const MetaField &f = k->fields[i];
            std::cout << "    " << f.type->spelling << " " << f.name;
            if (f.readonly) {
                std::cout << "  [readonly]";
            }
            if (f.range.has) {
                std::cout << "  [" << f.range.lo << ".." << f.range.hi << "]";
            }
            for (std::size_t j = 0; j < f.n_choices; ++j) {
                std::cout << (j ? ", " : "  choices: ") << f.choices[j];
            }
            if (f.type->n_enumerators) {
                for (std::size_t j = 0; j < f.type->n_enumerators; ++j) {
                    std::cout << (j ? ", " : "  values: ") << f.type->enumerators[j].name;
                }
            }
            if (!f.get) {
                std::cout << "  [not readable]";
            }
            std::cout << "\n";
        }

        for (std::size_t i = 0; i < k->n_methods; ++i) {
            const MetaMethod &m = k->methods[i];
            std::cout << "    " << (m.is_static ? "static " : "") << m.ret->spelling << " "
                      << m.name;
            print_params(m.params, m.n_params);
            if (m.overload_count > 1) {
                std::cout << "  [overload " << (m.overload_index + 1) << "/" << m.overload_count
                          << "]";
            }
            if (!m.invoke) {
                std::cout << "  [not callable: " << m.skip_reason << "]";
            }
            std::cout << "\n";
        }
    }

    for (const MetaFunction *f : registry().functions()) {
        std::cout << "\n" << f->ret->spelling << " " << f->qualified;
        print_params(f->params, f->n_params);
        std::cout << "\n";
    }
    return 0;
}
)CPP";

        // -------- small helpers --------------------------------------------

        /** @brief "GEO::Mesh" -> "GEO_Mesh"; any non-identifier char becomes '_'. */
        inline std::string dyn_ident(std::string s) {
            for (char &ch : s) {
                const bool ok = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                                (ch >= '0' && ch <= '9');
                if (!ok) {
                    ch = '_';
                }
            }
            return s;
        }

        /** @brief A C++ string literal for `s`. */
        inline std::string dyn_quote(const std::string &s) {
            std::string out = "\"";
            for (char ch : s) {
                switch (ch) {
                case '"':
                    out += "\\\"";
                    break;
                case '\\':
                    out += "\\\\";
                    break;
                case '\n':
                    out += "\\n";
                    break;
                case '\t':
                    out += "\\t";
                    break;
                case '\r':
                    break;
                default:
                    out += ch;
                }
            }
            return out + "\"";
        }

        /**
         * @brief Lower a member's annotation pack to MetaAnnotation key/value text.
         *
         * The compile-time IR type-erases annotations into std::vector<std::any>
         * and lets each backend std::any_cast the kinds it knows. That cannot
         * survive to run time — the caller has no type to cast to — so the
         * UI-relevant kinds are flattened here to (key, value) strings.
         *
         * doc / range / readonly / combobox are NOT in this list: they are lifted
         * to real MetaField members, because every consumer wants them and a
         * string round-trip would be a needless parse. What is left is the
         * presentation vocabulary — `label`, `button`, and the widget:: tags —
         * which a UI reads and everyone else ignores.
         *
         * Adding a new annotation kind means one line here, once, rather than
         * one per backend.
         */
        inline std::vector<std::pair<std::string, std::string>>
        dyn_annotations(const std::vector<std::any> &anns) {
            std::vector<std::pair<std::string, std::string>> out;
            if (const auto *l = find_annotation<rosetta::label>(anns)) {
                out.emplace_back("label", l->text);
            }
            if (const auto *b = find_annotation<rosetta::button>(anns)) {
                out.emplace_back("button", b->label);
            }
            const auto tag = [&](const char *name, bool present) {
                if (present) {
                    out.emplace_back("widget", name);
                }
            };
            tag("spin", find_annotation<rosetta::widget::spin_tag>(anns) != nullptr);
            tag("slider", find_annotation<rosetta::widget::slider_tag>(anns) != nullptr);
            tag("checkbox", find_annotation<rosetta::widget::checkbox_tag>(anns) != nullptr);
            tag("textfield", find_annotation<rosetta::widget::textfield_tag>(anns) != nullptr);
            tag("color", find_annotation<rosetta::widget::color_tag>(anns) != nullptr);
            tag("multiline", find_annotation<rosetta::widget::multiline_tag>(anns) != nullptr);
            tag("radio", find_annotation<rosetta::widget::radio_tag>(anns) != nullptr);
            tag("file", find_annotation<rosetta::widget::file_tag>(anns) != nullptr);
            return out;
        }

        /**
         * @brief Emit the MetaAnnotation array for a member, if it has any.
         * Returns the ",\n .annotations = ..." fragment to splice into the
         * member's initializer, appending the array definition to `arrays`.
         */
        inline std::string dyn_ann_field(const std::vector<std::any> &anns, const std::string &id,
                                         std::string &arrays) {
            const auto kv = dyn_annotations(anns);
            if (kv.empty()) {
                return {};
            }
            arrays += "    const MetaAnnotation " + id + "[] = {";
            for (std::size_t i = 0; i < kv.size(); ++i) {
                arrays += (i ? ", " : "");
                arrays += "{" + dyn_quote(kv[i].first) + ", " + dyn_quote(kv[i].second) + "}";
            }
            arrays += "};\n";
            return "         .annotations = " + id +
                   ", .n_annotations = " + std::to_string(kv.size()) + ",\n";
        }

        /** @brief The bound class an object / pointer type names, or null. */
        inline const GenClass *dyn_class_of(const GenType &t, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (names_type(t, k)) {
                    return &k;
                }
            }
            return nullptr;
        }

        /**
         * @brief Why the dynamic model cannot marshal `t`, or nullptr if it can.
         *
         * Same conservative policy as every other backend: a type with no
         * canonical Any representation is SKIPPED (null thunk + reason) rather
         * than bound into something that fails at call time. Unlike the other
         * backends, though, the member still reaches the metadata — so a UI can
         * grey it out and say why, instead of the member silently not existing.
         */
        inline const char *dyn_reject(const GenType &t, const GenContext &c) {
            if (t.is_callback) {
                return "callback: a std::function parameter needs a foreign-callable adapter";
            }
            if (!t.interop.empty()) {
                return "interop type: no canonical Any representation";
            }
            if (t.is_sequence || t.is_matrix) {
                return "foreign container: marshal through std::vector first";
            }
            if (t.is_path) {
                return "std::filesystem::path: needs the string<->path adapter";
            }
            if (t.is_shared_ptr) {
                return "std::shared_ptr: holder semantics not modelled yet";
            }
            if (t.kind == "boolean" || t.kind == "string" || t.kind == "number" ||
                t.kind == "enum" || t.kind == "void") {
                return nullptr;
            }
            if (t.kind == "object") {
                return dyn_class_of(t, c) ? nullptr : "class is not bound in this module";
            }
            if (t.kind == "vector") {
                if (t.element.empty()) {
                    return "vector with no element type";
                }
                return dyn_reject(t.element[0], c);
            }
            if (t.is_pointer) {
                return dyn_class_of(t, c) ? nullptr : "pointer to a class that is not bound";
            }
            return "no canonical Any representation";
        }

        /** @brief The C++ spelling value_cast / ref_cast should be given. */
        inline std::string dyn_cpp(const GenType &t) {
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "vector") {
                return "std::vector<" + dyn_cpp(t.element[0]) + ">";
            }
            if (t.kind == "enum" || t.kind == "object" || t.is_pointer) {
                const std::string q = t.object_qualified.empty() ? t.object : t.object_qualified;
                return t.is_pointer ? q + " *" : q;
            }
            return qualify_std(t.spelling);
        }

        /** @brief The rosetta::dyn::Kind enumerator for `t`. */
        inline std::string dyn_kind(const GenType &t) {
            if (t.kind == "void") {
                return "Kind::void_";
            }
            if (t.kind == "boolean") {
                return "Kind::boolean";
            }
            if (t.kind == "number") {
                return "Kind::number";
            }
            if (t.kind == "string") {
                return "Kind::string";
            }
            if (t.kind == "enum") {
                return "Kind::enum_";
            }
            if (t.kind == "vector") {
                return "Kind::vector";
            }
            if (t.kind == "object" || t.is_pointer) {
                return "Kind::object";
            }
            return "Kind::unknown";
        }

        // -------- the TypeDesc pool ----------------------------------------

        /**
         * @brief De-duplicating emitter for TypeDesc objects.
         *
         * Two members of the same type must share one TypeDesc, both so the
         * tables stay small and so `a.type() == b.type()` is a pointer compare
         * in the common case. Definitions are appended in dependency order
         * (element before container), which is also a valid static-init order.
         */
        struct DynTypes {
            std::string                        defs;
            std::map<std::string, std::string> ids;
            std::size_t                        next = 0;

            // Keyed on what actually gets EMITTED (dyn_cpp), not on
            // GenType::spelling. The two differ for a class or enum — spelling
            // may be the unqualified identifier — and keying on the raw spelling
            // would emit a second, identical descriptor for the synthesized
            // self-type of each class.
            static std::string key(const GenType &t) {
                std::string k = t.kind + "|" + dyn_cpp(t) + "|" + t.object_qualified + "|" +
                                (t.integer ? "i" : "f") + (t.is_pointer ? "p" : "");
                for (const auto &e : t.element) {
                    k += "{" + key(e) + "}";
                }
                return k;
            }

            std::string id(const GenType &t, const GenContext &c) {
                const std::string k  = key(t);
                auto              it = ids.find(k);
                if (it != ids.end()) {
                    return it->second;
                }

                // Emit the element first — a container's initializer takes its
                // address, so it has to already exist.
                std::string elem;
                if (t.kind == "vector" && !t.element.empty()) {
                    elem = id(t.element[0], c);
                }

                const std::string nm = "td_" + std::to_string(next++);
                ids[k]               = nm;

                std::string enums_id;
                if (t.kind == "enum" && !t.enumerators.empty()) {
                    enums_id = nm + "_values";
                    defs += "    constexpr MetaEnumerator " + enums_id + "[] = {";
                    for (std::size_t i = 0; i < t.enumerators.size(); ++i) {
                        defs += (i ? ", " : " ");
                        defs += "{" + dyn_quote(t.enumerators[i].name) + ", " +
                                std::to_string(t.enumerators[i].value) + "}";
                    }
                    defs += " };\n";
                }

                defs += "    TypeDesc " + nm + "{.kind = " + dyn_kind(t) +
                        ", .spelling = " + dyn_quote(dyn_cpp(t));
                if (!t.object_qualified.empty() || !t.object.empty()) {
                    defs += ",\n        .object = " +
                            dyn_quote(t.object_qualified.empty() ? t.object : t.object_qualified);
                }
                if (t.kind == "number") {
                    defs += ", .integral = " + std::string(t.integer ? "true" : "false");
                }
                if (t.is_pointer) {
                    defs += ", .is_pointer = true";
                }
                if (!elem.empty()) {
                    defs += ", .element = &" + elem;
                }
                if (!enums_id.empty()) {
                    defs += ",\n        .enumerators = " + enums_id +
                            ", .n_enumerators = " + std::to_string(t.enumerators.size());
                }
                // A class bound by THIS module can be linked at static-init time
                // (the MetaClass objects are forward-declared above). One bound
                // elsewhere keeps a null `cls` and is resolved by Registry::link().
                if (const GenClass *k = (t.kind == "object" || t.is_pointer)
                                            ? dyn_class_of(t, c)
                                            : nullptr) {
                    defs += ", .cls = &k_" + dyn_ident(qualified_of(*k));
                }
                defs += "};\n";
                return nm;
            }
        };

        // -------- member emission ------------------------------------------

        /** @brief The expression that produces argument `i` inside a thunk. */
        inline std::string dyn_arg(const GenParam &p, std::size_t i) {
            const std::string cpp = dyn_cpp(p.type);
            const std::string idx = "a[" + std::to_string(i) + "]";
            // A by-reference class parameter must NOT copy — that is what makes a
            // non-copyable class still passable (the compile-time side draws the
            // same line with GenParam::is_ref).
            if (p.type.kind == "object" && p.is_ref) {
                return "ref_cast<" + cpp + ">(" + idx + ")";
            }
            return "value_cast<" + cpp + ">(" + idx + ")";
        }

        /** @brief Can every parameter and the return type be marshalled? */
        inline const char *dyn_method_reject(const GenMethod &m, const GenContext &c) {
            if (const char *r = dyn_reject(m.ret, c)) {
                return r;
            }
            for (const auto &p : m.params) {
                if (p.is_out) {
                    // The value joins the return as a tuple; the thunk would have
                    // to declare a local and pack a heterogeneous list. Described,
                    // not yet callable.
                    return "out_params: multi-value returns are not modelled yet";
                }
                if (const char *r = dyn_reject(p.type, c)) {
                    return r;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return "non-copyable class taken by value";
                }
                if (p.type.kind != "object" && p.is_mutable_ref) {
                    return "non-const reference to a non-class type";
                }
            }
            return nullptr;
        }

        /** @brief One method's whole thunk, `+[](...) { ... }`. */
        inline std::string dyn_thunk(const GenClass &k, const GenMethod &m, const GenContext &c,
                                     DynTypes &T) {
            const std::string cls = qualified_of(k);

            std::string args;
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                args += (i ? ", " : "") + dyn_arg(m.params[i], i);
            }

            std::string call;
            if (m.is_extension) {
                call = m.ext_qualified + "(*static_cast<" + cls + " *>(self.ptr)" +
                       (args.empty() ? "" : ", " + args) + ")";
            } else if (m.is_static) {
                call = cls + "::" + m.name + "(" + args + ")";
            } else {
                call = "static_cast<" + cls + " *>(self.ptr)->" + m.name + "(" + args + ")";
            }

            // Name the parameters only where the body uses them, so the emitted
            // code is -Wunused-parameter clean.
            const std::string self_p = m.is_static ? "const ObjectRef &" : "const ObjectRef &self";
            const std::string args_p = m.params.empty() ? "const ArgList &" : "const ArgList &a";
            std::string       body;

            if (m.ret.kind == "void") {
                body = "             " + call + ";\n             return Any::none();\n";
            } else {
                const std::string rt = T.id(m.ret, c);
                // An lvalue-reference return is handed back WITHOUT a copy, pinned
                // to the receiver's owner so the child cannot outlive its parent.
                body = (m.ret_is_ref && m.ret.kind == "object" && !m.is_static)
                           ? "             return borrow_any(&" + rt + ", " + call +
                                 ", self.owner);\n"
                           : "             return make_any(&" + rt + ", " + call + ");\n";
            }
            return "+[](" + self_p + ", " + args_p + ") {\n" + body + "         }";
        }

        // -------- one class -------------------------------------------------

        struct DynClassText {
            std::string arrays; // enumerator / param / field / method / ctor arrays
            std::string cls;    // the MetaClass definition
        };

        inline DynClassText dyn_class(const GenClass &k, const GenContext &c, DynTypes &T) {
            DynClassText      out;
            const std::string id  = dyn_ident(qualified_of(k));
            const std::string cls = qualified_of(k);

            // ---- bases (only those bound here) ----
            std::string bases;
            std::size_t n_bases = 0;
            for (const auto &b : k.bases) {
                for (const auto &other : c.classes) {
                    if (qualified_of(other) == b) {
                        bases += (n_bases++ ? ", " : "") + std::string("&k_") + dyn_ident(b);
                    }
                }
            }
            if (n_bases) {
                out.arrays += "    const MetaClass *const k_" + id + "_bases[] = {" + bases +
                              "};\n";
            }

            // ---- fields ----
            std::string fields;
            std::size_t n_fields = 0;
            for (const auto &f : k.fields) {
                const char *reject = dyn_reject(f.type, c);
                if (reject) {
                    coverage::note_skip_field("dynamic", k, f, "unmarshalable_type", reject);
                    continue;
                }
                coverage::note_bound_field("dynamic", k, f);
                const std::string td = T.id(f.type, c);

                std::string choices;
                if (!f.choices.empty()) {
                    const std::string cid = "k_" + id + "_" + f.name + "_choices";
                    out.arrays += "    const char *const " + cid + "[] = {";
                    for (std::size_t i = 0; i < f.choices.size(); ++i) {
                        out.arrays += (i ? ", " : "") + dyn_quote(f.choices[i]);
                    }
                    out.arrays += "};\n";
                    choices = ",\n         .choices = " + cid +
                              ", .n_choices = " + std::to_string(f.choices.size());
                }

                const std::string self = "static_cast<" + cls + " *>(self.ptr)->" + f.name;
                // A class-typed field is handed out BY REFERENCE, pinned to the
                // owner — no copy, so a non-copyable member is still readable.
                const std::string getter =
                    f.type.kind == "object"
                        ? "borrow_any(&" + td + ", " + self + ", self.owner)"
                        : "make_any(&" + td + ", " + self + ")";

                fields += "        {.name = " + dyn_quote(f.name) + ",\n";
                fields += "         .type = &" + td + ",\n";
                if (!f.doc.empty()) {
                    fields += "         .doc = " + dyn_quote(f.doc) + ",\n";
                }
                if (f.is_readonly) {
                    fields += "         .readonly = true,\n";
                }
                if (f.range.has) {
                    fields += "         .range = {.has = true, .lo = " + num_str(f.range.min) +
                              ", .hi = " + num_str(f.range.max) + "},\n";
                }
                if (!choices.empty()) {
                    fields += "        " + choices.substr(2) + ",\n";
                }
                fields += dyn_ann_field(f.annotations, "k_" + id + "_" + f.name + "_anns",
                                        out.arrays);
                fields += "         .get = +[](const ObjectRef &self, const ArgList &) {\n";
                fields += "             return " + getter + ";\n";
                fields += "         }";
                // A read-only field, or one whose type cannot be assigned, gets no
                // setter at all — Object::set() then reports it instead of writing.
                if (!f.is_readonly && (f.type.kind != "object" || f.type.copy_assignable)) {
                    fields += ",\n";
                    fields += "         .set = +[](const ObjectRef &self, const ArgList &a) {\n";
                    fields += "             " + self + " = " +
                              (f.type.kind == "object" ? "ref_cast<" : "value_cast<") +
                              dyn_cpp(f.type) + ">(a[0]);\n";
                    fields += "             return Any::none();\n";
                    fields += "         }";
                }
                fields += "},\n";
                ++n_fields;
            }
            if (n_fields) {
                out.arrays += "    const MetaField k_" + id + "_fields[] = {\n" + fields + "    };\n";
            }

            // ---- methods ----
            std::string methods;
            std::size_t n_methods = 0;
            for (const auto &m : k.methods) {
                // NOTE: no coverage::emit_overload() call. Every other name-keyed
                // backend passes overloads::first_only here and discards the
                // siblings; the dynamic model keeps them all, which is the point.
                const std::string params_id =
                    "k_" + id + "_" + m.name + "_" + std::to_string(m.overload_index) + "_params";
                if (!m.params.empty()) {
                    out.arrays += "    const MetaParam " + params_id + "[] = {\n";
                    for (const auto &p : m.params) {
                        out.arrays += "        {.name = " + dyn_quote(p.name) +
                                      ", .type = &" + T.id(p.type, c) +
                                      (p.is_ref ? ", .is_ref = true" : "") +
                                      (p.is_mutable_ref ? ", .is_mutable_ref = true" : "") +
                                      (p.is_out ? ", .is_out = true" : "") + "},\n";
                    }
                    out.arrays += "    };\n";
                }

                const char *reject = dyn_method_reject(m, c);
                if (reject) {
                    coverage::note_skip("dynamic", k, m, "unmarshalable_type", reject);
                } else {
                    coverage::note_bound("dynamic", k, m);
                }

                methods += "        {.name = " + dyn_quote(m.name) + ",\n";
                methods += "         .ret = &" + T.id(m.ret, c) + ",\n";
                if (!m.doc.empty()) {
                    methods += "         .doc = " + dyn_quote(m.doc) + ",\n";
                }
                if (!m.params.empty()) {
                    methods += "         .params = " + params_id +
                               ", .n_params = " + std::to_string(m.params.size()) + ",\n";
                }
                if (m.is_static) {
                    methods += "         .is_static = true,\n";
                }
                if (m.is_const) {
                    methods += "         .is_const = true,\n";
                }
                if (m.is_virtual) {
                    methods += "         .is_virtual = true,\n";
                }
                if (m.overload_count > 1) {
                    methods += "         .overload_index = " + std::to_string(m.overload_index) +
                               ", .overload_count = " + std::to_string(m.overload_count) + ",\n";
                }
                methods += dyn_ann_field(m.annotations,
                                         "k_" + id + "_" + m.name + "_" +
                                             std::to_string(m.overload_index) + "_anns",
                                         out.arrays);
                if (reject) {
                    methods += "         .skip_reason = " + dyn_quote(reject) + "},\n";
                } else {
                    methods += "         .invoke = " + dyn_thunk(k, m, c, T) + "},\n";
                }
                ++n_methods;
            }
            if (n_methods) {
                out.arrays +=
                    "    const MetaMethod k_" + id + "_methods[] = {\n" + methods + "    };\n";
            }

            // ---- constructors ----
            std::string ctors;
            std::size_t n_ctors     = 0;
            bool        saw_default = false;
            for (std::size_t ci = 0; !k.is_abstract && ci < k.ctors.size(); ++ci) {
                const auto &ps = k.ctors[ci];
                bool        ok = true;
                for (const auto &p : ps) {
                    ok = ok && !dyn_reject(p.type, c) && !p.is_out &&
                         (p.type.kind == "object" ? (p.is_ref || p.type.copy_constructible)
                                                  : !p.is_mutable_ref);
                }
                if (!ok) {
                    continue;
                }
                saw_default = saw_default || ps.empty();

                const std::string pid = "k_" + id + "_ctor" + std::to_string(ci) + "_params";
                if (!ps.empty()) {
                    out.arrays += "    const MetaParam " + pid + "[] = {\n";
                    for (const auto &p : ps) {
                        out.arrays += "        {.name = " + dyn_quote(p.name) +
                                      ", .type = &" + T.id(p.type, c) +
                                      (p.is_ref ? ", .is_ref = true" : "") + "},\n";
                    }
                    out.arrays += "    };\n";
                }

                std::string args;
                for (std::size_t i = 0; i < ps.size(); ++i) {
                    args += (i ? ", " : "") + dyn_arg(ps[i], i);
                }
                ctors += "        {";
                if (!ps.empty()) {
                    ctors += ".params = " + pid +
                             ", .n_params = " + std::to_string(ps.size()) + ",\n         ";
                }
                ctors += ".construct = +[](const ArgList &" + std::string(ps.empty() ? "" : "a") +
                         ") -> void * {\n";
                ctors += "             return new " + cls + "(" + args + ");\n";
                ctors += "         }},\n";
                ++n_ctors;
            }
            // The implicit default constructor is often not enumerated as a
            // member, so GenClass::is_default_constructible is the only witness.
            if (!saw_default && !k.is_abstract && k.is_default_constructible) {
                ctors += "        {.construct = +[](const ArgList &) -> void * {\n";
                ctors += "             return new " + cls + "();\n";
                ctors += "         }},\n";
                ++n_ctors;
            }
            if (n_ctors) {
                out.arrays += "    const MetaCtor k_" + id + "_ctors[] = {\n" + ctors + "    };\n";
            }

            // ---- the class ----
            out.cls += "    const MetaClass k_" + id + "{\n";
            out.cls += "        .name = " + dyn_quote(exposed_of(k)) + ",\n";
            out.cls += "        .qualified = " + dyn_quote(cls) + ",\n";
            // NOT GenClass::doc — that is class_markdown(), a whole README
            // fragment meant for a generated document. What a tooltip needs is
            // the class's own rosetta::doc annotation, if it carries one.
            if (const doc *d = find_annotation<doc>(k.annotations)) {
                out.cls += "        .doc = " + dyn_quote(d->text) + ",\n";
            }
            if (n_bases) {
                out.cls += "        .bases = k_" + id +
                           "_bases, .n_bases = " + std::to_string(n_bases) + ",\n";
            }
            if (n_fields) {
                out.cls += "        .fields = k_" + id +
                           "_fields, .n_fields = " + std::to_string(n_fields) + ",\n";
            }
            if (n_methods) {
                out.cls += "        .methods = k_" + id +
                           "_methods, .n_methods = " + std::to_string(n_methods) + ",\n";
            }
            if (n_ctors) {
                out.cls += "        .ctors = k_" + id +
                           "_ctors, .n_ctors = " + std::to_string(n_ctors) + ",\n";
            }
            if (k.is_abstract) {
                out.cls += "        .is_abstract = true,\n";
            }
            // A class with a non-public destructor (GEO::Logger and friends) is
            // NOT skipped here, unlike in the runtime backends where destroying
            // what you wrap is unavoidable. It simply cannot be created or owned
            // — borrow it and everything else still works.
            if (k.is_destructible) {
                out.cls += "        .destroy = +[](void *p) { delete static_cast<" + cls +
                           " *>(p); },\n";
            }
            // The class's own descriptor, so an Object can be turned back into a
            // typed Any and passed as an argument. Synthesized rather than taken
            // from a member's type, because a class need not appear in any
            // signature to be instantiable.
            {
                GenType self_t;
                self_t.kind             = "object";
                self_t.object           = k.name;
                self_t.object_qualified = cls;
                self_t.spelling         = cls;
                out.cls += "        .self = &" + T.id(self_t, c) + ",\n";
            }
            out.cls += "    };\n\n";
            return out;
        }

        // -------- the whole translation unit --------------------------------

        inline std::string dynamic_source(const GenContext &c) {
            const std::string mod = dyn_ident(c.lib);

            std::string head = "// Generated by rosetta::generate (dynamic object model) — "
                               "do not edit by hand.\n"
                               "// Stock C++20: the metadata is DATA, so no reflection is needed "
                               "to build this.\n";
            head += "#include <rosetta/dynamic.h>\n";
            head += "#include \"auto_dynamic.h\"\n";
            head += "#include <string>\n#include <vector>\n";
            {
                auto add = [&](const std::string &h) { append_include(head, h); };
                head += init_includes(c);
                for (const auto &k : c.classes) {
                    add(k.header);
                    for (const auto &m : k.methods) {
                        if (m.is_extension && !m.ext_header.empty()) {
                            add(m.ext_header);
                        }
                    }
                }
                for (const auto &e : c.enums) {
                    add(e.header);
                }
                for (const auto &f : c.functions) {
                    add(f.header);
                }
            }
            head += "\nusing namespace rosetta::dyn;\n\nnamespace {\n\n";

            // Forward declarations: a TypeDesc naming a class takes its address,
            // and `&k_X` is an address constant expression even before the
            // definition. That is what lets two mutually-referencing classes link
            // during static init with no fix-up pass.
            std::string fwd;
            for (const auto &k : c.classes) {
                fwd += "    extern const MetaClass k_" + dyn_ident(qualified_of(k)) + ";\n";
            }
            if (!fwd.empty()) {
                fwd = "    // Forward declarations — see the note in backends/inline/dynamic.hxx.\n" +
                      fwd + "\n";
            }

            DynTypes    T;
            std::string arrays, classes;
            for (const auto &k : c.classes) {
                DynClassText t = dyn_class(k, c, T);
                arrays += t.arrays;
                classes += t.cls;
            }

            // ---- enums ----
            std::string enums;
            for (const auto &e : c.enums) {
                const std::string id = dyn_ident(qualified_of(e));
                arrays += "    constexpr MetaEnumerator k_" + id + "_values[] = {";
                for (std::size_t i = 0; i < e.values.size(); ++i) {
                    arrays += (i ? ", " : " ");
                    arrays += "{" + dyn_quote(e.values[i].name) + ", " +
                              std::to_string(e.values[i].value) + "}";
                }
                arrays += " };\n";
                enums += "    const MetaEnum k_" + id + "{.name = " + dyn_quote(exposed_of(e)) +
                         ",\n        .qualified = " + dyn_quote(qualified_of(e)) +
                         ", .underlying = " + dyn_quote(e.underlying) + ",\n        .values = k_" +
                         id + "_values, .n_values = " + std::to_string(e.values.size()) + "};\n";
            }
            if (!enums.empty()) {
                enums += "\n";
            }

            // ---- free functions ----
            std::string funcs;
            std::size_t fi = 0;
            for (const auto &f : c.functions) {
                const std::string id = "k_fn" + std::to_string(fi++) + "_" + dyn_ident(f.name);
                if (!f.params.empty()) {
                    arrays += "    const MetaParam " + id + "_params[] = {\n";
                    for (const auto &p : f.params) {
                        arrays += "        {.name = " + dyn_quote(p.name) + ", .type = &" +
                                  T.id(p.type, c) + (p.is_ref ? ", .is_ref = true" : "") + "},\n";
                    }
                    arrays += "    };\n";
                }

                const char *reject = dyn_reject(f.ret, c);
                for (const auto &p : f.params) {
                    if (!reject) {
                        reject = dyn_reject(p.type, c);
                    }
                    if (!reject && p.is_out) {
                        reject = "out_params: multi-value returns are not modelled yet";
                    }
                }

                funcs += "    const MetaFunction " + id + "{.name = " + dyn_quote(f.name) + ",\n";
                funcs += "        .qualified = " + dyn_quote(f.qualified) + ",\n";
                if (!f.doc.empty()) {
                    funcs += "        .doc = " + dyn_quote(f.doc) + ",\n";
                }
                funcs += "        .ret = &" + T.id(f.ret, c);
                if (!f.params.empty()) {
                    funcs += ", .params = " + id +
                             "_params, .n_params = " + std::to_string(f.params.size());
                }
                funcs += ",\n";
                if (reject) {
                    funcs += "        .skip_reason = " + dyn_quote(reject) + "};\n";
                } else {
                    std::string args;
                    for (std::size_t i = 0; i < f.params.size(); ++i) {
                        args += (i ? ", " : "") + dyn_arg(f.params[i], i);
                    }
                    const std::string call = f.qualified + "(" + args + ")";
                    funcs += "        .invoke = +[](const ObjectRef &, const ArgList &" +
                             std::string(f.params.empty() ? "" : "a") + ") {\n";
                    if (f.ret.kind == "void") {
                        funcs += "            " + call + ";\n            return Any::none();\n";
                    } else {
                        funcs += "            return make_any(&" + T.id(f.ret, c) + ", " + call +
                                 ");\n";
                    }
                    funcs += "        }};\n";
                }
            }
            if (!funcs.empty()) {
                funcs += "\n";
            }

            // ---- registration ----
            std::string reg = "namespace " + mod + " {\n\n";
            reg += "    void register_all(rosetta::dyn::Registry &r) {\n";
            reg += "        static bool done = false;\n";
            reg += "        if (done) {\n            return;\n        }\n";
            reg += "        done = true;\n";
            for (const auto &s : c.init_statements) {
                reg += "        " + s + (s.empty() || s.back() == ';' ? "" : ";") + "\n";
            }
            for (const auto &k : c.classes) {
                reg += "        r.add_class(&k_" + dyn_ident(qualified_of(k)) + ");\n";
            }
            for (const auto &e : c.enums) {
                reg += "        r.add_enum(&k_" + dyn_ident(qualified_of(e)) + ");\n";
            }
            for (std::size_t i = 0; i < c.functions.size(); ++i) {
                reg += "        r.add_function(&k_fn" + std::to_string(i) + "_" +
                       dyn_ident(c.functions[i].name) + ");\n";
            }
            reg += "        // Resolve any TypeDesc naming a class bound by ANOTHER module.\n";
            reg += "        r.link();\n";
            reg += "    }\n\n} // namespace " + mod + "\n";

            return head + fwd + T.defs + "\n" + arrays + "\n" + enums + classes + funcs +
                   "} // namespace\n\n" + reg;
        }

        inline std::string dynamic_header(const GenContext &c) {
            const std::string mod = dyn_ident(c.lib);
            std::string       s =
                "// Generated by rosetta::generate (dynamic object model) — do not edit by "
                      "hand.\n#pragma once\n\n#include <rosetta/dynamic.h>\n\nnamespace " +
                mod + " {\n\n";
            s += "    /** @brief Publish this module's metadata. Idempotent. */\n";
            s += "    void register_all(rosetta::dyn::Registry &r = rosetta::dyn::registry());\n";
            s += "\n} // namespace " + mod + "\n";
            return s;
        }

        // -------- Backend ---------------------------------------------------

        inline std::string Dynamic::render(const GenContext &c) const {
            return dynamic_source(c);
        }

        inline void Dynamic::emit(const GenContext &c) const {
            auto dir = c.out_dir / "dynamic";
            write_file(dir / "auto_dynamic.h", dynamic_header(c));
            write_file(dir / "auto_dynamic.cpp", dynamic_source(c));
            write_file(dir / "inspect.cpp", subst(DYNX_INSPECT, {{"LIB", dyn_ident(c.lib)}}));
            write_file(dir / "CMakeLists.txt", render_meta(DYNX_CMAKE, c));
            write_file(dir / "README.md",
                       readme("dynamic", c,
                              subst(DYNX_README_BUILD, {{"LIB", dyn_ident(c.lib)}})));
        }

    } // namespace backend
} // namespace rosetta
