// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) Dear ImGui backend. Included by
// inline/generate.hxx after qt_expanded_backend.h — it reuses qtx_display()
// (label annotation) and qtx_method_ok() (scalar-marshalable signature test),
// since the ImGui inspector exposes the same surface as the Qt one — and
// after the shared render helpers (py_lit / num_str / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // Stock toolchain; Dear ImGui and (when absent) GLFW are fetched at
        // configure time — imgui ships no CMakeLists, so its sources are
        // compiled straight into the target. rosetta's include dir is on the
        // path only for the header-only, reflection-free imgui_runtime.h.
        constexpr std::string_view IMGX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain Dear ImGui + GLFW + OpenGL3: NO C++26, NO reflection. rosetta's include
# dir is on the path only for the header-only imgui_runtime.h widget kit.
#
# EXCEPTION — inline-annotated headers: the generated inspector #includes the
# bound headers, so when they carry INLINE [[=rosetta::...]] annotations a
# stock compiler cannot parse them. Configure with -DROSETTA_IMGUI_CPP26=ON to
# build with the C++26 / P2996 toolchain instead (out-of-line .ann.json
# side-cars keep the default stock build).
cmake_minimum_required(VERSION 3.18)

option(ROSETTA_IMGUI_CPP26
    "Build with the C++26/P2996 toolchain (needed only when the bound headers carry inline annotations)"
    OFF)
if(ROSETTA_IMGUI_CPP26)
    set(CLANG_P2996_ROOT "{{CPP26_ROOT}}"
        CACHE PATH "C++26 / P2996 reflection toolchain root (clang-p2996 build dir)")
    set(ROSETTA_STDLIB "{{CPP26_LIB}}"
        CACHE PATH "Directory holding the fork's libc++ / libc++abi (-L and -rpath)")
    if(NOT CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER "{{CPP26_CXX}}")
    endif()
endif()

project({{LIB}}_imgui CXX)

if(ROSETTA_IMGUI_CPP26)
    set(CMAKE_CXX_STANDARD 26)
else()
    set(CMAKE_CXX_STANDARD 20)
endif()
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(OpenGL REQUIRED)
include(FetchContent)

# GLFW: an installed package wins; otherwise fetch and build it.
find_package(glfw3 3.3 QUIET)
if(NOT TARGET glfw)
    set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_TESTS    OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_DOCS     OFF CACHE BOOL "" FORCE)
    set(GLFW_INSTALL        OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(glfw
        GIT_REPOSITORY https://github.com/glfw/glfw.git
        GIT_TAG        3.4)
    FetchContent_MakeAvailable(glfw)
endif()

# Dear ImGui (no CMakeLists upstream — sources compile into the target).
FetchContent_Declare(imgui
    GIT_REPOSITORY https://github.com/ocornut/imgui.git
    GIT_TAG        v1.92.8)
FetchContent_MakeAvailable(imgui)

add_executable({{LIB}}_imgui main.cpp imgui_inspector.cpp
    ${imgui_SOURCE_DIR}/imgui.cpp
    ${imgui_SOURCE_DIR}/imgui_draw.cpp
    ${imgui_SOURCE_DIR}/imgui_tables.cpp
    ${imgui_SOURCE_DIR}/imgui_widgets.cpp
    ${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp
    ${imgui_SOURCE_DIR}/backends/imgui_impl_opengl3.cpp
    ${imgui_SOURCE_DIR}/misc/cpp/imgui_stdlib.cpp)

target_include_directories({{LIB}}_imgui PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}}
    ${imgui_SOURCE_DIR}
    ${imgui_SOURCE_DIR}/backends
    ${imgui_SOURCE_DIR}/misc/cpp)

if(APPLE)
    target_compile_definitions({{LIB}}_imgui PRIVATE GL_SILENCE_DEPRECATION)
endif()

if(ROSETTA_IMGUI_CPP26)
    # Inline annotations pull in <rosetta/annotations.h> → <experimental/meta>,
    # which needs the fork's flags and libc++ (only glfw, a C target, stays on
    # the system toolchain).
    target_compile_options({{LIB}}_imgui PRIVATE
        -freflection -freflection-latest -fexperimental-library -fannotation-attributes)
    if(APPLE)
        # Apple clang enables ObjC blocks implicitly; the fork must be told —
        # the macOS SDK frameworks glfw3native.h pulls in typedef them.
        target_compile_options({{LIB}}_imgui PRIVATE -fblocks)
    endif()
    target_link_options({{LIB}}_imgui PRIVATE
        -nostdlib++ -L${ROSETTA_STDLIB} -Wl,-rpath,${ROSETTA_STDLIB} -lc++ -lc++abi)
endif()

set(ROSETTA_BINDING_TARGET {{LIB}}_imgui)
{{USER_LIB_BLOCK}}
target_link_libraries({{LIB}}_imgui PRIVATE glfw OpenGL::GL)
)CMK";

        // README build section — kept next to IMGX_CMAKE so the documented
        // steps can't drift from the template. Stock C++20 by default (the
        // emitted sources are pre-expanded); the ROSETTA_IMGUI_CPP26 escape
        // hatch mirrors the template's inline-annotation exception.
        constexpr std::string_view IMGX_README_BUILD = R"MD(## Build

Prerequisites: a stock C++20 compiler, CMake >= 3.18, OpenGL, and network
access at configure time — Dear ImGui (and GLFW, unless a glfw3 >= 3.3 package
is already installed) are fetched with FetchContent and compiled into the
target. No C++26 / reflection toolchain is needed by default.

```sh
cmake -S . -B build
cmake --build build
./build/{{LIB}}_imgui
```

Exception: if the bound headers carry inline `[[=rosetta::...]]` annotations a
stock compiler cannot parse them — configure with the C++26 / P2996 toolchain:

```sh
cmake -S . -B build -DROSETTA_IMGUI_CPP26=ON -DCLANG_P2996_ROOT=/path/to/clang-p2996/build
```

Set `ROSETTA_IMGUI_FRAMES=N` to auto-exit after N frames (smoke tests / CI).
)MD";

        // C-string literal for the generated source.
        inline std::string imgx_str(const std::string &s) { return "\"" + py_lit(s) + "\""; }

        // Widget hint from the member's annotations (imgw::Hint values).
        // spin and textfield both map to H_SPIN — a typed input box (with
        // clamping when ranged) rather than a slider/drag.
        inline std::string imgx_hint(const std::vector<std::any> &anns) {
            if (find_annotation<rosetta::widget::slider_tag>(anns)) {
                return "rosetta::imgw::H_SLIDER";
            }
            if (find_annotation<rosetta::widget::spin_tag>(anns) ||
                find_annotation<rosetta::widget::textfield_tag>(anns)) {
                return "rosetta::imgw::H_SPIN";
            }
            return "rosetta::imgw::H_NONE";
        }

        // String-field widget hints (each pairs with a dedicated imgw helper).
        inline bool imgx_has_color(const std::vector<std::any> &anns) {
            return find_annotation<rosetta::widget::color_tag>(anns) != nullptr;
        }
        inline bool imgx_has_multiline(const std::vector<std::any> &anns) {
            return find_annotation<rosetta::widget::multiline_tag>(anns) != nullptr;
        }
        inline bool imgx_has_radio(const std::vector<std::any> &anns) {
            return find_annotation<rosetta::widget::radio_tag>(anns) != nullptr;
        }
        inline bool imgx_has_file(const std::vector<std::any> &anns) {
            return find_annotation<rosetta::widget::file_tag>(anns) != nullptr;
        }

        // One field → one imgw:: helper call bound to `t.<name>`.
        inline std::string imgx_field(const GenField &f) {
            const std::string disp = imgx_str(qtx_display(f.name, f.annotations));
            const std::string tip  = imgx_str(f.doc);
            const std::string ro   = f.is_readonly ? "true" : "false";
            const std::string mem  = "t." + f.name;
            if (f.type.kind == "boolean") {
                return "    rosetta::imgw::checkbox(" + disp + ", " + mem + ", " + ro + ", " +
                       tip + ");\n";
            }
            if (f.type.kind == "number") {
                return "    rosetta::imgw::scalar(" + disp + ", " + mem + ", " + ro + ", " +
                       (f.range.has ? "true" : "false") + ", " + num_str(f.range.min) + ", " +
                       num_str(f.range.max) + ", " + tip + ", " + imgx_hint(f.annotations) +
                       ");\n";
            }
            if (f.type.kind == "string") {
                if (!f.choices.empty()) {
                    std::string ch = "{";
                    for (std::size_t i = 0; i < f.choices.size(); ++i) {
                        ch += (i ? ", " : "") + imgx_str(f.choices[i]);
                    }
                    ch += "}";
                    // widget::radio renders the choices as a radio group.
                    const char *w = imgx_has_radio(f.annotations) ? "radio" : "combo";
                    return "    rosetta::imgw::" + std::string(w) + "(" + disp + ", " + mem +
                           ", " + ch + ", " + ro + ", " + tip + ");\n";
                }
                if (imgx_has_color(f.annotations)) {
                    return "    rosetta::imgw::color_text(" + disp + ", " + mem + ", " + ro +
                           ", " + tip + ");\n";
                }
                if (imgx_has_multiline(f.annotations)) {
                    return "    rosetta::imgw::multiline(" + disp + ", " + mem + ", " + ro +
                           ", " + tip + ");\n";
                }
                if (imgx_has_file(f.annotations)) {
                    return "    rosetta::imgw::file(" + disp + ", " + mem + ", " + ro + ", " +
                           tip + ");\n";
                }
                return "    rosetta::imgw::text(" + disp + ", " + mem + ", " + ro + ", " + tip +
                       ");\n";
            }
            if (f.type.kind == "enum" && !f.type.enumerators.empty()) {
                const std::string e = f.type.object;
                std::string items = "{";
                for (std::size_t i = 0; i < f.type.enumerators.size(); ++i) {
                    const std::string &n = f.type.enumerators[i].name;
                    items += (i ? ", " : "");
                    items += "{" + imgx_str(n) + ", " + e + "::" + n + "}";
                }
                items += "}";
                return "    rosetta::imgw::enum_combo(" + disp + ", " + mem + ", " + items +
                       ", " + ro + ", " + tip + ");\n";
            }
            if (f.type.kind == "vector" && !f.type.element.empty() &&
                f.type.element.front().kind == "number") {
                return "    rosetta::imgw::scalar_vector(" + disp + ", " + mem + ", " + ro +
                       ", " + tip + ");\n";
            }
            return "    rosetta::imgw::unsupported(" + disp + ", " + tip + ");\n";
        }

        // One method → a call button that stringifies the result. A method
        // WITH parameters wraps the button in a tree node holding one input
        // per parameter (persistent `static` state — immediate mode redraws
        // each frame); a zero-argument method is just the bare button.
        // Skipped when the signature can't cross the scalar boundary (same
        // rule as the Qt inspector).
        inline std::string imgx_method(const std::string &cls, const GenMethod &m) {
            if (!qtx_method_ok(m)) {
                return {};
            }
            const std::string disp = qtx_display(m.name, m.annotations);
            std::string       btn  = disp; // bare button: the display name is the caption
            if (const auto *b = find_annotation<rosetta::button>(m.annotations); b && b->label &&
                b->label[0]) {
                btn = b->label;
            }
            std::string s;
            const bool  bare = m.params.empty();
            if (bare) {
                s += "    {\n"; // scope the per-method static result
            } else {
                s += "    if (ImGui::TreeNode(" +
                     imgx_str(disp + (m.is_static ? " (static)" : "")) + ")) {\n";
            }
            // Persistent argument state + one widget per parameter.
            std::string args;
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                const GenType    &t  = m.params[i].type;
                const std::string an = "a" + std::to_string(i);
                const std::string lb = imgx_str(m.params[i].name);
                if (t.kind == "string") {
                    s += "        static std::string " + an + ";\n";
                    s += "        rosetta::imgw::text(" + lb + ", " + an + ", false, \"\");\n";
                } else if (t.kind == "boolean") {
                    s += "        static bool " + an + " = false;\n";
                    s += "        rosetta::imgw::checkbox(" + lb + ", " + an + ", false, \"\");\n";
                } else { // number — exact spelling keeps the call implicit-cast free
                    const std::string ty = qualify_std(t.spelling.empty() ? "double" : t.spelling);
                    s += "        static " + ty + " " + an + " = {};\n";
                    s += "        rosetta::imgw::scalar(" + lb + ", " + an +
                         ", false, false, 0, 0, \"\");\n";
                }
                args += (i ? ", " : "") + an;
            }
            const std::string call =
                (m.is_static ? cls + "::" : "t.") + m.name + "(" + args + ")";
            std::string expr;
            if (m.ret.kind == "void") {
                expr = call + ", std::string(\"ok\")";
            } else if (m.ret.kind == "string") {
                expr = call;
            } else if (m.ret.kind == "boolean") {
                expr = "(" + call + ") ? \"true\" : \"false\"";
            } else { // number
                expr = "std::to_string(" + call + ")";
            }
            s += "        static std::string result;\n";
            s += "        if (ImGui::Button(" + imgx_str(btn) + ")) {\n";
            s += "            try { result = (" + expr + "); }\n";
            s += "            catch (const std::exception &e) { result = e.what(); }\n";
            s += "        }\n";
            s += "        if (!result.empty()) { ImGui::SameLine(); "
                 "ImGui::TextUnformatted(result.c_str()); }\n";
            if (!m.doc.empty()) {
                s += "        rosetta::imgw::help_tip(" + imgx_str(m.doc) + ");\n";
            }
            if (!bare) {
                s += "        ImGui::TreePop();\n";
            }
            s += "    }\n";
            return s;
        }

        inline std::string imgx_draw_fn(const GenClass &k) {
            std::string s = "void rosetta_imgui::draw_" + k.name + "(" + k.name + " &t) {\n";
            for (const auto &f : k.fields) {
                s += imgx_field(f);
            }
            bool any_method = false;
            for (const auto &m : k.methods) {
                if (!m.is_extension && qtx_method_ok(m)) {
                    any_method = true;
                }
            }
            if (any_method) {
                s += "    ImGui::SeparatorText(\"methods\");\n";
                for (const auto &m : k.methods) {
                    if (m.is_extension) {
                        continue; // extensions: no member access pattern here
                    }
                    s += imgx_method(k.name, m);
                }
            }
            s += "}\n\n";
            return s;
        }

        inline std::string imgx_header(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n#pragma once\n\n";
            auto add = [&](const std::string &h) { append_include(s, h); };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            s += using_namespaces_of(c); // `using namespace` for namespaced user types
            s += "\nnamespace rosetta_imgui {\n";
            s += "    // Immediate-mode: call each frame between ImGui::NewFrame()/Render().\n";
            for (const auto &k : c.classes) {
                s += "    void draw_" + k.name + "(" + k.name + " &target);\n";
            }
            s += "} // namespace rosetta_imgui\n";
            return s;
        }

        inline std::string imgx_source(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n";
            s += "#include \"imgui_inspector.h\"\n";
            s += "#include <rosetta/visitors/imgui_runtime.h>\n";
            s += "#include <stdexcept>\n#include <string>\n\n";
            for (const auto &k : c.classes) {
                s += imgx_draw_fn(k);
            }
            return s;
        }

        inline std::string imgx_main(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n";
            s += "// Demo: one inspector tab per default-constructible class.\n";
            s += "// ROSETTA_IMGUI_FRAMES=N auto-exits after N frames (smoke tests / CI).\n";
            s += "#include \"imgui_inspector.h\"\n";
            s += "#include <imgui.h>\n#include <imgui_impl_glfw.h>\n"
                 "#include <imgui_impl_opengl3.h>\n#include <GLFW/glfw3.h>\n"
                 "#include <cstdlib>\n\n";
            s += "int main() {\n";
            s += "    if (!glfwInit()) { return 1; }\n";
            s += "    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);\n";
            s += "    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);\n";
            s += "    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);\n";
            s += "    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE);\n";
            s += "    GLFWwindow *window = glfwCreateWindow(560, 640, \"" + c.lib +
                 " inspector\", nullptr, nullptr);\n";
            s += "    if (!window) { glfwTerminate(); return 1; }\n";
            s += "    glfwMakeContextCurrent(window);\n";
            s += "    glfwSwapInterval(1);\n";
            s += "    IMGUI_CHECKVERSION();\n";
            s += "    ImGui::CreateContext();\n";
            s += "    ImGui::GetIO().IniFilename = nullptr; // no imgui.ini litter\n";
            s += "    ImGui_ImplGlfw_InitForOpenGL(window, true);\n";
            s += "    ImGui_ImplOpenGL3_Init(\"#version 150\");\n\n";
            s += "    long frames = -1; // -1: run until the window closes\n";
            s += "    if (const char *e = std::getenv(\"ROSETTA_IMGUI_FRAMES\")) { frames = "
                 "std::atol(e); }\n\n";
            s += "    while (!glfwWindowShouldClose(window)) {\n";
            s += "        if (frames >= 0 && frames-- == 0) { break; }\n";
            s += "        glfwPollEvents();\n";
            s += "        ImGui_ImplOpenGL3_NewFrame();\n";
            s += "        ImGui_ImplGlfw_NewFrame();\n";
            s += "        ImGui::NewFrame();\n\n";
            s += "        const ImGuiViewport *vp = ImGui::GetMainViewport();\n";
            s += "        ImGui::SetNextWindowPos(vp->WorkPos);\n";
            s += "        ImGui::SetNextWindowSize(vp->WorkSize);\n";
            s += "        ImGui::Begin(\"" + c.lib +
                 "\", nullptr,\n                     ImGuiWindowFlags_NoDecoration | "
                 "ImGuiWindowFlags_NoMove |\n                     "
                 "ImGuiWindowFlags_NoSavedSettings);\n";
            s += "        if (ImGui::BeginTabBar(\"classes\")) {\n";
            for (const auto &k : c.classes) {
                if (!k.is_default_constructible) {
                    continue;
                }
                s += "            if (ImGui::BeginTabItem(\"" + k.name + "\")) {\n";
                s += "                static " + k.name + " " + k.name + "_obj;\n";
                s += "                rosetta_imgui::draw_" + k.name + "(" + k.name + "_obj);\n";
                s += "                ImGui::EndTabItem();\n";
                s += "            }\n";
            }
            s += "            ImGui::EndTabBar();\n";
            s += "        }\n";
            s += "        ImGui::End();\n\n";
            s += "        ImGui::Render();\n";
            s += "        int w = 0, h = 0;\n";
            s += "        glfwGetFramebufferSize(window, &w, &h);\n";
            s += "        glViewport(0, 0, w, h);\n";
            s += "        glClearColor(0.10f, 0.11f, 0.13f, 1.0f);\n";
            s += "        glClear(GL_COLOR_BUFFER_BIT);\n";
            s += "        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());\n";
            s += "        glfwSwapBuffers(window);\n";
            s += "    }\n\n";
            s += "    ImGui_ImplOpenGL3_Shutdown();\n";
            s += "    ImGui_ImplGlfw_Shutdown();\n";
            s += "    ImGui::DestroyContext();\n";
            s += "    glfwDestroyWindow(window);\n";
            s += "    glfwTerminate();\n";
            s += "    return 0;\n}\n";
            return s;
        }

        inline void ImGuiExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "imgui-expanded";
            write_file(dir / "imgui_inspector.h", imgx_header(c));
            write_file(dir / "imgui_inspector.cpp", imgx_source(c));
            write_file(dir / "main.cpp", imgx_main(c));
            write_file(dir / "CMakeLists.txt", render_meta(IMGX_CMAKE, c));
            write_file(dir / "README.md",
                       readme("imgui-expanded", c, subst(IMGX_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
