// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) CxxWrap / jlcxx backend. Included by
// inline/generate.hxx after python_expanded_backend.h (whose qualify_std() it
// reuses) and after the shared render helpers (subst / num_str / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // A stock-toolchain CMake: C++20, JlCxx located through Julia's own
        // CxxWrap package. No clang-p2996, no reflection flags, no fork libc++
        // — which is precisely why <jlcxx/stl.hpp> (std::vector support)
        // compiles here while the thin julia backend must skip vectors.
        constexpr std::string_view JULIAX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# These bindings are plain jlcxx: NO C++26, NO reflection, NO rosetta headers.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

# Locate JlCxx (from libcxxwrap-julia / CxxWrap.jl). If it isn't hinted via
# JlCxx_DIR or CMAKE_PREFIX_PATH, ask Julia's CxxWrap for the prefix that
# ships the JlCxx CMake package. --startup-file=no keeps a user startup.jl
# from polluting the captured path.
if(NOT JlCxx_DIR AND NOT DEFINED CMAKE_PREFIX_PATH)
    execute_process(
        COMMAND julia --startup-file=no -e "using CxxWrap; print(CxxWrap.prefix_path())"
        OUTPUT_VARIABLE CXXWRAP_PREFIX
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(CXXWRAP_PREFIX)
        set(CMAKE_PREFIX_PATH "${CXXWRAP_PREFIX}")
    endif()
endif()
find_package(JlCxx REQUIRED)

add_library({{LIB}} SHARED auto_jlcxx.cpp)

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}})
target_link_libraries({{LIB}} PRIVATE
    JlCxx::cxxwrap_julia
    JlCxx::cxxwrap_julia_stl)

{{USER_LIB_BLOCK}}

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        // Build/Use section of the generated README — every claim traces to
        // JULIAX_CMAKE above (stock C++20, JlCxx auto-located through Julia's
        // CxxWrap, post-build copy) or to the jx_loader() output ({{LIB}}.jl
        // resolves lib{{LIB}} relative to its own directory via @__DIR__).
        constexpr std::string_view JULIAX_README_BUILD = R"MD(## Build

Plain jlcxx — no C++26, no reflection toolchain: any stock C++20 compiler
works. Only prerequisite: the Julia package **CxxWrap** (the CMakeLists locates
JlCxx by running `julia -e "using CxxWrap; print(CxxWrap.prefix_path())"`; hint
it manually with `-DJlCxx_DIR=…` or `-DCMAKE_PREFIX_PATH=…` if `julia` is not
on PATH).

```sh
cmake -S . -B build
cmake --build build   # post-build step copies lib{{LIB}}.{dylib,so} next to {{LIB}}.jl
```

## Use

The generated `{{LIB}}.jl` module wraps the library through CxxWrap, resolving
`lib{{LIB}}` in its own directory (where the post-build copy put it):

```julia
include("{{LIB}}.jl")
using .{{LIB}}
```
)MD";

        // --- Marshalling gates -------------------------------------------------
        // jlcxx's boundary rules: scalars / bool / std::string / enums map
        // natively; a registered class crosses as a wrapped object; with
        // <jlcxx/stl.hpp> a std::vector<T> registers lazily on first use (any
        // T, including bound classes). What can't cross: std::function (no
        // Julia-closure -> std::function conversion), std::array (not an stl.hpp
        // container), unregistered objects/pointees, and mutable references to
        // NON-class types (the converted argument is a temporary). Copies
        // happen wherever python-expanded copies (field accessors, by-value
        // crossings), so the same copyability gates apply.

        inline bool jx_is_bound(const std::string &name, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (k.name == name) {
                    return true;
                }
            }
            return false;
        }

        inline bool jx_marshalable(const GenType &t, const GenContext &c) {
            // Raw pointer to a bound class: jlcxx passes/returns it as a
            // CxxPtr-style non-owning handle to the registered type.
            if (t.is_pointer) {
                return jx_is_bound(t.object, c);
            }
            if (t.kind == "unknown") {
                return false; // std::function & friends
            }
            if (t.kind == "object") {
                return jx_is_bound(t.object, c);
            }
            if (t.kind == "vector") {
                if (t.element.empty()) {
                    return true;
                }
                if (t.element.front().is_pointer) {
                    return false; // container of raw pointers stays out
                }
                return jx_marshalable(t.element.front(), c);
            }
            return true; // number / boolean / string / enum / void
        }

        // Copies at the boundary need copyable payloads (same rule as
        // px_copyable — field accessors and by-value crossings copy).
        inline bool jx_copyable(const GenType &t) {
            if (t.kind == "object") {
                return t.copy_constructible && t.copy_assignable;
            }
            if (t.kind == "vector") {
                return t.element.empty() || jx_copyable(t.element.front());
            }
            return true;
        }

        inline bool jx_method_ok(const GenMethod &m, const GenContext &c) {
            if (m.ret.kind != "void" && !jx_marshalable(m.ret, c)) {
                return false;
            }
            // A class / vector return crosses by value (an lvalue-ref return is
            // copied through a wrapping lambda, matching pybind's `automatic`
            // policy), so it must be copy-constructible.
            if (m.ret.kind == "object" && !m.ret.copy_constructible) {
                return false;
            }
            if (m.ret.kind == "vector" && !jx_copyable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!jx_marshalable(p.type, c)) {
                    return false;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false; // by-value class parameter copy-constructs
                }
                if (p.type.kind == "vector" && !jx_copyable(p.type)) {
                    return false;
                }
                // Mutable ref to a NON-class type (std::string&, index_t&): an
                // out-parameter — the converted argument is a temporary.
                if (p.type.kind != "object" && p.is_mutable_ref) {
                    return false;
                }
            }
            return true;
        }

        // Both field accessors copy (getter by value, setter by copy
        // assignment) — the python-expanded rule.
        inline bool jx_field_ok(const GenField &f, const GenContext &c) {
            if (!jx_marshalable(f.type, c)) {
                return false;
            }
            if (f.type.kind == "object" && !f.type.copy_constructible) {
                return false; // even the getter would copy
            }
            return jx_copyable(f.type) || f.is_readonly;
        }

        // Is the setter emittable, or must the field stay getter-only?
        inline bool jx_field_readonly(const GenField &f) {
            if (f.is_readonly) {
                return true;
            }
            return !jx_copyable(f.type);
        }

        // A compilable C++ spelling for an IR type (value form). Exact
        // spellings via param_cpp are preferred; this covers the spots that
        // don't carry them (field types, ArrayRef adapters, extensions).
        inline std::string jx_cpp_type(const GenType &t) {
            if (t.kind == "vector") {
                return "std::vector<" +
                       (t.element.empty() ? std::string("double")
                                          : jx_cpp_type(t.element.front())) +
                       ">";
            }
            if (t.kind == "object" || t.kind == "enum") {
                return t.object;
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "number") {
                return t.spelling.empty() ? "double" : t.spelling;
            }
            return qualify_std(t.spelling);
        }

        // Vector parameters whose element is numeric can ALSO be taken as a
        // jlcxx::ArrayRef — a zero-copy view of a plain Julia Vector — so the
        // caller isn't forced to build a StdVector first. Julia's multiple
        // dispatch picks between this overload and the exact one.
        inline bool jx_numeric_vector(const GenType &t) {
            return t.kind == "vector" && !t.element.empty() &&
                   t.element.front().kind == "number";
        }
        inline bool jx_wants_arrayref_overload(const std::vector<GenParam> &params) {
            bool any = false;
            for (const auto &p : params) {
                if (p.type.kind == "vector") {
                    if (!jx_numeric_vector(p.type)) {
                        return false; // a non-numeric vector param has no ArrayRef form
                    }
                    any = true;
                }
            }
            return any;
        }

        // (lambda decls, forwarded args) for the ArrayRef overload: numeric
        // vector params become ArrayRef views (copied into a std::vector at
        // the call), everything else keeps its exact spelling when available.
        struct JxAdapterParams {
            std::string decls;
            std::string args;
        };
        inline JxAdapterParams jx_arrayref_params(const std::vector<GenParam>    &params,
                                                  const std::vector<std::string> &param_cpp) {
            JxAdapterParams a;
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                if (j) {
                    a.decls += ", ";
                    a.args += ", ";
                }
                const GenType &t = params[j].type;
                if (jx_numeric_vector(t)) {
                    const std::string el = jx_cpp_type(t.element.front());
                    a.decls += "jlcxx::ArrayRef<" + el + "> " + an;
                    a.args += "std::vector<" + el + ">(" + an + ".begin(), " + an + ".end())";
                } else if (j < param_cpp.size() && !param_cpp[j].empty()) {
                    a.decls += qualify_std(param_cpp[j]) + " " + an;
                    a.args += an;
                } else if (t.is_pointer) {
                    a.decls += t.object + " *" + an;
                    a.args += an;
                } else if (t.kind == "object") {
                    a.decls += "const " + jx_cpp_type(t) + " &" + an;
                    a.args += an;
                } else {
                    a.decls += jx_cpp_type(t) + " " + an;
                    a.args += an;
                }
            }
            return a;
        }

        // Exact-spelling (decls, args) for the wrapping lambdas (ref-return
        // copies, receiver-first calls).
        inline JxAdapterParams jx_exact_params(const std::vector<std::string> &param_cpp) {
            JxAdapterParams a;
            for (std::size_t j = 0; j < param_cpp.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                if (j) {
                    a.decls += ", ";
                    a.args += ", ";
                }
                a.decls += qualify_std(param_cpp[j]) + " " + an;
                a.args += an;
            }
            return a;
        }

        // One enum: a jlcxx bits type + one module constant per enumerator.
        // Constants are PREFIXED with the enum name (`Kind_Point`) — Julia
        // module constants share one flat namespace with the registered types,
        // so a bare enumerator name collides with a same-named class (e.g.
        // `Kind::Point` vs `class Point` — "Duplicate registration") the
        // moment both are bound.
        inline std::string jx_enum(const GenEnum &e) {
            std::string s =
                "    mod.add_bits<" + e.name + ">(\"" + e.name + "\", jlcxx::julia_type(\"CppEnum\"));\n";
            for (const auto &v : e.values) {
                s += "    mod.set_const(\"" + e.name + "_" + v.name + "\", " + e.name +
                     "::" + v.name + ");\n";
            }
            return s;
        }

        // One field: getter `name(obj)` + mutating setter `name!(obj, v)` —
        // Julia's `!` convention, matching the thin visitor. readonly (or a
        // non-copy-assignable type) drops the setter; a numeric `range` field
        // validates on assignment; a numeric-vector field gains an ArrayRef
        // setter overload so `tags!(m, [1.0, 2.0])` takes a plain Vector.
        inline std::string jx_field(const GenClass &k, const GenField &f) {
            const std::string self = k.name;
            const std::string ty   = jx_cpp_type(f.type);
            std::string       s;
            s += "    c.method(\"" + f.name + "\", [](const " + self + " &s) { return s." +
                 f.name + "; });\n";
            if (jx_field_readonly(f)) {
                return s;
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string lo = num_str(f.range.min);
                const std::string hi = num_str(f.range.max);
                s += "    c.method(\"" + f.name + "!\", [](" + self + " &s, " + ty + " v) {\n";
                s += "        if (v < " + lo + " || v > " + hi + ")\n";
                s += "            throw std::out_of_range(\"" + f.name + " out of range [" + lo +
                     ", " + hi + "]\");\n";
                s += "        s." + f.name + " = v;\n";
                s += "    });\n";
                return s;
            }
            s += "    c.method(\"" + f.name + "!\", [](" + self + " &s, const " + ty +
                 " &v) { s." + f.name + " = v; });\n";
            if (jx_numeric_vector(f.type)) {
                const std::string el = jx_cpp_type(f.type.element.front());
                s += "    c.method(\"" + f.name + "!\", [](" + self + " &s, jlcxx::ArrayRef<" +
                     el + "> v) { s." + f.name + ".assign(v.begin(), v.end()); });\n";
            }
            return s;
        }

        // One method. jlcxx makes the object the first Julia argument
        // (`name(obj, ...)`); a static becomes a module-level function. The
        // member pointer is disambiguated with an explicit cast to the exact
        // signature — dropping any `noexcept` (jlcxx's method() templates
        // don't match noexcept pointers; the conversion is implicit). An
        // lvalue-ref class/vector return is wrapped in a lambda that returns
        // by VALUE — the same copy pybind's `automatic` policy makes — so the
        // Julia side always holds a plain object. An extension method binds
        // its free function directly (receiver-first, exactly jlcxx's shape).
        inline std::string jx_method(const GenClass &k, const GenMethod &m) {
            const std::string owner = m.is_static ? "mod" : "c";
            const bool        copy_ret =
                m.ret_is_ref && (m.ret.kind == "object" || m.ret.kind == "vector");
            std::string primary;
            if (m.is_extension) {
                primary = "&" + m.ext_qualified;
            } else if (copy_ret) {
                const JxAdapterParams xp = jx_exact_params(m.param_cpp);
                std::string           decls, call;
                if (m.is_static) {
                    decls = xp.decls;
                    call  = k.name + "::" + m.name + "(" + xp.args + ")";
                } else {
                    decls = (m.is_const ? "const " : "") + k.name + " &self" +
                            (xp.decls.empty() ? "" : ", " + xp.decls);
                    call = "self." + m.name + "(" + xp.args + ")";
                }
                primary = "[](" + decls + ") -> " + jx_cpp_type(m.ret) + " { return " + call +
                          "; }";
            } else {
                std::string args;
                for (std::size_t j = 0; j < m.param_cpp.size(); ++j) {
                    args += (j ? ", " : "") + qualify_std(m.param_cpp[j]);
                }
                const std::string quals = m.is_const ? " const" : ""; // noexcept dropped
                const std::string ret   = qualify_std(m.ret_cpp);
                const std::string fp =
                    m.is_static ? (ret + " (*)(" + args + ")")
                                : (ret + " (" + k.name + "::*)(" + args + ")" + quals);
                primary = "static_cast<" + fp + ">(&" + k.name + "::" + m.name + ")";
            }
            std::string s =
                "    " + owner + ".method(\"" + m.name + "\", " + primary + ");\n";
            // Numeric-vector parameters: add the plain-Julia-Vector overload.
            if (jx_wants_arrayref_overload(m.params) && !m.is_extension) {
                const JxAdapterParams ap = jx_arrayref_params(m.params, m.param_cpp);
                std::string           decls, call;
                if (m.is_static) {
                    decls = ap.decls;
                    call  = k.name + "::" + m.name + "(" + ap.args + ")";
                } else {
                    decls = (m.is_const ? "const " : "") + k.name + " &self" +
                            (ap.decls.empty() ? "" : ", " + ap.decls);
                    call = "self." + m.name + "(" + ap.args + ")";
                }
                s += "    " + owner + ".method(\"" + m.name + "\", [](" + decls +
                     ") { return " + call + "; });\n";
            }
            return s;
        }

        // The constructors: `.constructor<exact spellings...>()` for each
        // marshalable one (jlcxx dispatches overloads through Julia's multiple
        // dispatch), a factory-lambda variant taking ArrayRef views when a
        // ctor names numeric vectors, and a synthetic default when the type is
        // default-constructible (jlcxx guards against double registration).
        // An abstract class gets none.
        inline std::string jx_ctors(const GenClass &k, const GenContext &c) {
            std::string s;
            bool        saw_default = false;
            for (std::size_t i = 0; !k.is_abstract && i < k.ctor_param_cpp.size(); ++i) {
                bool ok = true;
                for (const auto &p : k.ctors[i]) {
                    ok = ok && jx_marshalable(p.type, c) &&
                         (p.type.kind != "object" || p.is_ref || p.type.copy_constructible) &&
                         (p.type.kind != "vector" || jx_copyable(p.type)) &&
                         (p.type.kind == "object" || !p.is_mutable_ref);
                }
                if (!ok) {
                    continue;
                }
                const auto &params = k.ctor_param_cpp[i];
                if (params.empty()) {
                    saw_default = true;
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    args += (j ? ", " : "") + qualify_std(params[j]);
                }
                s += "    c.constructor<" + args + ">();\n";
                if (jx_wants_arrayref_overload(k.ctors[i])) {
                    const JxAdapterParams ap = jx_arrayref_params(k.ctors[i], params);
                    s += "    c.constructor([](" + ap.decls + ") { return new " + k.name + "(" +
                         ap.args + "); });\n";
                }
            }
            if (!saw_default && !k.is_abstract && k.is_default_constructible) {
                s += "    c.constructor<>();\n";
            }
            return s;
        }

        // First bound base of a class, or "" — jlcxx (like embind) registers
        // single inheritance only.
        inline std::string jx_bound_base(const GenClass &k, const GenContext &c) {
            auto qualified = [](const GenClass &g) {
                return g.name_space.empty() ? g.name : g.name_space + "::" + g.name;
            };
            for (const auto &b : k.bases) {
                for (const auto &g : c.classes) {
                    if (qualified(g) == b) {
                        return b;
                    }
                }
            }
            return std::string{};
        }

        // Registration is TWO-PHASE (the canonical jlcxx pattern for
        // interdependent types): first add_type for every class, then populate
        // constructors/fields/methods. jlcxx resolves each method's argument
        // and return types at registration time, so a one-pass emission would
        // fail with "No appropriate factory for type X" whenever a method of
        // an earlier class names a later one (Model::addSurface(Surface&)).
        inline std::string jx_class_decl(const GenClass &k, const GenContext &c) {
            const std::string base = jx_bound_base(k, c);
            std::string       s;
            s += "    auto c_" + k.name + " = mod.add_type<" + k.name + ">(\"" + k.name + "\"";
            if (!base.empty()) {
                // Bound single base (jlcxx, like embind, registers one). The
                // base's add_type must precede this — i.e. list the base first
                // in the manifest.
                s += ", jlcxx::julia_base_type<" + base + ">()";
            }
            s += ");\n";
            return s;
        }

        inline std::string jx_class_members(const GenClass &k, const GenContext &c) {
            std::string s = "    {\n";
            s += "    auto &c = c_" + k.name + ";\n";
            s += jx_ctors(k, c);
            for (const auto &f : k.fields) {
                if (!jx_field_ok(f, c)) {
                    continue; // type jlcxx can't marshal — see jx_field_ok
                }
                s += jx_field(k, f);
            }
            for (const auto &m : k.methods) {
                if (!jx_method_ok(m, c)) {
                    continue; // signature the emitted jlcxx line could not compile
                }
                s += jx_method(k, m);
            }
            s += "    }\n";
            return s;
        }

        // The `<lib>.jl` loader: a Julia module wrapping the shared library
        // through CxxWrap. `include("<lib>.jl"); using .<lib>` is all a script
        // needs (the post-build copy puts the library beside it).
        inline std::string jx_loader(const GenContext &c) {
            std::string s;
            s += "# Generated by rosetta::generate — do not edit by hand.\n";
            s += "module " + c.lib + "\n";
            s += "using CxxWrap\n";
            s += "@wrapmodule(() -> joinpath(@__DIR__, \"lib" + c.lib + "\"))\n";
            s += "function __init__()\n";
            s += "    @initcxx\n";
            s += "end\n";
            s += "end # module\n";
            return s;
        }

        inline std::string julia_expanded_source(const GenContext &c) {
            std::string body;
            for (const auto &e : c.enums) {
                body += jx_enum(e);
            }
            // Phase 1: register every class; phase 2: populate members (see
            // jx_class_decl for why the split is required).
            for (const auto &k : c.classes) {
                body += jx_class_decl(k, c);
            }
            for (const auto &k : c.classes) {
                body += jx_class_members(k, c);
            }
            for (const auto &f : c.functions) {
                GenMethod probe; // free functions go through the same gates
                probe.ret        = f.ret;
                probe.params     = f.params;
                probe.ret_is_ref = false; // GenFunction doesn't carry it; by-value assumed
                if (!jx_method_ok(probe, c)) {
                    continue;
                }
                body += "    mod.method(\"" + f.name + "\", &" + f.qualified + ");\n";
                if (jx_wants_arrayref_overload(f.params)) {
                    const JxAdapterParams ap = jx_arrayref_params(f.params, {});
                    body += "    mod.method(\"" + f.name + "\", [](" + ap.decls +
                            ") { return " + f.qualified + "(" + ap.args + "); });\n";
                }
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            // User headers FIRST (types must be complete for the SuperType
            // specializations below), then jlcxx. stl.hpp registers any
            // std::vector<T> lazily on first use — including vectors of bound
            // classes — which the thin backend cannot compile (fork libc++).
            auto add = [&](const std::string &h) { append_include(out, h); };
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += "#include <jlcxx/jlcxx.hpp>\n"
                   "#include <jlcxx/stl.hpp>\n"
                   "#include <stdexcept>\n"
                   "#include <string>\n"
                   "#include <vector>\n";
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            // C++ inheritance: jlcxx requires a SuperType specialization for
            // every type registered with julia_base_type (single base).
            std::string supers;
            for (const auto &k : c.classes) {
                const std::string base = jx_bound_base(k, c);
                if (!base.empty()) {
                    supers += "    template <> struct SuperType<" + k.name + "> { typedef " +
                              base + " type; };\n";
                }
            }
            if (!supers.empty()) {
                out += "\nnamespace jlcxx {\n" + supers + "} // namespace jlcxx\n";
            }
            out += "\n// CxxWrap.jl loads this entry point (default symbol "
                   "`define_julia_module`)\n// from Julia via `@wrapmodule(() -> libpath)`.\n";
            out += "JLCXX_MODULE define_julia_module(jlcxx::Module &mod) {\n";
            out += body;
            out += "}\n";
            return out;
        }

        inline std::string JuliaExpandedBackend::render(const GenContext &c) const {
            return julia_expanded_source(c);
        }

        inline void JuliaExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "julia-expanded";
            write_file(dir / "auto_jlcxx.cpp", julia_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(JULIAX_CMAKE, c));
            write_file(dir / (c.lib + ".jl"), jx_loader(c));
            write_file(dir / "README.md",
                       readme("julia-expanded", c,
                              subst(JULIAX_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
