// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) sol2 / Lua backend. Included by
// inline/generate.hxx after python_expanded_backend.h (whose qualify_std() it
// reuses) and after the shared render helpers (subst / num_str / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // A stock-toolchain CMake: C++17, the system's Lua, sol2 (header-only,
        // fetched when not installed). No clang-p2996, no reflection flags.
        constexpr std::string_view LUAX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# These bindings are plain sol2: NO C++26, NO reflection, NO rosetta headers.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# sol2 supports Lua 5.1–5.4 and LuaJIT — NOT Lua 5.5, which changed the C API
# (lua_newstate gained a seed parameter) — so prefer a 5.4 installation.
# Override with -DLUA_INCLUDE_DIR / -DLUA_LIBRARIES. Homebrew's prefix is not
# in every CMake's default search path — hint it, and probe the keg-only
# lua@5.4 directly (FindLua never looks inside opt/lua@5.4).
if(APPLE AND EXISTS /opt/homebrew)
    list(APPEND CMAKE_PREFIX_PATH /opt/homebrew)
endif()
find_package(Lua 5.4 EXACT QUIET)
if(NOT LUA_INCLUDE_DIR)
    find_path(LUA_INCLUDE_DIR lua.h
        PATH_SUFFIXES lua5.4 lua-5.4 lua luajit-2.1
        PATHS /opt/homebrew/opt/lua@5.4/include /usr/local/opt/lua@5.4/include
              /opt/homebrew/include /usr/local/include /usr/include
        NO_DEFAULT_PATH)
    find_library(LUA_LIBRARIES NAMES lua5.4 lua-5.4 lua luajit-5.1
        PATHS /opt/homebrew/opt/lua@5.4/lib /usr/local/opt/lua@5.4/lib
              /opt/homebrew/lib /usr/local/lib /usr/lib
        NO_DEFAULT_PATH)
endif()
if(NOT LUA_INCLUDE_DIR)
    find_package(Lua QUIET) # any other 5.1–5.3 / LuaJIT
endif()
if(NOT LUA_INCLUDE_DIR)
    message(FATAL_ERROR
        "Lua not found — pass -DLUA_INCLUDE_DIR=<dir of lua.h> and -DLUA_LIBRARIES=<liblua>.")
endif()
message(STATUS "Lua headers: ${LUA_INCLUDE_DIR}")
file(STRINGS "${LUA_INCLUDE_DIR}/lua.h" _rosetta_lua_ver REGEX "define[ \t]+LUA_VERSION_NUM")
if(_rosetta_lua_ver MATCHES "50[5-9]")
    message(WARNING "Lua at ${LUA_INCLUDE_DIR} is 5.5+, which sol2 does not support "
                    "(5.1–5.4 / LuaJIT). Install lua@5.4 or pass -DLUA_INCLUDE_DIR.")
endif()

# sol2 (header-only). An installed package wins; otherwise fetch it.
find_package(sol2 QUIET CONFIG)
if(NOT sol2_FOUND)
    include(FetchContent)
    FetchContent_Declare(sol2
        GIT_REPOSITORY https://github.com/ThePhD/sol2.git
        GIT_TAG        v3.5.0)
    FetchContent_MakeAvailable(sol2)
endif()

add_library({{LIB}} MODULE auto_sol.cpp)

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    ${LUA_INCLUDE_DIR}
    {{USER_INCLUDE}})
target_link_libraries({{LIB}} PRIVATE sol2::sol2)

# On macOS a C module must NOT link liblua: the interpreter provides the Lua
# API at load time (linking a second copy of the VM corrupts its state), so
# leave the symbols undefined — exactly what luarocks does. Elsewhere link it.
if(APPLE)
    target_link_options({{LIB}} PRIVATE -undefined dynamic_lookup)
else()
    target_link_libraries({{LIB}} PRIVATE ${LUA_LIBRARIES})
endif()

# `require("{{LIB}}")` searches package.cpath for <name>.so — no "lib" prefix,
# and .so also on macOS (the default .dylib suffix is never probed).
set_target_properties({{LIB}} PROPERTIES PREFIX "" SUFFIX ".so")

{{USER_LIB_BLOCK}}

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        // Build/Use section of the generated README — every claim traces to
        // LUAX_CMAKE above (stock C++17, the Lua 5.1–5.4 / not-5.5 probe and
        // its -DLUA_* override, sol2 find_package-then-FetchContent, the
        // PREFIX ""/SUFFIX ".so" naming for require(), post-build copy).
        constexpr std::string_view LUAX_README_BUILD = R"MD(## Build

Plain sol2 — no C++26, no reflection toolchain: any stock C++17 compiler
works. Prerequisite: Lua 5.1–5.4 or LuaJIT (5.4 preferred; sol2 does **not**
support 5.5 — override the probe with `-DLUA_INCLUDE_DIR=…` and
`-DLUA_LIBRARIES=…`). sol2 itself is header-only: an installed package is
used when found, otherwise it is fetched (v3.5.0) at configure time.

```sh
cmake -S . -B build
cmake --build build   # produces {{LIB}}.so (no "lib" prefix; .so also on macOS)
```

The post-build step copies `{{LIB}}.so` next to this README.

## Use

`require` searches `package.cpath` for `{{LIB}}.so`:

```lua
package.cpath = "path/to/this/dir/?.so;" .. package.cpath
local {{LIB}} = require("{{LIB}}")
```
)MD";

        // --- Marshalling gates -------------------------------------------------
        // sol2's boundary rules differ from pybind/embind in rosetta's favor:
        // an lvalue-ref class return is pushed by REFERENCE (no copy), a method
        // taking a std::function accepts a Lua function natively, and a mutable
        // T& parameter of a registered class binds to the userdata in place.
        // What still can't cross: types sol2 has no conversion for ("unknown"
        // kind), pointers/objects that aren't registered usertypes, mutable
        // references to NON-class types (the converted argument is a temporary
        // — a std::string& out-parameter can't work), and copies of
        // non-copyable classes (by-value parameters and returns).

        // Is `name` (unqualified) one of the bound classes? A raw pointer or a
        // by-value object is only marshalable when its type is itself
        // registered as a sol2 usertype.
        inline bool lx_is_bound(const std::string &name, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (k.name == name) {
                    return true;
                }
            }
            return false;
        }

        inline bool lx_marshalable(const GenType &t, const GenContext &c) {
            // Bare raw pointer to a bound class: sol2 treats T* as a non-owning
            // handle to the registered usertype.
            if (t.is_pointer) {
                return lx_is_bound(t.object, c);
            }
            if (t.kind == "unknown") {
                return false; // callbacks are allowed per-parameter, see lx_param_ok
            }
            if (t.kind == "object") {
                // std::array rides sol2's fixed-size container support.
                if (qualify_std(t.spelling).rfind("std::array<", 0) == 0) {
                    return true;
                }
                return lx_is_bound(t.object, c);
            }
            if (t.kind == "vector") {
                if (t.element.empty()) {
                    return true;
                }
                // A vector of raw pointers stays out (mirrors the other
                // expanded backends — ownership through a container of
                // pointers is a trap in a GC'd host language).
                if (t.element.front().is_pointer) {
                    return false;
                }
                return lx_marshalable(t.element.front(), c);
            }
            return true; // number / boolean / string / enum / void
        }

        // Can a value of this type cross INSIDE a Lua-function callback, i.e.
        // through sol2's native sol::function → std::function conversion? Each
        // signature type must itself be sol2-convertible; raw pointers and
        // nested callbacks stay out (conservative, mirrors node/wasm).
        inline bool lx_callback_convertible(const GenType &t, const GenContext &c) {
            if (!t.is_callback || t.callback_sig.empty()) {
                return false;
            }
            auto convertible = [&](const GenType &s) {
                return !s.is_pointer && !s.is_callback && lx_marshalable(s, c);
            };
            const GenType &ret = t.callback_sig.front();
            if (!(ret.kind == "void" || convertible(ret))) {
                return false;
            }
            for (std::size_t i = 1; i < t.callback_sig.size(); ++i) {
                if (!convertible(t.callback_sig[i])) {
                    return false;
                }
            }
            return true;
        }

        // A parameter is bindable when sol2 marshals it directly, OR it is a
        // std::function sol2 can build from a Lua function.
        inline bool lx_param_ok(const GenType &t, const GenContext &c) {
            return lx_marshalable(t, c) || (t.is_callback && lx_callback_convertible(t, c));
        }

        // Copies happen when a Lua table converts to a std::vector (parameters,
        // field setters) — so those spots need copyable elements.
        inline bool lx_copyable(const GenType &t) {
            if (t.kind == "object") {
                return t.copy_constructible && t.copy_assignable;
            }
            if (t.kind == "vector") {
                return t.element.empty() || lx_copyable(t.element.front());
            }
            return true;
        }

        inline bool lx_method_ok(const GenMethod &m, const GenContext &c) {
            // Overload set: the bare `&T::name` the emitter spells would be
            // ambiguous — skip the whole set.
            if (m.is_overloaded) {
                return false;
            }
            if (m.ret.kind != "void" && !lx_marshalable(m.ret, c)) {
                return false;
            }
            // A by-VALUE class return copies into the userdata; an lvalue-ref
            // return is pushed by reference and never copies (unlike pybind).
            if (m.ret.kind == "object" && !m.ret_is_ref && !m.ret.copy_constructible) {
                return false;
            }
            if (m.ret.kind == "vector" && !m.ret_is_ref && !lx_copyable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!lx_param_ok(p.type, c)) {
                    return false;
                }
                // A by-value class parameter copy-constructs; by-ref binds the
                // userdata in place (mutable T& of a bound class is fine).
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false;
                }
                if (p.type.kind == "vector" && !lx_copyable(p.type)) {
                    return false; // table → vector conversion copies elements
                }
                // Mutable ref to a NON-class type (std::string&, index_t&): an
                // out-parameter — sol2's converted argument is a temporary, so
                // the mutation would be lost (or fail to compile).
                if (p.type.kind != "object" && p.is_mutable_ref) {
                    return false;
                }
            }
            return true;
        }

        // Can this field be exposed? Member-object pointers of a registered
        // class push by reference (no copy needed to READ), but sol2's
        // generated setter copy-assigns — a non-copy-assignable field is
        // downgraded to read-only (see lua_field) rather than skipped.
        inline bool lx_field_ok(const GenField &f, const GenContext &c) {
            if (!lx_marshalable(f.type, c)) {
                return false;
            }
            if (f.type.kind == "vector" && !f.is_readonly && !lx_copyable(f.type)) {
                return false; // writable vector field: table assignment copies
            }
            return true;
        }

        // Does the emitted binding need sol2's writable-field setter, or must
        // the field be wrapped read-only? (manifest readonly, or a class /
        // vector-of-class the setter could not copy-assign.)
        inline bool lx_field_readonly(const GenField &f) {
            if (f.is_readonly) {
                return true;
            }
            if (f.type.kind == "object") {
                return !(f.type.copy_constructible && f.type.copy_assignable);
            }
            return false;
        }

        // A compilable C++ spelling for an IR type — the cvref-stripped value
        // form, used in the table-accepting lambda overloads (exact spellings
        // via GenMethod::param_cpp are preferred where available; extension
        // methods and free functions don't carry them).
        inline std::string lua_cpp_type(const GenType &t) {
            if (t.kind == "vector") {
                return "std::vector<" +
                       (t.element.empty() ? std::string("double")
                                          : lua_cpp_type(t.element.front())) +
                       ">";
            }
            if (t.kind == "object" || t.kind == "enum") {
                return t.object;
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "number") {
                return t.spelling.empty() ? "double" : t.spelling;
            }
            return qualify_std(t.spelling);
        }

        inline bool lx_has_vector_param(const std::vector<GenParam> &params) {
            for (const auto &p : params) {
                if (p.type.kind == "vector") {
                    return true;
                }
            }
            return false;
        }

        // The (lambda parameter decls, forwarded call args) of a table-friendly
        // overload. sol2 does NOT convert a Lua table to a std::vector
        // parameter on its own (containers are userdata), so any signature
        // naming a vector gets a second overload whose vector parameters are
        // sol::nested<...> — accepting a plain (possibly nested) Lua table —
        // while the primary member-pointer overload keeps accepting container
        // userdata. Other parameters use generic value/reference spellings.
        struct LuaTableParams {
            std::string decls; // e.g. "sol::nested<std::vector<double>> arg0, bool arg1"
            std::string args;  // e.g. "arg0.value(), arg1"
        };
        inline LuaTableParams lua_table_params(const std::vector<GenParam> &params) {
            LuaTableParams a;
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                if (j) {
                    a.decls += ", ";
                    a.args += ", ";
                }
                const GenType &t = params[j].type;
                if (t.kind == "vector") {
                    a.decls += "sol::nested<" + lua_cpp_type(t) + "> " + an;
                    a.args += an + ".value()";
                } else if (t.is_pointer) {
                    a.decls += t.object + " *" + an;
                    a.args += an;
                } else if (t.kind == "object") {
                    a.decls += lua_cpp_type(t) + " &" + an; // bound userdata, by ref
                    a.args += an;
                } else {
                    a.decls += lua_cpp_type(t) + " " + an;
                    a.args += an;
                }
            }
            return a;
        }

        // --- Foreign sequences (rosetta::is_sequence) --------------------------
        // A method touching a trait-registered sequence binds through a lambda
        // whose sequence parameters are sol::nested<std::vector<element>> —
        // plain Lua tables — copied into the foreign container before the call;
        // a returned sequence is flattened to a std::vector (container
        // userdata, like every other bound vector return). Mutable `Seq&`
        // binds input-only, and an overload set whose surviving IR entry is
        // the sequence one binds too (the adapter calls by NAME).

        inline bool lx_seq_rest_ok(const GenMethod &m, const GenContext &c) {
            if (!m.ret.is_sequence) {
                if (m.ret.kind != "void" && !lx_marshalable(m.ret, c)) {
                    return false;
                }
                if (m.ret.kind == "object" && !m.ret_is_ref && !m.ret.copy_constructible) {
                    return false;
                }
                if (m.ret.kind == "vector" && !m.ret_is_ref && !lx_copyable(m.ret)) {
                    return false;
                }
            }
            for (const auto &p : m.params) {
                if (p.type.is_sequence) {
                    continue;
                }
                if (!lx_param_ok(p.type, c)) {
                    return false;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false;
                }
                if (p.type.kind == "vector" && !lx_copyable(p.type)) {
                    return false;
                }
                if (p.type.kind != "object" && p.is_mutable_ref) {
                    return false;
                }
            }
            return true;
        }
        inline bool lx_seq_eligible(const GenMethod &m, const GenContext &c) {
            return seq_adaptable(m) && lx_seq_rest_ok(m, c);
        }

        // (decls, pre-call statements, call args) — sequence params arrive as
        // sol::nested tables; the rest mirrors lua_table_params.
        struct LxSeqSig {
            std::string decls;
            std::string pre;
            std::string args;
        };
        // `tables`: vector-ish parameters arrive as sol::nested (plain Lua
        // tables). Otherwise they arrive as std::vector container userdata —
        // what a bound sequence RETURN pushes — so every sequence method is
        // emitted as a sol::overload of both forms, mirroring the ordinary
        // vector-parameter convention (primary + table overload).
        inline LxSeqSig lx_seq_sig(const std::vector<GenParam> &params, bool tables) {
            LxSeqSig o;
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                if (j) {
                    o.decls += ", ";
                    o.args += ", ";
                }
                const GenType &t = params[j].type;
                if (t.is_sequence) {
                    const std::string sn = "seq" + std::to_string(j);
                    if (tables) {
                        o.decls += "sol::nested<" + seq_boundary_cpp(t) + "> " + an;
                        o.pre += seq_decl_stmts(t, an + ".value()", sn, "        ");
                    } else {
                        o.decls += "const " + seq_boundary_cpp(t) + " &" + an;
                        o.pre += seq_decl_stmts(t, an, sn, "        ");
                    }
                    o.args += sn;
                } else if (t.kind == "vector") {
                    if (tables) {
                        o.decls += "sol::nested<" + lua_cpp_type(t) + "> " + an;
                        o.args += an + ".value()";
                    } else {
                        o.decls += "const " + lua_cpp_type(t) + " &" + an;
                        o.args += an;
                    }
                } else if (t.is_pointer) {
                    o.decls += t.object + " *" + an;
                    o.args += an;
                } else if (t.kind == "object") {
                    o.decls += lua_cpp_type(t) + " &" + an; // bound userdata, by ref
                    o.args += an;
                } else {
                    o.decls += lua_cpp_type(t) + " " + an;
                    o.args += an;
                }
            }
            return o;
        }

        // Does the parameter list name a vector-ish type at all? (No ⇒ one
        // lambda suffices; the overload pair is only about tables-vs-userdata
        // for parameters.)
        inline bool lx_seq_has_vectorish_param(const std::vector<GenParam> &params) {
            for (const auto &p : params) {
                if (p.type.is_sequence || p.type.kind == "vector") {
                    return true;
                }
            }
            return false;
        }

        inline std::string lx_seq_body(const GenMethod &m, const LxSeqSig &sig,
                                       const std::string &call) {
            std::string body = sig.pre;
            if (m.ret.is_sequence) {
                body += "        auto &&r = " + call + ";\n";
                body += "        return " + seq_from_expr(m.ret, "r") + ";\n";
            } else if (m.ret.kind == "void") {
                body += "        " + call + ";\n";
            } else {
                body += "        return " + call + ";\n";
            }
            return body;
        }

        // One lambda text for the given parameter form (userdata / tables).
        inline std::string lx_seq_lambda(const GenClass &k, const GenMethod &m, bool tables) {
            const LxSeqSig sig = lx_seq_sig(m.params, tables);
            std::string    decls, call;
            if (m.is_extension) {
                decls = k.name + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = m.ext_qualified + "(self" + (sig.args.empty() ? "" : ", " + sig.args) +
                       ")";
            } else if (m.is_static) {
                decls = sig.decls;
                call  = k.name + "::" + m.name + "(" + sig.args + ")";
            } else {
                decls = k.name + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = "self." + m.name + "(" + sig.args + ")";
            }
            return "[](" + decls + ") {\n" + lx_seq_body(m, sig, call) + "    }";
        }

        inline std::string lx_seq_method(const GenClass &k, const GenMethod &m) {
            if (!lx_seq_has_vectorish_param(m.params)) {
                return "    c[\"" + m.name + "\"] = " + lx_seq_lambda(k, m, true) + ";\n";
            }
            // Container userdata (what a bound sequence return pushes) AND
            // plain Lua tables both dispatch.
            return "    c[\"" + m.name + "\"] = sol::overload(\n        " +
                   lx_seq_lambda(k, m, false) + ",\n        " + lx_seq_lambda(k, m, true) +
                   ");\n";
        }

        // One enum: m.new_enum<E>("E", {{"A", E::A}, ...}); (read-only table).
        inline std::string lua_enum(const GenEnum &e) {
            std::string s = "    m.new_enum<" + e.name + ">(\"" + e.name + "\", {";
            for (std::size_t i = 0; i < e.values.size(); ++i) {
                s += (i ? "," : "");
                s += "\n        {\"" + e.values[i].name + "\", " + e.name +
                     "::" + e.values[i].name + "}";
            }
            s += "});\n";
            return s;
        }

        // One field: readonly (or non-copy-assignable) -> sol::readonly;
        // arithmetic + range -> validating sol::property; otherwise the bare
        // member pointer (sol2 generates both accessors from it).
        inline std::string lua_field(const GenClass &k, const GenField &f) {
            const std::string self = k.name;
            const std::string mp   = "&" + self + "::" + f.name;
            if (lx_field_readonly(f)) {
                return "    c[\"" + f.name + "\"] = sol::readonly(" + mp + ");\n";
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string ty = f.type.spelling;
                const std::string lo = num_str(f.range.min);
                const std::string hi = num_str(f.range.max);
                std::string s;
                s += "    c[\"" + f.name + "\"] = sol::property(\n";
                s += "        [](const " + self + " &s) { return s." + f.name + "; },\n";
                s += "        [](" + self + " &s, " + ty + " v) {\n";
                s += "            if (v < " + lo + " || v > " + hi + ")\n";
                s += "                throw std::runtime_error(\"" + f.name + " out of range [" +
                     lo + ", " + hi + "]\");\n";
                s += "            s." + f.name + " = v;\n";
                s += "        });\n";
                return s;
            }
            // Writable vector field: the member-pointer setter would demand
            // container userdata, so emit a property whose setter branches —
            // another field's userdata assigns directly, a plain Lua table
            // converts through sol::nested. The getter hands out a reference,
            // so in-place container ops (m.tags:add(x), m.tags[1] = y) still
            // mutate the real member.
            if (f.type.kind == "vector") {
                const std::string vt = lua_cpp_type(f.type);
                std::string s;
                s += "    c[\"" + f.name + "\"] = sol::property(\n";
                s += "        [](" + self + " &s) -> " + vt + " & { return s." + f.name + "; },\n";
                s += "        [](" + self + " &s, const sol::object &v) {\n";
                s += "            if (v.is<" + vt + ">()) { s." + f.name + " = v.as<" + vt +
                     ">(); }\n";
                // (object::as<nested<V>> yields the unwrapped V, not nested<V>.)
                s += "            else { s." + f.name + " = v.as<sol::nested<" + vt +
                     ">>(); }\n";
                s += "        });\n";
                return s;
            }
            return "    c[\"" + f.name + "\"] = " + mp + ";\n";
        }

        // One method. The member-function pointer is disambiguated with an
        // explicit cast to the exact signature — a plain `&T::m` is ambiguous
        // for an overloaded method. An extension method binds its free
        // function instead: sol2 treats a non-member whose first parameter is
        // the class (by ref) as an instance method. A static method assigned
        // through the usertype binds as a plain function (called T.m(...)).
        // A signature naming a vector gets a second, table-accepting overload
        // (see lua_table_params); sol2 dispatches to whichever matches.
        inline std::string lua_method(const GenClass &k, const GenMethod &m) {
            // The primary binding: exact-signature pointer to the real function.
            std::string primary;
            if (m.is_extension) {
                primary = "&" + m.ext_qualified;
            } else {
                std::string args;
                for (std::size_t j = 0; j < m.param_cpp.size(); ++j) {
                    args += (j ? ", " : "") + qualify_std(m.param_cpp[j]);
                }
                std::string quals;
                if (m.is_const) {
                    quals += " const";
                }
                if (m.is_noexcept) {
                    quals += " noexcept";
                }
                const std::string ret = qualify_std(m.ret_cpp);
                const std::string fp =
                    m.is_static ? (ret + " (*)(" + args + ")" + quals)
                                : (ret + " (" + k.name + "::*)(" + args + ")" + quals);
                primary = "static_cast<" + fp + ">(&" + k.name + "::" + m.name + ")";
            }
            if (!lx_has_vector_param(m.params)) {
                return "    c[\"" + m.name + "\"] = " + primary + ";\n";
            }
            const LuaTableParams tp = lua_table_params(m.params);
            std::string          decls, call;
            if (m.is_extension) {
                decls = k.name + " &self" + (tp.decls.empty() ? "" : ", " + tp.decls);
                call  = m.ext_qualified + "(self" + (tp.args.empty() ? "" : ", " + tp.args) + ")";
            } else if (m.is_static) {
                decls = tp.decls;
                call  = k.name + "::" + m.name + "(" + tp.args + ")";
            } else {
                decls = k.name + " &self" + (tp.decls.empty() ? "" : ", " + tp.decls);
                call  = "self." + m.name + "(" + tp.args + ")";
            }
            return "    c[\"" + m.name + "\"] = sol::overload(\n        " + primary +
                   ",\n        [](" + decls + ") { return " + call + "; });\n";
        }

        // The constructor clause of new_usertype: sol::constructors<T(...), ...>
        // over every marshalable constructor (sol2 does full runtime overload
        // resolution, so unlike embind all arities AND same-arity overloads
        // coexist), plus a synthetic T() when the type is default-constructible
        // but no zero-arg ctor was enumerated. An abstract class — or one with
        // no usable constructor — gets sol::no_constructor.
        //
        // When a constructor names a std::vector — and the class looks
        // value-ish (copy_or_move_assignable, since a factory returns T by
        // value) — the whole clause switches to sol::factories: one lambda per
        // constructor spelled with the exact parameter types, plus a
        // table-accepting variant (sol::nested) for each vector-taking one, so
        // `Surface.new({0,0,0,...}, {0,1,2})` works with plain Lua tables.
        inline std::string lua_ctor_clause(const GenClass &k, const GenContext &c) {
            std::vector<std::size_t> usable; // indices into k.ctors
            bool                     saw_default = false;
            bool                     any_vector  = false;
            for (std::size_t i = 0; !k.is_abstract && i < k.ctor_param_cpp.size(); ++i) {
                bool ok = true;
                for (const auto &p : k.ctors[i]) {
                    ok = ok && lx_param_ok(p.type, c) &&
                         (p.type.kind != "object" || p.is_ref || p.type.copy_constructible) &&
                         (p.type.kind != "vector" || lx_copyable(p.type)) &&
                         (p.type.kind == "object" || !p.is_mutable_ref);
                }
                if (!ok) {
                    continue;
                }
                usable.push_back(i);
                saw_default = saw_default || k.ctor_param_cpp[i].empty();
                any_vector  = any_vector || lx_has_vector_param(k.ctors[i]);
            }
            const bool synth_default = !saw_default && !k.is_abstract && k.is_default_constructible;
            if (usable.empty() && !synth_default) {
                return "sol::no_constructor";
            }

            if (any_vector && k.copy_or_move_assignable) {
                std::vector<std::string> lambdas;
                if (synth_default) {
                    lambdas.push_back("[]() { return " + k.name + "(); }");
                }
                for (std::size_t i : usable) {
                    const auto &params = k.ctor_param_cpp[i];
                    std::string decls, args;
                    for (std::size_t j = 0; j < params.size(); ++j) {
                        const std::string an = "arg" + std::to_string(j);
                        decls += (j ? ", " : "") + qualify_std(params[j]) + " " + an;
                        args += (j ? ", " : "") + an;
                    }
                    lambdas.push_back("[](" + decls + ") { return " + k.name + "(" + args +
                                      "); }");
                    if (lx_has_vector_param(k.ctors[i])) {
                        const LuaTableParams tp = lua_table_params(k.ctors[i]);
                        lambdas.push_back("[](" + tp.decls + ") { return " + k.name + "(" +
                                          tp.args + "); }");
                    }
                }
                std::string s = "sol::factories(";
                for (std::size_t i = 0; i < lambdas.size(); ++i) {
                    s += (i ? "," : "") + std::string("\n            ") + lambdas[i];
                }
                return s + ")";
            }

            std::vector<std::string> sigs;
            if (synth_default) {
                sigs.push_back(k.name + "()");
            }
            for (std::size_t i : usable) {
                const auto &params = k.ctor_param_cpp[i];
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    args += (j ? ", " : "") + qualify_std(params[j]);
                }
                sigs.push_back(k.name + "(" + args + ")");
            }
            std::string s = "sol::constructors<";
            for (std::size_t i = 0; i < sigs.size(); ++i) {
                s += (i ? ", " : "") + sigs[i];
            }
            return s + ">()";
        }

        // The bound base classes, as a sol::base_classes clause. sol2 supports
        // multiple inheritance, so — unlike embind — every bound base is
        // listed, and a derived userdata is accepted wherever a base is
        // expected (methods included, via sol2's base lookup).
        inline std::string lua_bases_clause(const GenClass &k, const GenContext &c) {
            auto qualified = [](const GenClass &g) {
                return g.name_space.empty() ? g.name : g.name_space + "::" + g.name;
            };
            std::string bases;
            for (const auto &b : k.bases) {
                for (const auto &g : c.classes) {
                    if (qualified(g) == b) {
                        bases += (bases.empty() ? "" : ", ") + b;
                        break;
                    }
                }
            }
            if (bases.empty()) {
                return {};
            }
            return ",\n        sol::base_classes, sol::bases<" + bases + ">()";
        }

        // One class block: new_usertype + one assignment per member, inside an
        // open scope so the local `c` never leaks.
        inline std::string lua_class(const GenClass &k, const GenContext &c) {
            std::string s = "    {\n";
            s += "    sol::usertype<" + k.name + "> c = m.new_usertype<" + k.name + ">(\"" +
                 k.name + "\",\n        " + lua_ctor_clause(k, c) + lua_bases_clause(k, c) +
                 ");\n";
            for (const auto &f : k.fields) {
                if (f.type.is_sequence) {
                    // Foreign sequence field: property copying through the
                    // boundary vector (get: container userdata; set: another
                    // container or a plain table via sol::nested).
                    if (seq_ok(f.type)) {
                        const std::string vt = seq_boundary_cpp(f.type);
                        s += "    c[\"" + f.name + "\"] = sol::property(\n";
                        s += "        [](const " + k.name + " &s) { return " +
                             seq_from_expr(f.type, "s." + f.name) + "; }";
                        if (!f.is_readonly) {
                            s += ",\n        [](" + k.name + " &s, const sol::object &o) {\n";
                            s += "            " + vt + " v = o.is<" + vt + ">() ? o.as<" + vt +
                                 ">() : o.as<sol::nested<" + vt + ">>();\n";
                            s += "            s." + f.name + ".resize(v.size());\n";
                            s += "            std::copy(v.begin(), v.end(), s." + f.name +
                                 ".begin());\n";
                            s += "        }";
                        }
                        s += ");\n";
                    }
                    continue;
                }
                if (!lx_field_ok(f, c)) {
                    continue; // type sol2 can't marshal — see lx_field_ok
                }
                s += lua_field(k, f);
            }
            for (const auto &m : k.methods) {
                if (seq_touches(m)) {
                    // Foreign sequence in the signature: table-accepting
                    // adapter or nothing (sol2 has no usertype for the
                    // foreign container).
                    if (lx_seq_eligible(m, c)) {
                        s += lx_seq_method(k, m);
                    }
                    continue;
                }
                if (!lx_method_ok(m, c)) {
                    continue; // signature the emitted sol2 line could not compile
                }
                s += lua_method(k, m);
            }
            s += "    }\n";
            return s;
        }

        inline std::string lua_expanded_source(const GenContext &c) {
            std::string body;
            for (const auto &e : c.enums) {
                body += lua_enum(e);
            }
            for (const auto &k : c.classes) {
                body += lua_class(k, c);
            }
            for (const auto &f : c.functions) {
                GenMethod probe; // free functions go through the same gates
                probe.ret    = f.ret;
                probe.params = f.params;
                if (seq_touches(probe)) {
                    if (lx_seq_eligible(probe, c)) {
                        auto lambda = [&](bool tables) {
                            const LxSeqSig    sig  = lx_seq_sig(f.params, tables);
                            const std::string call = f.qualified + "(" + sig.args + ")";
                            return "[](" + sig.decls + ") {\n" +
                                   lx_seq_body(probe, sig, call) + "    }";
                        };
                        if (lx_seq_has_vectorish_param(f.params)) {
                            body += "    m.set_function(\"" + f.name +
                                    "\", sol::overload(\n        " + lambda(false) +
                                    ",\n        " + lambda(true) + "));\n";
                        } else {
                            body += "    m.set_function(\"" + f.name + "\", " + lambda(true) +
                                    ");\n";
                        }
                    }
                    continue;
                }
                if (!lx_method_ok(probe, c)) {
                    continue;
                }
                if (lx_has_vector_param(f.params)) {
                    // Same table-accepting second overload as methods get.
                    const LuaTableParams tp = lua_table_params(f.params);
                    body += "    m.set_function(\"" + f.name + "\", sol::overload(\n        &" +
                            f.qualified + ",\n        [](" + tp.decls + ") { return " +
                            f.qualified + "(" + tp.args + "); }));\n";
                } else {
                    body += "    m.set_function(\"" + f.name + "\", &" + f.qualified + ");\n";
                }
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += "#define SOL_ALL_SAFETIES_ON 1\n"
                   "#include <sol/sol.hpp>\n"
                   "#include <algorithm>\n"
                   "#include <functional>\n"
                   "#include <stdexcept>\n"
                   "#include <string>\n"
                   "#include <vector>\n";
            // sol2-only: just the user's (stock) headers below.
            auto add = [&](const std::string &h) { append_include(out, h); };
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += "\n// The module table, filled once when the library is require()d.\n";
            out += "static sol::table rosetta_open_module(sol::this_state ts) {\n";
            out += "    sol::state_view lua(ts);\n";
            out += "    sol::table      m = lua.create_table();\n";
            out += body;
            out += "    return m;\n";
            out += "}\n\n";
            out += "extern \"C\"\n";
            out += "#if defined(_WIN32)\n__declspec(dllexport)\n";
            out += "#else\n__attribute__((visibility(\"default\")))\n#endif\n";
            out += "int luaopen_" + c.lib + "(lua_State *L) {\n";
            out += "    // Refuse a foreign interpreter with a clean error instead of a\n";
            out += "    // segfault: on macOS the module resolves the Lua C API from the\n";
            out += "    // HOST at load time (-undefined dynamic_lookup), so loading this\n";
            out += "    // module into an interpreter of another Lua version (e.g. a 5.4\n";
            out += "    // build inside the 5.5 CLI) corrupts the stack. luaL_checkversion\n";
            out += "    // compares the compiled-against core/number-size with the running\n";
            out += "    // one through a stable ABI and raises \"version mismatch\".\n";
            out += "    luaL_checkversion(L);\n";
            out += "    return sol::stack::call_lua(L, 1, rosetta_open_module);\n";
            out += "}\n";
            return out;
        }

        inline std::string LuaExpandedBackend::render(const GenContext &c) const {
            return lua_expanded_source(c);
        }

        inline void LuaExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "lua-expanded";
            write_file(dir / "auto_sol.cpp", lua_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(LUAX_CMAKE, c));
            write_file(dir / "README.md",
                       readme("lua-expanded", c,
                              subst(LUAX_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
