// Copyright (c) fmaerten@gmail.com
// License: MIT

// MCP backend, emitter. Included by inline/generate.hxx after backends/dynamic.h.
//
// Output shape, per target:
//
//   mcp/auto_dynamic.h    — declares register_all()       (same as dynamic/)
//   mcp/auto_dynamic.cpp  — the metadata tables and thunks (same as dynamic/)
//   mcp/mcp_server.cpp    — main(): register_all(), enable_lua() / enable_python()
//                           when built with them (ROSETTA_MCP_LUA / _PYTHON),
//                           then serve MCP on stdio
//   mcp/CMakeLists.txt    — stock C++20, nlohmann/json, one executable <lib>
//   mcp/README.md         — build, and how to register the server with a client

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        // -------- templates ------------------------------------------------

        constexpr std::string_view MCP_CMAKE =
            R"CMK(# Generated by rosetta::generate (MCP server) — do not edit by hand.
# Stock C++20: NO reflection. The server is <rosetta/runtime/mcp.h> over the
# dynamic object model's metadata tables.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_mcp CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

set(ROSETTA_INCLUDE "{{ROSETTA_INCLUDE}}")

# nlohmann/json: use an installed one if there is one, else fetch it.
find_package(nlohmann_json 3.11 QUIET)
if(NOT nlohmann_json_FOUND)
    include(FetchContent)
    FetchContent_Declare(json
        GIT_REPOSITORY https://github.com/nlohmann/json.git
        GIT_TAG        v3.11.3)
    FetchContent_MakeAvailable(json)
endif()

add_executable({{LIB}} mcp_server.cpp auto_dynamic.cpp)
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    ${ROSETTA_INCLUDE}
    ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries({{LIB}} PRIVATE nlohmann_json::nlohmann_json)
set(ROSETTA_BINDING_TARGET {{LIB}})

# run_script: the agent sends a Lua script instead of many tool calls. Needs
# Lua 5.3+ (5.4 preferred); without it the server simply lacks that tool.
# Override with -DLUA_INCLUDE_DIR / -DLUA_LIBRARIES, or -DROSETTA_MCP_LUA=OFF.
option(ROSETTA_MCP_LUA "Offer the run_script tool (embeds Lua)" ON)
if(ROSETTA_MCP_LUA)
    if(APPLE AND EXISTS /opt/homebrew)
        list(APPEND CMAKE_PREFIX_PATH /opt/homebrew)
    endif()
    # Test LUA_LIBRARIES, not LUA_INCLUDE_DIR: FindLua caches the include
    # dir but sets LUA_LIBRARIES as a plain variable, so a re-configure would
    # otherwise skip the search and lose the library.
    if(NOT LUA_LIBRARIES)
        find_package(Lua 5.4 EXACT QUIET)
    endif()
    if(NOT LUA_LIBRARIES)
        find_path(LUA_INCLUDE_DIR lua.h
            PATH_SUFFIXES lua5.4 lua-5.4 lua
            PATHS /opt/homebrew/opt/lua@5.4/include /usr/local/opt/lua@5.4/include
                  /opt/homebrew/include /usr/local/include /usr/include
            NO_DEFAULT_PATH)
        find_library(LUA_LIBRARIES NAMES lua5.4 lua-5.4 lua
            PATHS /opt/homebrew/opt/lua@5.4/lib /usr/local/opt/lua@5.4/lib
                  /opt/homebrew/lib /usr/local/lib /usr/lib
            NO_DEFAULT_PATH)
    endif()
    if(NOT LUA_LIBRARIES)
        find_package(Lua 5.3 QUIET)
    endif()
    if(LUA_INCLUDE_DIR AND LUA_LIBRARIES)
        message(STATUS "run_script enabled — Lua headers: ${LUA_INCLUDE_DIR}")
        target_include_directories({{LIB}} PRIVATE ${LUA_INCLUDE_DIR})
        target_link_libraries({{LIB}} PRIVATE ${LUA_LIBRARIES})
        target_compile_definitions({{LIB}} PRIVATE ROSETTA_MCP_LUA=1)
    else()
        message(WARNING "Lua 5.3+ not found — the server is built WITHOUT run_script. "
                        "Pass -DLUA_INCLUDE_DIR=... -DLUA_LIBRARIES=..., or -DROSETTA_MCP_LUA=OFF "
                        "to silence this.")
    endif()
endif()

# run_python: the same idea in Python (numpy and friends available to the
# agent). OFF by default because CPython cannot be sandboxed — the agent's
# scripts run with this process's permissions. Needs Python 3.10+ dev files
# and pybind11 (installed, or fetched).
option(ROSETTA_MCP_PYTHON "Offer the run_python tool (embeds CPython, NOT sandboxed)" OFF)
if(ROSETTA_MCP_PYTHON)
    find_package(Python 3.10 REQUIRED COMPONENTS Interpreter Development.Embed)
    execute_process(COMMAND "${Python_EXECUTABLE}" -c "import pybind11; print(pybind11.get_cmake_dir())"
        OUTPUT_VARIABLE _rosetta_pybind11_dir OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    find_package(pybind11 CONFIG QUIET HINTS "${_rosetta_pybind11_dir}")
    if(NOT pybind11_FOUND)
        include(FetchContent)
        FetchContent_Declare(pybind11
            GIT_REPOSITORY https://github.com/pybind/pybind11.git
            GIT_TAG        v3.0.1)
        FetchContent_MakeAvailable(pybind11)
    endif()
    target_link_libraries({{LIB}} PRIVATE pybind11::embed)
    target_compile_definitions({{LIB}} PRIVATE ROSETTA_MCP_PYTHON=1)
    message(STATUS "run_python enabled — ${Python_EXECUTABLE} (not sandboxed)")
endif()
{{USER_DEFS_BLOCK}}{{USER_LIB_BLOCK}}{{OUT_DIR_BLOCK}}
)CMK";

        constexpr std::string_view MCP_MAIN =
            R"CPP(// Generated by rosetta::generate (MCP server) — do not edit by hand.
//
// An MCP server over stdio. It names no bound type: the tools it offers are
// rosetta's generic ones (list_classes, describe_class, create_object,
// call_method, ...), answered by querying the metadata registered below.

#include <rosetta/runtime/mcp.h>
#include "auto_dynamic.h"

#if ROSETTA_MCP_LUA
#include <rosetta/runtime/mcp_lua.h> // the run_script tool
#endif
#if ROSETTA_MCP_PYTHON
#include <rosetta/runtime/mcp_python.h> // the run_python tool
#endif

int main() {
    {{MOD}}::register_all();

    rosetta::mcp::Options opts;
    opts.name = "{{LIB}}";
    rosetta::mcp::Server server(opts);
#if ROSETTA_MCP_LUA
    rosetta::mcp::enable_lua(server);
#endif
#if ROSETTA_MCP_PYTHON
    rosetta::mcp::enable_python(server);
#endif
    return server.serve_stdio();
}
)CPP";

        constexpr std::string_view MCP_README_BUILD = R"MD(## Build

Prerequisites: a stock C++20 compiler and CMake >= 3.18. nlohmann/json is used
if installed, otherwise fetched on the first configure. Lua 5.3+ (5.4
preferred) is optional: when CMake finds it, the server also offers
`run_script`; `-DROSETTA_MCP_LUA=OFF` builds without it. `-DROSETTA_MCP_PYTHON=ON`
adds `run_python` (embedded CPython via pybind11; not sandboxed, so off by
default).

```sh
cmake -S . -B build
cmake --build build
```

## Connect an agent

The server speaks MCP over stdio. Register it with Claude Code:

```sh
claude mcp add {{LIB}} -- "$PWD/build/{{LIB}}"
```

or in any client's JSON configuration (`.mcp.json`, Claude Desktop, ...):

```json
{ "mcpServers": { "{{LIB}}": { "command": "/absolute/path/to/build/{{LIB}}" } } }
```

The agent gets a fixed set of tools — `list_classes`, `describe_class`,
`create_object`, `call_method`, `inspect_object`, `set_fields`,
`list_objects`, `release_object` (and `call_function` when free functions are
bound), plus `run_script` / `run_python` when built with Lua / Python — and discovers the classes below
through them. `run_script` runs a sandboxed Lua script next to the live
objects, so a loop ("relax until the worst triangle passes 0.1") is one tool
call instead of dozens. Objects live in a handle
table (`Mesh#1`) for the life of the server process.

Try it by hand:

```sh
printf '%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"list_classes","arguments":{}}}' \
  | ./build/{{LIB}}
```
)MD";

        // -------- Backend ---------------------------------------------------

        inline void Mcp::emit(const GenContext &c) const {
            auto              dir = c.out_dir / "mcp";
            const std::string mod = dyn_ident(c.lib);
            write_file(dir / "auto_dynamic.h", dynamic_header(c));
            write_file(dir / "auto_dynamic.cpp", dynamic_source(c));
            write_file(dir / "mcp_server.cpp", subst(MCP_MAIN, {{"LIB", c.lib}, {"MOD", mod}}));
            write_file(dir / "CMakeLists.txt", render_meta(MCP_CMAKE, c));
            write_file(dir / "README.md",
                       readme("mcp", c, subst(MCP_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace backend
} // namespace rosetta
