// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Nanobind generation backend. Included by inline/generate.hxx, which provides
// the shared render helpers (subst / render_meta / includes_of / readme).

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view NB_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/nanobind_visitor.h>

NB_MODULE({{LIB}}, m) {
    m.doc() = "Auto-generated nanobind bindings for {{LIB}}.";
{{BINDINGS}}}
)CPP";

        // Like the pybind CMake: the thin binding re-runs reflection, so it
        // builds with clang-p2996 (C++26 + the reflection flags). nanobind is
        // discovered through its installed CMake config; nanobind_add_module
        // compiles the nanobind support library into the target.
        constexpr std::string_view NB_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

execute_process(
    COMMAND {{PYTHON_CMD}} -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(Python {{PYTHON_MIN}} COMPONENTS Interpreter Development.Module REQUIRED)

# Prefer the nanobind CMake package shipped with the pip/`nanobind` module,
# fall back to fetching a pinned release.
if(NOT nanobind_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -c "import nanobind; print(nanobind.cmake_dir())"
        OUTPUT_VARIABLE nanobind_DIR
        RESULT_VARIABLE _nanobind_probe
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _nanobind_probe EQUAL 0)
        set(nanobind_DIR "")
    endif()
endif()
if(nanobind_DIR)
    find_package(nanobind CONFIG REQUIRED)
else()
    include(FetchContent)
    FetchContent_Declare(
        nanobind
        GIT_REPOSITORY https://github.com/wjakob/nanobind.git
        GIT_TAG v2.13.0)
    FetchContent_MakeAvailable(nanobind)
endif()

nanobind_add_module({{LIB}} NB_STATIC auto_nanobind.cpp)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})
{{USER_LIB_BLOCK}}
target_compile_options({{LIB}} PRIVATE
    {{REFLECTION_FLAGS}})

target_link_options({{LIB}} PRIVATE
    {{STDLIB_LINK}})

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
{{OUT_DIR_BLOCK}}
)CMK";

        // Build/Use section for the generated README — kept next to NB_CMAKE so
        // the doc can't drift from the template it describes: nanobind comes
        // from pip when installed (`nanobind.cmake_dir()` locates it) and is
        // otherwise fetched at configure time, the compile needs the
        // clang-p2996 toolchain ({{REFLECTION_FLAGS}}/{{STDLIB_LINK}}), and the
        // POST_BUILD copy makes the module importable from this dir.
        constexpr std::string_view NB_README_BUILD = R"MD(## Build

Prerequisite: the clang-p2996 C++26 reflection toolchain — pass
`-DCLANG_P2996_ROOT=/path/to/clang-p2996/build` (or `-DROSETTA_CXX_COMPILER=…`)
if yours is not at the default location. nanobind is taken from an installed
copy when available (`pip install nanobind`); otherwise CMake fetches a pinned
release at configure time (network access needed on the first configure).

```sh
cmake -S . -B build && cmake --build build
```

## Use

A post-build step copies the module next to the sources, so from this directory:

```sh
python3 -c "import {{LIB}}"
```)MD";

        // The one base class nanobind can be told about, or "" when there is
        // none. Shared by both nanobind backends (this header is included
        // before nanobind_expanded_backend.h).
        //
        // Registering the relationship is what makes a derived instance
        // acceptable where a base is expected: without it `nb::class_<Derived>`
        // is an unrelated Python type, and passing one to a method taking
        // `Base *` fails with "incompatible function arguments".
        //
        // Two filters apply, both of them nanobind's:
        //   - a base that is not itself bound is dropped — nanobind resolves it
        //     by looking the type up in the module.
        //   - at most ONE base survives. nb::class_<T, Ts...> pulls a single
        //     `Base` out of Ts and static_asserts that nothing else is left
        //     over ("invoked with extra arguments that could not be handled"):
        //     nanobind has no multiple inheritance, where pybind11 and sol2 do.
        //     A second bound base is reported and dropped rather than emitted
        //     into code that cannot compile.
        inline std::string nb_bound_base(const GenClass &k, const GenContext &c,
                                         const char *backend) {
            auto index_of = [&](const std::string &q) -> std::size_t {
                for (std::size_t i = 0; i < c.classes.size(); ++i) {
                    // A class with a non-public destructor is in the IR but
                    // never emitted (see the is_destructible guard on the class
                    // emitters), so it is no more registered than an unlisted
                    // type — naming it as a base would break the import.
                    if (qualified_of(c.classes[i]) == q && c.classes[i].is_destructible) {
                        return i;
                    }
                }
                return c.classes.size(); // not bound
            };
            const std::size_t self = index_of(qualified_of(k));

            std::string first;
            std::string dropped;
            for (const auto &b : k.bases) {
                const std::size_t at = index_of(b);
                if (at == c.classes.size()) {
                    continue; // base not bound — nothing to point nanobind at
                }
                if (first.empty()) {
                    first = b;
                    // nanobind binds in emission order and needs the base type
                    // already registered when the derived class declares it.
                    // Emission follows manifest order, so this is the user's to
                    // fix: flag it here rather than at import time.
                    if (at > self) {
                        std::fprintf(stderr,
                                     "rosetta::%s: class '%s' is bound before its base '%s' — "
                                     "list the base first in the manifest, or the module will "
                                     "fail to import\n",
                                     backend, k.name.c_str(), b.c_str());
                    }
                } else {
                    dropped += (dropped.empty() ? "" : ", ") + b;
                }
            }
            if (!dropped.empty()) {
                std::fprintf(stderr,
                             "rosetta::%s: class '%s' has several bound bases — kept '%s', "
                             "dropped %s (nanobind has no multiple inheritance)\n",
                             backend, k.name.c_str(), first.c_str(), dropped.c_str());
            }
            return first;
        }

        inline std::string nanobind_bindings(const GenContext &c) {
            std::string binds = init_block(c);
            for (const auto &e : c.enums) {
                binds += "    rosetta::bind_nanobind_enum<" + qualified_of(e) + ">(m, \"" +
                         exposed_of(e) + "\");\n";
            }
            for (const auto &k : c.classes) {
                // Trailing template argument: the bound base, forwarded to
                // nb::class_ by bind_nanobind<T, Bases...>.
                const std::string base = nb_bound_base(k, c, "nanobind");
                binds += "    rosetta::bind_nanobind<" + qualified_of(k) +
                         (base.empty() ? "" : ", " + base) + ">(m, \"" + exposed_of(k) + "\");\n";
            }
            for (const auto &f : c.functions) {
                binds += "    m.def(\"" + f.name + "\", " + fn_addr(f) +
                         (f.doc.empty() ? "" : ", \"" + f.doc + "\"") + ");\n";
            }
            return binds;
        }

        inline std::string nanobind_source(const GenContext &c) {
            return subst(NB_CPP, {{"LIB", c.lib},
                                  // includes_of() also emits the `using namespace`
                                  // a namespaced user library needs (so unqualified
                                  // bind_nanobind<T> resolves).
                                  {"INCLUDES", includes_of(c)},
                                  {"BINDINGS", nanobind_bindings(c)}});
        }

        inline std::string NanobindBackend::render(const GenContext &c) const {
            return nanobind_source(c);
        }

        inline void NanobindBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "nanobind";
            write_file(dir / "auto_nanobind.cpp", nanobind_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(NB_CMAKE, c));
            write_file(dir / "README.md",
                       readme("nanobind", c, subst(NB_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
