// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) N-API backend. Included by inline/generate.hxx
// after backends/node.h (reuses node_trampolines_of / node_virtual_methods) and
// backends/python.h (reuses qualify_std), plus the shared render
// helpers (subst / num_str / render_meta / write_file).

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        // Stock-toolchain CMake: C++20 (member-pointer + class-type NTTPs), the
        // user's headers, and rosetta's include dir for the reflection-free
        // runtime/node.h. No clang-p2996, no -freflection, no -nostdlib++.
        constexpr std::string_view NODEX_CMAKE = R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain N-API: NO C++26, NO reflection. rosetta's include dir is on the path
# only for the header-only, reflection-free runtime/node.h.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

if(NOT NODE_ADDON_API_DIR)
    execute_process(
        COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(REGEX REPLACE "^\"|\"$" "" NODE_ADDON_API_DIR "${NODE_ADDON_API_DIR}")
endif()

add_library({{LIB}} SHARED auto_napi.cpp ${CMAKE_JS_SRC})
set_target_properties({{LIB}} PROPERTIES PREFIX "" SUFFIX ".node")

target_include_directories({{LIB}} PRIVATE
    ${CMAKE_JS_INC}
    ${NODE_ADDON_API_DIR}
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}} PRIVATE ${CMAKE_JS_LIB})
target_compile_definitions({{LIB}} PRIVATE NAPI_VERSION={{NAPI_VERSION}})

{{USER_LIB_BLOCK}}

if(APPLE)
    target_link_options({{LIB}} PRIVATE -Wl,-undefined,dynamic_lookup)
endif()

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
{{OUT_DIR_BLOCK}}
)CMK";

        // Build section appended to the generated README. package.json is the
        // shared NODE_PACKAGE (same cmake-js/node-addon-api devDependencies and
        // `build` script), but the build itself differs from the thin backend:
        // NODEX_CMAKE sets no compiler and no reflection flags, so any stock
        // C++20 toolchain works — say so instead of sharing NODE_README_BUILD.
        constexpr std::string_view NODEX_README_BUILD = R"MD(## Build

Needs Node.js and a stock C++20 compiler — the emitted source is pre-expanded
(no C++26, no reflection toolchain). `npm install` pulls the two build-time
deps from `package.json`: cmake-js (drives CMake and supplies the Node headers)
and node-addon-api (the CMakeLists locates it via
`node -p "require('node-addon-api').include"`).

```sh
npm install
npm run build    # cmake-js compile
```

## Use

A post-build step copies the addon next to this README:

```sh
node -e "const m = require('./{{LIB}}.node'); console.log(Object.keys(m))"
```
)MD";

        // Can N-API marshal this IR type? Same surface as the reflective
        // napi_supported(): scalars, bool, string, enums, user objects, and
        // vectors of those; std::function / "unknown" cannot.
        // ---- package.json + N-API trampolines --------------------------------
        // Lived in the thin node backend until it was removed.
        constexpr std::string_view NODE_PACKAGE = R"JSON({
  "name": "{{LIB}}",
  "version": "1.0.0",
  "private": true,
  "description": "Auto-generated N-API bindings for {{LIB}}.",
  "main": "index.js",
  "scripts": {
    "build": "cmake-js compile",
    "rebuild": "cmake-js rebuild"
  },
  "devDependencies": {
    "cmake-js": "^7.3.0",
    "node-addon-api": "^8.0.0"
  }{{NODE_ENGINES}}
}
)JSON";

        // Instance virtual methods of a class — the ones a trampoline must shim.
        // A "final" class (manifest flag) never gets one: its virtuals bind as
        // ordinary methods, and — because the wrapped type is then T itself,
        // not Js_T — the class becomes eligible as an aliased member-object
        // property (mesh.vertices).
        inline std::vector<const GenMethod *> node_virtual_methods(const GenClass &k) {
            std::vector<const GenMethod *> out;
            if (k.is_final) {
                return out;
            }
            for (const auto &m : k.methods) {
                if (m.is_virtual && !m.is_static) {
                    out.push_back(&m);
                }
            }
            return out;
        }

        // One N-API trampoline: `class Js_T : public T, public rosetta::NapiTrampoline`.
        // Each virtual override reproduces the base signature exactly and routes
        // through napi_call_override[_pure], which dispatches to the JS subclass's
        // override (or falls back to the C++ base / throws for a pure virtual).
        inline std::string node_trampoline_for(const GenClass &k) {
            const auto virts = node_virtual_methods(k);
            if (virts.empty()) {
                return {};
            }
            // Named after the EXPOSED name (unique across the module) and derived
            // from the QUALIFIED spelling — see the python trampoline notes.
            const std::string kq = qualified_of(k);
            std::string s =
                "class Js_" + exposed_of(k) + " : public " + kq + ", public rosetta::NapiTrampoline {\npublic:\n";
            s += "    using " + kq + "::" + k.name + ";\n";
            for (const GenMethod *m : virts) {
                // Skip a virtual whose signature has no Node-API marshalling (e.g. a
                // pointer to a type left incomplete in this TU): napi_call_override
                // could not convert the argument and the override would fail to
                // compile. A concrete bound class still supplies the body.
                if (!m->sig_bindable) {
                    continue;
                }
                // A reference-returning virtual (AlgoBuilder::model() -> const
                // Model&): from_napi hands back a value, which cannot bind to
                // the lvalue reference the override must return — skip it. A
                // skipped PURE virtual leaves Js_T abstract; that only occurs
                // when T itself is abstract, and an abstract T never gets
                // ctor_table entries (its constructibility traits are false),
                // so nothing ever constructs the abstract Js_T.
                if (m->ret_is_ref) {
                    continue;
                }
                const bool  is_void = (m->ret_cpp == "void");
                // Exact spellings re-qualified per the IR: an unqualified user
                // token ("Data &") is ambiguous once two bound namespaces
                // declare it (see qualify_objects).
                const std::string rq  = qualify_objects(m->ret_cpp, m->ret);
                std::string sig     = "    " + rq + " " + m->name + "(";
                std::string names;  // p0, p1, ... — base-call + JS-forward args
                for (std::size_t i = 0; i < m->param_cpp.size(); ++i) {
                    const std::string pn = "p" + std::to_string(i);
                    std::string       pt = m->param_cpp[i];
                    if (i < m->params.size()) {
                        pt = qualify_objects(std::move(pt), m->params[i].type);
                    }
                    sig += (i ? ", " : "") + pt + " " + pn;
                    names += (i ? ", " : "") + pn;
                }
                sig += ")";
                if (m->is_const) {
                    sig += " const";
                }
                if (m->is_noexcept) {
                    sig += " noexcept";
                }
                sig += " override {\n        ";

                const std::string ret   = is_void ? "" : "return ";
                const std::string targs = names.empty() ? "" : ", " + names;
                if (m->is_pure) {
                    s += sig + ret + "rosetta::napi_call_override_pure<" + kq + ", " +
                         rq + ">(*this, \"" + m->name + "\"" + targs + ");\n    }\n";
                } else {
                    const std::string thunk = "[&]{ " + (is_void ? std::string() : std::string("return ")) +
                                              "this->" + kq + "::" + m->name + "(" + names + "); }";
                    s += sig + ret + "rosetta::napi_call_override<" + kq + ", " + rq +
                         ">(*this, \"" + m->name + "\", " + thunk + targs + ");\n    }\n";
                }
            }
            s += "};\n";
            return s;
        }

        inline std::string node_trampolines_of(const GenContext &c) {
            std::string body;
            for (const auto &k : c.classes) {
                body += node_trampoline_for(k);
            }
            if (body.empty()) {
                return {};
            }
            // `using namespace std;` is scoped to this trampoline-only namespace so
            // override signatures reproducing a parameter's exact spelling resolve
            // unqualified std names (display_string_of drops `std::`, e.g.
            // `vector<double, allocator<double>>`).
            return "\nnamespace rosetta_node {\nusing namespace std;\n" + body +
                   "} // namespace rosetta_node\n";
        }


        inline bool nx_marshalable(const GenType &t) {
            if (t.kind == "unknown") {
                return false;
            }
            if (t.kind == "vector") {
                return t.element.empty() || nx_marshalable(t.element.front());
            }
            return true;
        }

        // --- Copyability gates -------------------------------------------------
        // The node runtime copies at two boundaries: to_napi builds a fresh
        // wrapped object and copy-ASSIGNS into it (returns, field gets), and a
        // by-value class parameter copy-CONSTRUCTS from the reference from_napi
        // hands out. Where the copy is deleted the emitted line would not
        // compile, so gate on the copyability captured in the IR (non-copyable
        // classes — GEO::Mesh and its member stores — then bind as opaque
        // handles reached through references only).

        // --- Callbacks ---------------------------------------------------------
        // A std::function parameter is the only way a callback crosses: a member
        // TEMPLATE has nothing to reflect on, so a bindable API spells the
        // callback out as a concrete type. rosetta::napi_make_fn turns the JS
        // function into it (runtime/node.h), which is the node counterpart of the
        // wasm backend's rosetta_wx::make_fn.

        // Can a value of this type ride INSIDE the callback, i.e. through the
        // to_napi / from_napi pair the wrapper closure uses? Scalars, bool,
        // strings, enums and vectors of those. Raw pointers and nested callbacks
        // are out — nothing would build the inner adapter — and so are objects:
        // to_napi wraps a class by COPY into a fresh JS object, which is the
        // wrong identity for a value handed to a callback mid-iteration.
        inline bool nx_cb_convertible(const GenType &t) {
            if (t.is_pointer || t.is_callback || t.is_shared_ptr) {
                return false;
            }
            if (t.kind == "number" || t.kind == "boolean" || t.kind == "string" ||
                t.kind == "enum") {
                return true;
            }
            if (t.kind == "vector") {
                return !t.element.empty() && nx_cb_convertible(t.element.front());
            }
            return false;
        }

        // Bindable iff the whole signature is convertible (the return may be void).
        inline bool nx_callback_convertible(const GenType &t) {
            if (!t.is_callback || t.callback_sig.empty()) {
                return false;
            }
            const GenType &ret = t.callback_sig.front();
            if (!(ret.kind == "void" || nx_cb_convertible(ret))) {
                return false;
            }
            for (std::size_t i = 1; i < t.callback_sig.size(); ++i) {
                if (!nx_cb_convertible(t.callback_sig[i])) {
                    return false;
                }
            }
            return true;
        }

        // OK as an input (parameter / setter side)?
        inline bool nx_pass_ok(const GenParam &p) {
            const GenType &t = p.type;
            // A callback is not "marshalable" — its kind is unknown — but it IS
            // convertible when every type in its signature is. Checked before the
            // marshalable gate, which would reject it on kind alone.
            if (t.is_callback) {
                return nx_callback_convertible(t);
            }
            if (!nx_marshalable(t)) {
                return false;
            }
            // Shared ownership travels OUT only. from_napi would have to
            // manufacture a shared_ptr for an object whose JS wrapper may own it
            // outright or merely alias a member of another object — inventing a
            // control block over memory rosetta does not own is how a
            // double-free starts. A `const T&` parameter takes the same call.
            if (t.is_shared_ptr) {
                return false;
            }
            if (t.kind == "object") {
                return p.is_ref || t.copy_constructible; // by-ref never copies
            }
            // A mutable reference to a NON-class type (std::string&, index_t&)
            // is an out-parameter: from_napi hands back a temporary for these
            // kinds, which cannot bind to a non-const reference.
            if (p.is_mutable_ref) {
                return false;
            }
            if (t.kind == "vector" && !t.element.empty()) {
                const GenType &e = t.element.front();
                if (e.kind == "object" && !e.copy_constructible) {
                    return false; // from_napi push_back copies each element
                }
            }
            return true;
        }

        // OK as an output (return / field get side, i.e. through to_napi)?
        inline const GenClass *nx_bound_class(const GenType &t, const GenContext &c); // below

        // Does this method hand out a REFERENCE to a bound class? Such a method
        // binds through call_method_alias — the wrap aliases the referent and
        // pins the receiver — instead of to_napi, which would copy. A const
        // reference is included: JS has no constness to preserve, and the
        // alternative (a copy) is worse for a store the caller means to reach.
        inline bool nx_alias_return(const GenMethod &m, const GenContext &c) {
            return m.ret_is_ref && m.ret.kind == "object" && !m.ret.is_shared_ptr &&
                   nx_bound_class(m.ret, c) != nullptr;
        }

        inline bool nx_ret_ok(const GenType &t, const GenContext &c, bool ref_return = false) {
            if (t.kind == "void") {
                return true;
            }
            if (!nx_marshalable(t)) {
                return false;
            }
            // std::shared_ptr<T>: to_napi hands the OWNERSHIP to the JS object,
            // which adopts the shared_ptr and keeps the C++ object alive (the
            // third ownership mode in Wrap — see runtime/node.h). Two conditions,
            // both structural: T must be bound (its ctor_ref is what the adopt
            // path calls) and must have no virtuals, since the adopting Wrap
            // stores a T* and reading it as a trampoline subclass would be
            // undefined — the same restriction the aliased member-object path
            // carries, for the same reason. Must precede the "object" branch,
            // whose kind a shared_ptr also has.
            if (t.is_shared_ptr) {
                const GenClass *pk = nx_bound_class(shared_pointee(t), c);
                return pk != nullptr && node_virtual_methods(*pk).empty();
            }
            if (t.kind == "object") {
                // to_napi builds the wrapper through `ctor_ref<T>()`, which is
                // only set for a class this module REGISTERED. For anything else
                // — GEO::CSGCompiler::builder() returning an unbound
                // GEO::CSGBuilder&, a std::map, an incomplete helper — that
                // reference is empty and calling the method takes the process
                // down with a FATAL N-API error. Skipping is the honest reading,
                // and it is what wasm / lua already do.
                const GenClass *pk = nx_bound_class(t, c);
                if (pk == nullptr) {
                    return false;
                }
                // A REFERENCE return does not go through to_napi at all: it
                // hands out an aliased wrap pinned to the receiver
                // (call_method_alias), so copy-assignability is beside the
                // point — which is what lets `facet_corners.attributes()` bind
                // to a non-copyable AttributesManager. The alias stores a T*,
                // so the class must be untrampolined, exactly as the
                // member-object property path requires.
                if (ref_return) {
                    return node_virtual_methods(*pk).empty();
                }
                return t.copy_assignable; // to_napi: Wrap(...)->inner() = v
            }
            if (t.kind == "vector" && !t.element.empty()) {
                const GenType &e = t.element.front();
                if (e.kind == "object" && !e.copy_assignable) {
                    return false;
                }
            }
            return true;
        }

        // A range bound rendered as a `double` literal. set_field_ranged's Lo/Hi
        // are `double` non-type template params, and clang rejects an `int`
        // literal (e.g. 0) there in an explicit argument list — it must read as
        // a double (0.0), so we always force a decimal point.
        inline std::string nx_double_lit(double d) {
            std::string s = num_str(d);
            if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
                s.find('E') == std::string::npos) {
                s += ".0";
            }
            return s;
        }

        // --- Foreign containers (rosetta::is_sequence / is_matrix) -------------
        // A method touching a trait-registered sequence binds through a FREE
        // adapter function emitted at namespace scope: the runtime's fn_traits
        // introspect the ADAPTER's signature, so the boundary speaks
        // std::vector<element> (from_napi/to_napi handle that) and the adapter
        // builds the foreign container around the real call. Instance methods
        // ride ext_method<&adapter> (receiver = first param), statics ride
        // call_static<&adapter>, free functions napi_free_entry<&adapter>.
        // Because the adapter calls by NAME with concrete arguments, an
        // overload set whose surviving IR entry is the sequence one binds too.

        // Do the NON-sequence parts of the signature satisfy the node gates?
        inline bool nx_seq_rest_ok(const GenMethod &m, const GenContext &c) {
            if (!is_adapted(m.ret) && !nx_ret_ok(m.ret, c, nx_alias_return(m, c))) {
                return false;
            }
            for (const auto &p : m.params) {
                if (is_adapted(p.type) || is_out_param(p)) {
                    continue;
                }
                if (!nx_pass_ok(p)) {
                    return false;
                }
            }
            return true;
        }

        // Generic value/reference spelling for adapter params without an exact
        // param_cpp (extension methods, free functions).
        inline std::string nx_cpp_type(const GenType &t) {
            if (t.kind == "vector") {
                return "std::vector<" +
                       (t.element.empty() ? std::string("double")
                                          : nx_cpp_type(t.element.front())) +
                       ">";
            }
            if (t.kind == "object" || t.kind == "enum") {
                // Qualified when known: the unqualified identifier is ambiguous
                // once two bound namespaces declare it (the "expose" case).
                return t.object_qualified.empty() ? t.object : t.object_qualified;
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "number") {
                return t.spelling.empty() ? "double" : t.spelling;
            }
            return qualify_std(t.spelling);
        }

        // The namespace-scope adapter definition. `receiver` is the class name
        // for instance/extension flavors ("" for statics and free functions);
        // `callee` is what gets called — "self.assign_points", "georo::fn"
        // (with ext_self, which forwards `self` as the first argument),
        // "Cls::stat", "ns::freefn".
        inline std::string nx_seq_adapter_def(const std::string &fn_name,
                                              const std::string &receiver, const GenMethod &m,
                                              const std::string &callee, bool ext_self = false) {
            // Declarations and arguments are collected separately: an
            // out-parameter contributes an ARGUMENT (its local) but no
            // DECLARATION.
            std::vector<std::string> decls, args;
            if (!receiver.empty()) {
                decls.push_back(receiver + " &self");
            }
            std::string pre;
            const bool  exact = m.param_cpp.size() == m.params.size();
            for (std::size_t j = 0; j < m.params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                const GenType    &t  = m.params[j].type;
                if (is_out_param(m.params[j])) {
                    const std::string on = "out" + std::to_string(j);
                    pre += "        " + out_local_cpp(t) + " " + on + "{};\n";
                    args.push_back(on);
                    continue;
                }
                if (is_adapted(t)) {
                    const std::string sn = adapt_local(t, j);
                    decls.push_back(adapt_boundary_cpp(t) + " " + an);
                    pre += adapt_decl_stmts(t, an, sn, "        ");
                    args.push_back(sn);
                } else if (exact) {
                    decls.push_back(qualify_objects(qualify_std(m.param_cpp[j]), t) + " " + an);
                    args.push_back(an);
                } else if (t.kind == "object") {
                    decls.push_back(nx_cpp_type(t) + " &" + an);
                    args.push_back(an);
                } else {
                    decls.push_back(nx_cpp_type(t) + " " + an);
                    args.push_back(an);
                }
            }
            // The receiver is spelled in the declaration list but passed
            // separately by the ext_self form, so it never joins `args`.
            const std::string arg_list = join(args, ", ");
            const std::string invoke =
                ext_self ? (callee + "(self" + (arg_list.empty() ? "" : ", " + arg_list) + ")")
                         : (callee + "(" + arg_list + ")");
            // Out-parameters: rebuild them here rather than in the shared helper,
            // because the adapter must also name its own return TYPE.
            std::vector<OutParam> outs;
            for (std::size_t j = 0; j < m.params.size(); ++j) {
                if (is_out_param(m.params[j])) {
                    const std::string on = "out" + std::to_string(j);
                    outs.push_back({on, out_expr(m.params[j].type, on)});
                }
            }
            std::string ret, body = pre;
            if (!outs.empty()) {
                // A std::tuple, which to_napi turns into a JS array: the return
                // value first when there is one, then the out-parameters.
                std::vector<std::string> types;
                if (m.ret.kind != "void") {
                    types.push_back(is_adapted(m.ret) ? adapt_boundary_cpp(m.ret)
                                                      : nx_cpp_type(m.ret));
                }
                for (std::size_t j = 0; j < m.params.size(); ++j) {
                    if (is_out_param(m.params[j])) {
                        types.push_back(out_boundary_cpp(m.params[j].type));
                    }
                }
                ret = "std::tuple<" + join(types, ", ") + ">";
                body += out_return_stmts(m, outs, invoke, "        ");
            } else if (is_adapted(m.ret)) {
                ret = adapt_boundary_cpp(m.ret);
                body += "        auto &&r = " + invoke + ";\n";
                body += "        return " + adapt_from_expr(m.ret, "r") + ";\n";
            } else if (m.ret.kind == "void") {
                ret = "void";
                body += "        " + invoke + ";\n";
            } else {
                ret = "decltype(auto)"; // preserve a reference return (to_napi copies)
                body += "        return " + invoke + ";\n";
            }
            return "    inline " + ret + " " + fn_name + "(" + join(decls, ", ") + ") {\n" + body +
                   "    }\n";
        }

        inline bool nx_method_ok(const GenMethod &m, const GenContext &c) {
            // Overload set: `&T::name` in the thunk template argument would be
            // ambiguous. The emitter routes such a method through the free
            // adapter path instead (which calls by name), so reaching here with
            // is_overloaded means the member-pointer spelling was about to be
            // used — reject it.
            if (m.is_overloaded) {
                return false;
            }
            if (!nx_ret_ok(m.ret, c, nx_alias_return(m, c))) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!nx_pass_ok(p)) {
                    return false;
                }
            }
            return true;
        }

        // One class, expanded into a DefineClass block. `held` is the concrete
        // wrapped type — the trampoline subclass when the class has virtuals,
        // else T itself — matching what bind_napi<T, Tramp> instantiates.
        // The GenClass bound under this unqualified name, or nullptr. Used by
        // the member-object property path: the field's class must itself be
        // bound (it provides the JS constructor the aliased wrap rides on) and
        // must have no virtuals (the alias stores a T*, not a trampoline).
        inline const GenClass *nx_bound_class(const GenType &t, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (t.object_qualified.empty() ? (k.name == t.object)
                                               : (qualified_of(k) == t.object_qualified)) {
                    return &k;
                }
            }
            return nullptr;
        }

        inline std::string node_expanded_class(const GenClass &k, const GenContext &c,
                                               std::string &adapters) {
            // A class whose destructor is not public cannot be wrapped: every
            // runtime backend destroys what it holds. Skip it with a note —
            // the alternative is a compile error inside the framework headers.
            if (!k.is_destructible) {
                std::fprintf(stderr,
                             "rosetta::%s: class '%s' has a non-public destructor "
                             "(ref-counted?) — skipped\n",
                             "node", k.name.c_str());
                return {};
            }

            const auto        virts = node_virtual_methods(k);
            const std::string kx    = exposed_of(k);
            const std::string held =
                virts.empty() ? qualified_of(k) : "rosetta_node::Js_" + kx;
            const std::string self = qualified_of(k);
            const std::string th   = "rosetta::Wrap<" + self + ", " + held + ">";

            std::string s = "    {\n";
            s += "        using This = " + th + ";\n";
            s += "        std::vector<Napi::ClassPropertyDescriptor<This>> props;\n";

            // Fields → InstanceAccessor(getter, setter). Both directions copy
            // (get_field via to_napi, set_field via copy assignment), so a
            // non-copy-assignable member object is skipped — UNLESS its class
            // is itself bound (and untrampolined): then it becomes a read-only
            // member-object property returning an aliased wrap that pins the
            // parent (get_member_object in runtime/node.h).
            for (const auto &f : k.fields) {
                if (!nx_marshalable(f.type) || !nx_ret_ok(f.type, c) ||
                    (f.type.kind == "object" && !f.type.copy_assignable)) {
                    const GenClass *fk = f.type.kind == "object"
                                             ? nx_bound_class(f.type, c)
                                             : nullptr;
                    bool clashes = false;
                    for (const auto &m : k.methods) {
                        clashes = clashes || m.name == f.name;
                    }
                    if (fk != nullptr && node_virtual_methods(*fk).empty() && !clashes) {
                        const std::string mp = "&" + self + "::" + f.name;
                        s += "        props.push_back(This::InstanceAccessor<"
                             "&This::get_member_object<" + mp + ">, "
                             "&This::set_field_readonly<" + mp + ", \"" + f.name +
                             "\">>(\"" + f.name + "\"));\n";
                    }
                    continue;
                }
                const std::string mp  = "&" + self + "::" + f.name;
                const std::string get = "&This::get_field<" + mp + ">";
                std::string       set;
                if (f.is_readonly) {
                    set = "&This::set_field_readonly<" + mp + ", \"" + f.name + "\">";
                } else if (f.range.has && f.type.kind == "number") {
                    set = "&This::set_field_ranged<" + mp + ", \"" + f.name + "\", " +
                          nx_double_lit(f.range.min) + ", " + nx_double_lit(f.range.max) + ">";
                } else {
                    set = "&This::set_field<" + mp + ">";
                }
                s += "        props.push_back(This::InstanceAccessor<" + get + ", " + set +
                     ">(\"" + f.name + "\"));\n";
            }

            // Methods → InstanceMethod / StaticMethod. Extension methods call
            // their free function through ext_method (receiver = the wrapped
            // object) instead of a member pointer.
            for (const auto &m : k.methods) {
                // N-API property descriptors are keyed by name: two
                // InstanceMethod entries called "f" are a duplicate, not an
                // overload, and the two free adapters below would collide on
                // the same C++ function name. JS cannot dispatch on argument
                // types, so only the first-declared overload binds; the rest
                // are recorded for the coverage report.
                if (!coverage::emit_overload(coverage::overloads::first_only, "node", k,
                                             m)) {
                    continue;
                }
                if (seq_touches(m)) {
                    // Foreign sequence in the signature: free-adapter or
                    // nothing (from_napi has no conversion for the foreign
                    // type; overloaded sets are fine here, see the adapter
                    // notes above).
                    if (!seq_adaptable(m) || !nx_seq_rest_ok(m, c)) {
                        coverage::note_skip("node", k, m, "sequence_not_adaptable",
                                            "a registered sequence in the signature has no "
                                            "std::vector boundary adapter for this backend");
                        continue;
                    }
                    const std::string an = "seq_" + kx + "_" + m.name; // identifier-safe
                    if (m.is_extension) {
                        adapters +=
                            nx_seq_adapter_def(an, self, m, m.ext_qualified, true);
                    } else if (m.is_static) {
                        adapters += nx_seq_adapter_def(an, "", m, self + "::" + m.name);
                    } else {
                        adapters += nx_seq_adapter_def(an, self, m, "self." + m.name);
                    }
                    if (m.is_static) {
                        s += "        props.push_back(This::StaticMethod<&This::call_static<"
                             "&rosetta_nx_seq::" + an + ">>(\"" + m.name + "\"));\n";
                    } else {
                        s += "        props.push_back(This::InstanceMethod<&This::ext_method<"
                             "&rosetta_nx_seq::" + an + ">>(\"" + m.name + "\"));\n";
                    }
                    coverage::note_bound("node", k, m);
                    continue;
                }
                if (m.is_overloaded && !m.is_extension) {
                    // Overload set: `&T::name` in the thunk template argument
                    // would be ambiguous. The entry that got past the gate above
                    // (the first-declared one) binds through a free adapter that
                    // calls by NAME with concrete arguments — same trick as the
                    // sequence path.
                    GenMethod probe    = m;
                    probe.is_overloaded = false;
                    if (!nx_method_ok(probe, c)) {
                        coverage::note_skip("node", k, m, "unmarshalable_signature",
                                            "no N-API conversion for a type in this signature");
                        continue; // the survivor's own signature fails the gates
                    }
                    coverage::note_bound("node", k, m);
                    const std::string an = "ovl_" + kx + "_" + m.name;
                    if (m.is_static) {
                        adapters += nx_seq_adapter_def(an, "", m, self + "::" + m.name);
                        s += "        props.push_back(This::StaticMethod<&This::call_static<"
                             "&rosetta_nx_seq::" + an + ">>(\"" + m.name + "\"));\n";
                    } else {
                        adapters += nx_seq_adapter_def(an, self, m, "self." + m.name);
                        s += "        props.push_back(This::InstanceMethod<&This::ext_method<"
                             "&rosetta_nx_seq::" + an + ">>(\"" + m.name + "\"));\n";
                    }
                    continue;
                }
                if (!nx_method_ok(m, c)) {
                    coverage::note_skip("node", k, m, "unmarshalable_signature",
                                        "no N-API conversion for a type in this signature "
                                        "(e.g. a std::function parameter, or a non-const "
                                        "reference the converted temporary cannot bind to)");
                    continue;
                }
                if (m.is_extension) {
                    s += "        props.push_back(This::InstanceMethod<&This::ext_method<&" +
                         m.ext_qualified + ">>(\"" + m.name + "\"));\n";
                    coverage::note_bound("node", k, m);
                    continue;
                }
                const std::string mp = "&" + self + "::" + m.name;
                if (m.is_static) {
                    s += "        props.push_back(This::StaticMethod<&This::call_static<" + mp +
                         ">>(\"" + m.name + "\"));\n";
                } else if (nx_alias_return(m, c)) {
                    // Returns a reference to a bound class: alias it, pinning
                    // this object as the parent (see call_method_alias).
                    s += "        props.push_back(This::InstanceMethod<&This::call_method_alias<" +
                         mp + ">>(\"" + m.name + "\"));\n";
                } else {
                    s += "        props.push_back(This::InstanceMethod<&This::call_method<" + mp +
                         ">>(\"" + m.name + "\"));\n";
                }
                coverage::note_bound("node", k, m);
            }

            s += "        Napi::Function ctor = This::DefineClass(env, \"" + kx + "\", props);\n";
            s += "        rosetta::ctor_ref<" + self + ">() = Napi::Persistent(ctor);\n";
            s += "        rosetta::ctor_ref<" + self + ">().SuppressDestruct();\n";

            // Constructors → ctor_table entries on the held type, keyed by arity.
            // A default-constructible class ASSIGNS the freshly built object
            // into the Wrap's inner storage (so it must be assignable —
            // GEO::Mesh keeps only the default ctor); a class WITHOUT a default
            // ctor is constructed straight from the entry into fresh storage
            // (so it must be copy- or move-constructible).
            const bool ctor_entries_ok = k.is_default_constructible
                                             ? k.copy_or_move_assignable
                                             : k.copy_or_move_constructible;
            for (std::size_t i = 0; ctor_entries_ok && i < k.ctor_param_cpp.size(); ++i) {
                const auto &ir = k.ctors[i];
                bool        ok = true;
                for (const auto &p : ir) {
                    ok = ok && nx_pass_ok(p);
                }
                if (!ok) {
                    continue;
                }
                const auto &params = k.ctor_param_cpp[i];
                if (params.empty()) {
                    continue; // 0-arg: Wrap default-constructs `inner`, no entry needed
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    std::string one = qualify_std(params[j]);
                    if (j < ir.size()) {
                        one = qualify_objects(std::move(one), ir[j].type);
                    }
                    args += (j ? ", " : "") + std::string("rosetta::from_napi<std::remove_cvref_t<") +
                            one + ">>(info[" + std::to_string(j) + "])";
                }
                s += "        rosetta::ctor_table<" + held + ">()[" + std::to_string(params.size()) +
                     "] =\n            [](const Napi::CallbackInfo &info) { return " + held + "(" +
                     args + "); };\n";
            }

            // Override guard: record each virtual method's bound prototype fn so
            // the trampoline can tell a JS override from the inherited binding.
            if (!virts.empty()) {
                s += "        {\n";
                s += "            Napi::Object proto = ctor.Get(\"prototype\").As<Napi::Object>();\n";
                s += "            auto &guard = rosetta::napi_override_guard<" + self + ">();\n";
                for (const GenMethod *m : virts) {
                    if (!nx_method_ok(*m, c)) {
                        continue;
                    }
                    s += "            if (proto.Get(\"" + m->name + "\").IsFunction()) {\n";
                    s += "                guard[\"" + m->name +
                         "\"] = Napi::Persistent(proto.Get(\"" + m->name +
                         "\").As<Napi::Function>());\n";
                    s += "                guard[\"" + m->name + "\"].SuppressDestruct();\n";
                    s += "            }\n";
                }
                s += "        }\n";
            }

            s += "        exports.Set(\"" + kx + "\", ctor);\n";
            s += "    }\n";
            return s;
        }

        inline std::string node_expanded_source(const GenContext &c) {
            std::string body;
            std::string adapters; // namespace-scope sequence adapters (rosetta_nx_seq)
            for (const auto &e : c.enums) {
                body += "    exports.Set(\"" + exposed_of(e) + "\", rosetta::make_enum(env, {";
                for (std::size_t i = 0; i < e.values.size(); ++i) {
                    body += (i ? ", " : "") + std::string("{\"") + e.values[i].name + "\", " +
                            std::to_string(e.values[i].value) + "}";
                }
                body += "}));\n";
            }
            for (const auto &k : c.classes) {
                body += node_expanded_class(k, c, adapters);
            }
            for (const auto &f : c.functions) {
                GenMethod probe;
                probe.ret    = f.ret;
                probe.params = f.params;
                if (seq_touches(probe)) {
                    if (seq_adaptable(probe) && nx_seq_rest_ok(probe, c)) {
                        const std::string an = "seq_fn_" + f.name;
                        adapters += nx_seq_adapter_def(an, "", probe, fn_call_expr(f));
                        body += "    exports.Set(\"" + f.name +
                                "\", Napi::Function::New(env, "
                                "&rosetta::napi_free_entry<&rosetta_nx_seq::" + an +
                                ">, \"" + f.name + "\"));\n";
                    }
                    continue;
                }
                bool ok = nx_ret_ok(f.ret, c);
                for (const auto &p : f.params) {
                    ok = ok && nx_pass_ok(p);
                }
                if (ok) {
                    body += "    exports.Set(\"" + f.name +
                            "\", Napi::Function::New(env, &rosetta::napi_free_entry<" + fn_addr(f) +
                            ">, \"" + f.name + "\"));\n";
                }
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += "#include <napi.h>\n";
            out += "#include <rosetta/runtime/node.h>\n";
            auto add = [&](const std::string &h) { append_include(out, h); };
            out += init_includes(c);
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            if (!adapters.empty()) {
                out += "\n// Foreign-container adapters (rosetta::is_sequence / is_matrix): the\n"
                       "// boundary speaks std::vector<element> — a vector of those rows for a\n"
                       "// matrix; the adapter builds the foreign container around the real\n"
                       "// call (a mutable Seq& / Mat& binds input-only).\n"
                       "#include <algorithm>\n"
                       "#include <filesystem>\n"
                       "#include <tuple>\n"
                       "#include <vector>\n"
                       "namespace rosetta_nx_seq {\n" + adapters + "}\n";
            }
            out += node_trampolines_of(c); // reflection-free; empty when no virtuals
            out += "\nNapi::Object Init(Napi::Env env, Napi::Object exports) {\n";
            out += init_block(c);
            out += body;
            out += "    return exports;\n}\n\n";
            out += "NODE_API_MODULE(" + c.lib + ", Init)\n";
            return out;
        }

        inline std::string Node::render(const GenContext &c) const {
            return node_expanded_source(c);
        }

        inline void Node::emit(const GenContext &c) const {
            auto dir = c.out_dir / "node";
            write_file(dir / "auto_napi.cpp", node_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(NODEX_CMAKE, c));
            write_file(dir / "package.json", render_meta(NODE_PACKAGE, c));
            write_file(dir / "README.md",
                       readme("node", c,
                              subst(NODEX_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace backend
} // namespace rosetta
