// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) pybind11 backend. Included by inline/generate.hxx
// after python_backend.h, whose virtual_methods()/trampolines_of() helpers it
// reuses, and after the shared render helpers (subst / num_str / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // A stock-toolchain CMake: C++17, pybind11, the user's include dir only.
        // No clang-p2996, no -freflection/-fannotation-attributes, no -nostdlib++.
        constexpr std::string_view PYX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# These bindings are plain pybind11: NO C++26, NO reflection, NO rosetta headers.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

execute_process(
    COMMAND python3 -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python3_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(PYBIND11_FINDPYTHON ON)

# Prefer an installed pybind11 (pip), fall back to fetching a pinned release.
if(NOT pybind11_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -m pybind11 --cmakedir
        OUTPUT_VARIABLE pybind11_DIR
        RESULT_VARIABLE _pybind11_probe
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _pybind11_probe EQUAL 0)
        set(pybind11_DIR "")
    endif()
endif()
if(pybind11_DIR)
    find_package(pybind11 REQUIRED CONFIG)
else()
    include(FetchContent)
    FetchContent_Declare(
        pybind11
        GIT_REPOSITORY https://github.com/pybind/pybind11.git
        GIT_TAG v3.0.4)
    FetchContent_MakeAvailable(pybind11)
endif()

pybind11_add_module({{LIB}} NO_EXTRAS auto_pybind.cpp)

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}})

{{USER_LIB_BLOCK}}

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        // Build/Use section for the generated README — kept next to PYX_CMAKE
        // so the doc can't drift from the template it describes. Unlike the
        // thin python backend the source is pre-expanded: plain C++17 pybind11,
        // any stock compiler, no clang-p2996 and no rosetta headers.
        constexpr std::string_view PYX_README_BUILD = R"MD(## Build

The emitted source is plain C++17 pybind11 — any stock compiler works; no
reflection toolchain, no rosetta headers. pybind11 is taken from an installed
copy when available (`pip install pybind11`); otherwise CMake fetches a pinned
release at configure time (network access needed on the first configure).

```sh
cmake -S . -B build && cmake --build build
```

## Use

A post-build step copies the module next to the sources, so from this directory:

```sh
python3 -c "import {{LIB}}"
```)MD";

        // Escape a docstring for a C++ string literal (backslash + quote only;
        // annotation text is short single-line prose in practice).
        inline std::string py_lit(const std::string &s) {
            std::string out;
            for (char ch : s) {
                if (ch == '\\' || ch == '"') {
                    out += '\\';
                }
                out += ch;
            }
            return out;
        }

        // Trailing `, "doc"` for a pybind call, or empty when there is no doc.
        inline std::string doc_arg(const std::string &doc) {
            return doc.empty() ? std::string{} : ", \"" + py_lit(doc) + "\"";
        }

        // Re-qualify standard-library names in an exact type spelling. The
        // p2996 fork's display_string_of prints library types unqualified
        // (`vector<double, allocator<double>>`); a stock compiler needs the
        // `std::`. We word-match a known set of std identifiers and prepend
        // `std::` when the occurrence is a standalone token not already
        // qualified. Only constructor parameter types are spelled out in the
        // emitted code (fields/methods go through member pointers, which keep
        // types implicit), so this is the single place qualification is needed.
        inline std::string qualify_std(std::string s) {
            static constexpr std::string_view names[] = {
                "basic_string", "string_view", "string",  "wstring",     "vector",
                "allocator",    "char_traits", "function", "shared_ptr",  "unique_ptr",
                "unordered_map","unordered_set","map",     "multimap",    "set",
                "multiset",     "pair",        "tuple",    "array",       "list",
                "deque",        "optional",    "variant",  "hash",        "less",
                "equal_to",     "size_t",      "ptrdiff_t"};
            auto ident_char = [](char ch) {
                return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                       (ch >= '0' && ch <= '9') || ch == '_';
            };
            for (std::string_view nm : names) {
                std::string::size_type pos = 0;
                while ((pos = s.find(nm, pos)) != std::string::npos) {
                    const bool left_ok =
                        pos == 0 || (!ident_char(s[pos - 1]) && s[pos - 1] != ':');
                    const std::string::size_type end = pos + nm.size();
                    const bool right_ok = end >= s.size() || !ident_char(s[end]);
                    if (left_ok && right_ok) {
                        s.insert(pos, "std::");
                        pos = end + 5; // past the inserted "std::" + name
                    } else {
                        pos = end;
                    }
                }
            }
            return s;
        }

        // The #include block: pybind11 + the user headers. No rosetta header, so
        // the TU pulls in no reflection machinery whatsoever.
        inline std::string expanded_includes(const GenContext &c) {
            std::string s = "#include <pybind11/pybind11.h>\n"
                            "#include <pybind11/stl.h>\n"
                            "#include <pybind11/functional.h>\n"
                            "#include <algorithm>\n"
                            "#include <vector>\n";
            auto add = [&](const std::string &h) { append_include(s, h); };
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            return s;
        }

        // --- Marshalling gates -------------------------------------------------
        // pybind copies at several boundaries: def_readwrite's setter
        // copy-assigns, a by-value class parameter copy-constructs, and the
        // automatic return policy COPIES an lvalue-ref return. Where the copy
        // is deleted the emitted line would not compile, so gate on the
        // copyability captured in the IR. A class whose data API lives in
        // non-copyable public members (GEO::Mesh) then binds as an opaque
        // handle instead of breaking the build.

        // Can this type ride a def_readwrite / vector caster (which copy)?
        inline bool px_copyable(const GenType &t) {
            if (t.kind == "object") {
                return t.copy_constructible && t.copy_assignable;
            }
            if (t.kind == "vector") {
                return t.element.empty() || px_copyable(t.element.front());
            }
            return true;
        }

        inline bool px_field_ok(const GenField &f) {
            return px_copyable(f.type);
        }

        inline bool px_method_ok(const GenMethod &m) {
            // An overload set: the bare `&T::name` member pointer the emitter
            // spells would be ambiguous — skip the whole set.
            if (m.is_overloaded) {
                return false;
            }
            // Lvalue-ref class return: policy `automatic` copies it; a by-value
            // class return needs copy/move too (copy_constructible is the
            // conservative proxy for both).
            if (m.ret.kind == "object" && !m.ret.copy_constructible) {
                return false;
            }
            if (m.ret.kind == "vector" && !px_copyable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false; // by-value class parameter copy-constructs
                }
                if (p.type.kind == "vector" && !px_copyable(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // Explicit pybind for one enum: py::enum_<E>(m,"E").value("A", E::A)...;
        inline std::string expanded_enum(const GenEnum &e) {
            std::string s = "    py::enum_<" + e.name + ">(m, \"" + e.name + "\")";
            for (const auto &v : e.values) {
                s += "\n        .value(\"" + v.name + "\", " + e.name + "::" + v.name + ")";
            }
            s += ";\n";
            return s;
        }

        // Explicit pybind for one field, mirroring PybindVisitor::field():
        // readonly -> def_readonly; arithmetic + range -> validating def_property;
        // otherwise def_readwrite. Member pointers keep the field type implicit,
        // so no type spelling is needed except for the range setter's parameter.
        inline std::string expanded_field(const GenClass &k, const GenField &f) {
            const std::string self  = k.name;
            const std::string mp    = "&" + self + "::" + f.name; // member pointer
            const std::string dq    = doc_arg(f.doc);
            if (f.is_readonly) {
                return "    c.def_readonly(\"" + f.name + "\", " + mp + dq + ");\n";
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string ty  = f.type.spelling; // arithmetic -> compilable spelling
                const std::string lo  = num_str(f.range.min);
                const std::string hi  = num_str(f.range.max);
                std::string s;
                s += "    c.def_property(\"" + f.name + "\",\n";
                s += "        [](const " + self + " &s) { return s." + f.name + "; },\n";
                s += "        [](" + self + " &s, " + ty + " v) {\n";
                s += "            if (v < " + lo + " || v > " + hi + ")\n";
                s += "                throw py::value_error(\"" + f.name + " out of range [" + lo +
                     ", " + hi + "]\");\n";
                s += "            s." + f.name + " = v;\n";
                s += "        }" + dq + ");\n";
                return s;
            }
            return "    c.def_readwrite(\"" + f.name + "\", " + mp + dq + ");\n";
        }

        // Member-object property: a public data member whose type is another
        // BOUND class but is not copyable (a plain def_readwrite/def_readonly
        // would copy). Emitted as a read-only property returning a reference,
        // with reference_internal so the parent outlives every child handle —
        // `mesh.vertices` hands out the real MeshVertices living inside the
        // mesh. This is what makes struct-of-member-objects APIs (GEO::Mesh)
        // reachable without a flat-array facade.
        inline bool px_is_bound_class(const std::string &obj, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (k.name == obj) {
                    return true;
                }
            }
            return false;
        }

        inline std::string expanded_member_object(const GenClass &k, const GenField &f) {
            const std::string dq = doc_arg(f.doc);
            std::string s;
            s += "    c.def_property_readonly(\"" + f.name + "\",\n";
            s += "        [](" + k.name + " &s) -> " + f.type.object + " & { return s." +
                 f.name + "; },\n";
            s += "        py::return_value_policy::reference_internal" + dq + ");\n";
            return s;
        }

        // --- Foreign sequences (rosetta::is_sequence) --------------------------
        // A method touching a trait-registered sequence binds through a lambda
        // adapter: the script side speaks std::vector<element> (pybind's stl.h
        // caster), the adapter builds the foreign container before the call and
        // flattens a returned one after. The adapter calls the method BY NAME
        // with concrete arguments, so — unlike the member-pointer path — an
        // overload set whose surviving IR entry is the sequence overload binds
        // (GEO::MeshVertices::assign_points). A mutable `Seq&` parameter binds
        // input-only: the adapter's local container is a real lvalue and
        // in-place mutations are discarded, exactly like pybind's std::vector&.

        // A compilable value/reference spelling for adapter parameters that
        // carry no exact param_cpp (extension methods, free functions).
        inline std::string px_cpp_type(const GenType &t) {
            if (t.kind == "vector") {
                return "std::vector<" +
                       (t.element.empty() ? std::string("double")
                                          : px_cpp_type(t.element.front())) +
                       ">";
            }
            if (t.kind == "object" || t.kind == "enum") {
                return t.object;
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "number") {
                return t.spelling.empty() ? "double" : t.spelling;
            }
            return qualify_std(t.spelling);
        }

        // Do the NON-sequence parts of the signature still satisfy the python
        // gates? (The sequence parts go through the adapter, which lifts the
        // vector-copy and overload restrictions.)
        inline bool px_seq_rest_ok(const GenMethod &m) {
            if (m.ret.kind == "object" && !m.ret.copy_constructible) {
                return false;
            }
            if (m.ret.kind == "vector" && !px_copyable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (p.type.is_sequence) {
                    continue;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false;
                }
                if (p.type.kind == "vector" && !px_copyable(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // The adapter lambda's (parameter decls, pre-call statements, call args).
        struct PxSeqSig {
            std::string decls;
            std::string pre;
            std::string args;
        };
        inline PxSeqSig px_seq_sig(const std::vector<GenParam>    &params,
                                   const std::vector<std::string> &param_cpp) {
            PxSeqSig    o;
            const bool  exact = param_cpp.size() == params.size();
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                if (j) {
                    o.decls += ", ";
                    o.args += ", ";
                }
                const GenType &t = params[j].type;
                if (t.is_sequence) {
                    const std::string sn = "seq" + std::to_string(j);
                    o.decls += seq_boundary_cpp(t) + " " + an;
                    o.pre += seq_decl_stmts(t, an, sn, "        ");
                    o.args += sn;
                } else if (exact) {
                    o.decls += qualify_std(param_cpp[j]) + " " + an;
                    o.args += an;
                } else if (t.kind == "object") {
                    o.decls += px_cpp_type(t) + " &" + an; // bound class, by ref
                    o.args += an;
                } else {
                    o.decls += px_cpp_type(t) + " " + an;
                    o.args += an;
                }
            }
            return o;
        }

        // The full def(...) for a sequence-adapted method / extension / static.
        inline std::string px_seq_method(const GenClass &k, const GenMethod &m) {
            const PxSeqSig    sig = px_seq_sig(m.params, m.param_cpp);
            std::string       decls, call;
            if (m.is_extension) {
                decls = k.name + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = m.ext_qualified + "(self" + (sig.args.empty() ? "" : ", " + sig.args) +
                       ")";
            } else if (m.is_static) {
                decls = sig.decls;
                call  = k.name + "::" + m.name + "(" + sig.args + ")";
            } else {
                decls = k.name + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = "self." + m.name + "(" + sig.args + ")";
            }
            std::string body = sig.pre;
            if (m.ret.is_sequence) {
                body += "        auto &&r = " + call + ";\n";
                body += "        return " + seq_from_expr(m.ret, "r") + ";\n";
            } else if (m.ret.kind == "void") {
                body += "        " + call + ";\n";
            } else {
                body += "        return " + call + ";\n";
            }
            const std::string def = m.is_static ? "def_static" : "def";
            return "    c." + def + "(\"" + m.name + "\", [](" + decls + ") {\n" + body +
                   "    }" + doc_arg(m.doc) + ");\n";
        }

        // A sequence-typed field: def_property copying through the boundary
        // vector in both directions (member pointers would hand pybind the
        // casterless foreign type).
        inline std::string px_seq_field(const GenClass &k, const GenField &f) {
            const std::string vt = seq_boundary_cpp(f.type);
            const std::string dq = doc_arg(f.doc);
            std::string       s;
            const std::string get = "[](const " + k.name + " &s) { return " +
                                    seq_from_expr(f.type, "s." + f.name) + "; }";
            if (f.is_readonly) {
                return "    c.def_property_readonly(\"" + f.name + "\", " + get + dq + ");\n";
            }
            s += "    c.def_property(\"" + f.name + "\",\n";
            s += "        " + get + ",\n";
            s += "        [](" + k.name + " &s, const " + vt + " &v) {\n";
            s += "            s." + f.name + ".resize(v.size());\n";
            s += "            std::copy(v.begin(), v.end(), s." + f.name + ".begin());\n";
            s += "        }" + dq + ");\n";
            return s;
        }

        // Explicit pybind for one method. Overloads are deduped by name in the
        // walk and the surviving IR entry is flagged is_overloaded (px_method_ok
        // skips it), so the bare &T::m member pointer here is unambiguous. An
        // extension method binds its free function instead — pybind treats a
        // free function whose first parameter is T& as an instance method.
        inline std::string expanded_method(const GenClass &k, const GenMethod &m) {
            const std::string dq = doc_arg(m.doc);
            if (m.is_extension) {
                return "    c.def(\"" + m.name + "\", &" + m.ext_qualified + dq + ");\n";
            }
            const std::string mp = "&" + k.name + "::" + m.name;
            if (m.is_static) {
                return "    c.def_static(\"" + m.name + "\", " + mp + dq + ");\n";
            }
            return "    c.def(\"" + m.name + "\", " + mp + dq + ");\n";
        }

        // The constructors, as py::init<...>() lines. Exact param spellings come
        // from GenClass::ctor_param_cpp; a synthetic py::init<>() is added when T
        // is default-constructible but no zero-arg ctor was enumerated.
        inline std::string expanded_ctors(const GenClass &k) {
            std::string s;
            bool        saw_default = false;
            for (const auto &params : k.ctor_param_cpp) {
                if (params.empty()) {
                    saw_default = true;
                }
                std::string args;
                for (std::size_t i = 0; i < params.size(); ++i) {
                    args += (i ? ", " : "") + qualify_std(params[i]);
                }
                s += "    c.def(py::init<" + args + ">());\n";
            }
            if (!saw_default && k.is_default_constructible) {
                s += "    c.def(py::init<>());\n";
            }
            return s;
        }

        // One class block: an open scope so the local `c` never leaks. Uses the
        // trampoline (py::class_<T, Py_T>) when the class has virtual methods —
        // the trampoline classes themselves are emitted, verbatim, by the
        // existing reflection-free trampolines_of() helper.
        inline std::string expanded_class(const GenClass &k, const GenContext &c) {
            const bool        has_tramp = !virtual_methods(k).empty();
            const std::string decl = has_tramp ? "py::class_<" + k.name + ", rosetta_py::Py_" +
                                                     k.name + ">"
                                               : "py::class_<" + k.name + ">";
            std::string s = "    {\n        " + decl + " c(m, \"" + k.name + "\");\n";
            // The block-local helper lines are written at one indent; reuse the
            // module-level emitters and shift them in by four spaces.
            auto indent = [](const std::string &block) {
                std::string out;
                std::size_t i = 0;
                while (i < block.size()) {
                    std::size_t nl = block.find('\n', i);
                    if (nl == std::string::npos) {
                        nl = block.size();
                    }
                    out += "    " + block.substr(i, nl - i + 1);
                    i = nl + 1;
                }
                return out;
            };
            s += indent(expanded_ctors(k));
            for (const auto &f : k.fields) {
                if (f.type.is_sequence) {
                    if (seq_ok(f.type)) {
                        s += indent(px_seq_field(k, f));
                    }
                    continue; // never hand pybind the casterless foreign type
                }
                if (!px_field_ok(f)) {
                    // A non-copyable member object of a BOUND class becomes a
                    // reference property (methods win on a name clash — e.g. a
                    // manifest extension already named like the field).
                    bool clashes = false;
                    for (const auto &m : k.methods) {
                        clashes = clashes || m.name == f.name;
                    }
                    if (f.type.kind == "object" && px_is_bound_class(f.type.object, c) &&
                        !clashes) {
                        s += indent(expanded_member_object(k, f));
                    }
                    continue; // anything else non-copyable — see px_copyable
                }
                s += indent(expanded_field(k, f));
            }
            for (const auto &m : k.methods) {
                if (seq_touches(m)) {
                    // Foreign sequence in the signature: adapter or nothing —
                    // the member-pointer path would hand pybind the casterless
                    // foreign type (and an overloaded set is fine here, see
                    // px_seq_method).
                    if (seq_adaptable(m) && px_seq_rest_ok(m)) {
                        s += indent(px_seq_method(k, m));
                    }
                    continue;
                }
                if (!px_method_ok(m)) {
                    continue; // signature the emitted pybind line could not compile
                }
                s += indent(expanded_method(k, m));
            }
            s += "    }\n";
            return s;
        }

        inline std::string python_expanded_source(const GenContext &c) {
            std::string body;
            for (const auto &e : c.enums) {
                body += expanded_enum(e);
            }
            for (const auto &k : c.classes) {
                body += expanded_class(k, c);
            }
            for (const auto &f : c.functions) {
                GenMethod probe; // free functions go through the same gates
                probe.ret    = f.ret;
                probe.params = f.params;
                if (seq_touches(probe)) {
                    if (seq_adaptable(probe) && px_seq_rest_ok(probe)) {
                        const PxSeqSig sig = px_seq_sig(f.params, {});
                        std::string body2 = sig.pre;
                        const std::string call = f.qualified + "(" + sig.args + ")";
                        if (f.ret.is_sequence) {
                            body2 += "        auto &&r = " + call + ";\n";
                            body2 += "        return " + seq_from_expr(f.ret, "r") + ";\n";
                        } else if (f.ret.kind == "void") {
                            body2 += "        " + call + ";\n";
                        } else {
                            body2 += "        return " + call + ";\n";
                        }
                        body += "    m.def(\"" + f.name + "\", [](" + sig.decls + ") {\n" +
                                body2 + "    }" + doc_arg(f.doc) + ");\n";
                    }
                    continue;
                }
                if (!px_method_ok(probe)) {
                    continue;
                }
                body += "    m.def(\"" + f.name + "\", &" + f.qualified + doc_arg(f.doc) + ");\n";
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += expanded_includes(c);
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += "\nnamespace py = pybind11;\n";
            out += trampolines_of(c); // reflection-free; empty when no virtuals
            out += "\nPYBIND11_MODULE(" + c.lib + ", m) {\n";
            out += "    m.doc() = \"Auto-generated (expanded) bindings for " + c.lib + ".\";\n";
            out += body;
            out += "}\n";
            return out;
        }

        inline std::string PythonExpandedBackend::render(const GenContext &c) const {
            return python_expanded_source(c);
        }

        inline void PythonExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "python-expanded";
            write_file(dir / "auto_pybind.cpp", python_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(PYX_CMAKE, c));
            write_file(dir / "README.md",
                       readme("python-expanded", c, subst(PYX_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
