// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// TypeScript generation backend — emits a `.d.ts` ambient module describing
// the bound classes (a companion to the node / wasm runtime bindings). This
// is a *pure-data* backend: it consumes the reflection IR that `generate`
// erases into GenClass (fields / methods / ctors) and renders text — no C++
// is compiled. Included by inline/generate.hxx.

#pragma once

namespace rosetta {
    namespace gen_detail {

        // Render a neutral GenType as a TypeScript type expression. A class /
        // enum reference resolves against the bound-class list so it names the
        // EXPOSED class (manifest "expose" may rename it; two bound classes may
        // even share an unqualified C++ identifier). Unresolved objects keep the
        // reflected identifier, matching the previous behavior.
        inline std::string ts_type(const GenType &t, const GenContext &c) {
            if (t.kind == "number") {
                return "number";
            }
            if (t.kind == "boolean") {
                return "boolean";
            }
            if (t.kind == "string") {
                return "string";
            }
            if (t.kind == "void") {
                return "void";
            }
            // A shared_ptr is, to a script, the object it points at — the
            // reference count is a C++-side detail. Declaring "shared_ptr" (the
            // literal identifier the IR carries in `object`) would name a type
            // the .d.ts never defines.
            if (t.is_shared_ptr && !t.element.empty()) {
                return ts_type(t.element.front(), c);
            }
            if (t.kind == "object" || t.kind == "enum") {
                if (t.object.empty()) {
                    return "any";
                }
                for (const auto &k : c.classes) {
                    if (t.object_qualified.empty() ? (k.name == t.object)
                                                   : (qualified_of(k) == t.object_qualified)) {
                        return exposed_of(k);
                    }
                }
                return t.object;
            }
            if (t.kind == "vector") {
                return (t.element.empty() ? std::string("any")
                                          : ts_type(t.element.front(), c)) +
                       "[]";
            }
            if (is_adapted(t) && !t.element.empty()) {
                // A trait-registered foreign container marshals as an array of
                // its element in the opted-in runtime backends — and a matrix
                // as an array of those rows.
                return ts_type(t.element.front(), c) + (t.is_matrix ? "[][]" : "[]");
            }
            return "any"; // unknown (e.g. std::function, unsupported types)
        }

        // Out-parameters (manifest "out_params") are not arguments: the caller
        // receives them, so they leave the parameter list and join the return.
        inline std::string ts_params(const std::vector<GenParam> &ps, const GenContext &c) {
            std::vector<std::string> parts;
            for (const auto &p : ps) {
                if (is_out_param(p)) {
                    continue;
                }
                parts.push_back(p.name + ": " + ts_type(p.type, c));
            }
            return join(parts, ", ");
        }

        // The declared return: the type itself normally, and a TUPLE when the
        // signature has out-parameters — `[boolean, number[], number]` for
        // `bool get_doubles(const string&, vector<double>&, index_t&)`, matching
        // the array node and wasm hand back and the multiple values Lua does.
        inline std::string ts_return(const GenType &ret, const std::vector<GenParam> &ps,
                                     const GenContext &c) {
            std::vector<std::string> parts;
            if (ret.kind != "void") {
                parts.push_back(ts_type(ret, c));
            }
            for (const auto &p : ps) {
                if (is_out_param(p)) {
                    parts.push_back(ts_type(p.type, c));
                }
            }
            if (parts.empty()) {
                return "void";
            }
            if (parts.size() == 1 && !ret.kind.empty() && ret.kind != "void") {
                return parts[0]; // no out-parameters: unchanged
            }
            return "[" + join(parts, ", ") + "]";
        }

        inline void TypeScriptBackend::emit(const GenContext &c) const {
            std::string out = "// Generated by rosetta::generate — do not edit by hand.\n";
            out += "declare module \"" + c.lib + "\" {\n";

            for (const auto &e : c.enums) {
                out += "    export enum " + exposed_of(e) + " {\n";
                for (const auto &v : e.values) {
                    out += "        " + v.name + " = " + std::to_string(v.value) + ",\n";
                }
                out += "    }\n";
            }

            for (const auto &k : c.classes) {
                out += "    export class " + exposed_of(k) + " {\n";

                for (const auto &ct : k.ctors) {
                    out += "        constructor(" + ts_params(ct, c) + ");\n";
                }

                for (const auto &f : k.fields) {
                    if (is_adapted(f.type) && !adapt_ok(f.type)) {
                        continue; // not adaptable — the runtime backends skip it
                    }
                    if (f.type.kind == "object" &&
                        !(f.type.copy_constructible && f.type.copy_assignable)) {
                        // A non-copyable member object of a BOUND class is a
                        // read-only member-object property in the runtime
                        // backends (mesh.vertices aliasing the real store);
                        // anything else non-copyable stays hidden.
                        bool bound = false;
                        for (const auto &kk : c.classes) {
                            bound = bound || (f.type.object_qualified.empty()
                                                  ? kk.name == f.type.object
                                                  : qualified_of(kk) == f.type.object_qualified);
                        }
                        bool clashes = false;
                        for (const auto &m : k.methods) {
                            clashes = clashes || m.name == f.name;
                        }
                        if (bound && !clashes) {
                            if (!f.doc.empty()) {
                                out += "        /** " + f.doc + " */\n";
                            }
                            out += "        readonly " + f.name + ": " + ts_type(f.type, c) + ";\n";
                        }
                        continue;
                    }
                    if (!f.doc.empty()) {
                        out += "        /** " + f.doc + " */\n";
                    }
                    out += "        " + std::string(f.is_readonly ? "readonly " : "") + f.name +
                           ": " + ts_type(f.type, c) + ";\n";
                }

                for (const auto &m : k.methods) {
                    // Same visibility rule as the runtime backends: a
                    // non-copyable class return or a non-copyable by-value
                    // parameter is skipped there, so don't declare it here
                    // either. A signature touching a foreign sequence follows
                    // the adapter rule: declared iff adaptable, hidden
                    // otherwise.
                    //
                    // Overloads follow the NODE runtime rather than what
                    // TypeScript could express. TypeScript does support
                    // declaration overloads, but this .d.ts describes the N-API
                    // module, which binds only the first-declared entry — so
                    // declaring the others would promise the caller a method
                    // that is not there, which is worse than not declaring it.
                    if (!coverage::emit_overload(coverage::overloads::first_only, "typescript", k,
                                                 m)) {
                        continue;
                    }
                    bool visible;
                    if (seq_touches(m)) {
                        visible = seq_adaptable(m);
                    } else {
                        visible = !(m.ret.kind == "object" && !m.ret.copy_constructible);
                    }
                    for (const auto &p : m.params) {
                        visible = visible && !(p.type.kind == "object" && !p.is_ref &&
                                               !p.type.copy_constructible);
                    }
                    if (!visible) {
                        continue;
                    }
                    if (!m.doc.empty()) {
                        out += "        /** " + m.doc + " */\n";
                    }
                    out += "        " + std::string(m.is_static ? "static " : "") + m.name + "(" +
                           ts_params(m.params, c) + "): " + ts_return(m.ret, m.params, c) + ";\n";
                }

                out += "    }\n";
            }

            for (const auto &f : c.functions) {
                if (!f.doc.empty()) {
                    out += "    /** " + f.doc + " */\n";
                }
                out += "    export function " + f.name + "(" + ts_params(f.params, c) +
                       "): " + ts_return(f.ret, f.params, c) + ";\n";
            }

            out += "}\n";
            write_file(c.out_dir / "typescript" / (c.lib + ".d.ts"), out);
        }

    } // namespace gen_detail
} // namespace rosetta
