// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// TypeScript generation backend — emits a `.d.ts` ambient module describing
// the bound classes (a companion to the node / wasm runtime bindings). This
// is a *pure-data* backend: it consumes the reflection IR that `generate`
// erases into GenClass (fields / methods / ctors) and renders text — no C++
// is compiled. Included by inline/generate.hxx.

#pragma once

namespace rosetta {
    namespace gen_detail {

        // Render a neutral GenType as a TypeScript type expression. A class /
        // enum reference resolves against the bound-class list so it names the
        // EXPOSED class (manifest "expose" may rename it; two bound classes may
        // even share an unqualified C++ identifier). Unresolved objects keep the
        // reflected identifier, matching the previous behavior.
        inline std::string ts_type(const GenType &t, const GenContext &c) {
            if (t.kind == "number") {
                return "number";
            }
            if (t.kind == "boolean") {
                return "boolean";
            }
            if (t.kind == "string") {
                return "string";
            }
            if (t.kind == "void") {
                return "void";
            }
            if (t.kind == "object" || t.kind == "enum") {
                if (t.object.empty()) {
                    return "any";
                }
                for (const auto &k : c.classes) {
                    if (t.object_qualified.empty() ? (k.name == t.object)
                                                   : (qualified_of(k) == t.object_qualified)) {
                        return exposed_of(k);
                    }
                }
                return t.object;
            }
            if (t.kind == "vector") {
                return (t.element.empty() ? std::string("any")
                                          : ts_type(t.element.front(), c)) +
                       "[]";
            }
            if (t.is_sequence && !t.element.empty()) {
                // A trait-registered foreign sequence marshals as an array of
                // its element in the opted-in runtime backends.
                return ts_type(t.element.front(), c) + "[]";
            }
            return "any"; // unknown (e.g. std::function, unsupported types)
        }

        inline std::string ts_params(const std::vector<GenParam> &ps, const GenContext &c) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                if (i) {
                    s += ", ";
                }
                s += ps[i].name + ": " + ts_type(ps[i].type, c);
            }
            return s;
        }

        inline void TypeScriptBackend::emit(const GenContext &c) const {
            std::string out = "// Generated by rosetta::generate — do not edit by hand.\n";
            out += "declare module \"" + c.lib + "\" {\n";

            for (const auto &e : c.enums) {
                out += "    export enum " + e.name + " {\n";
                for (const auto &v : e.values) {
                    out += "        " + v.name + " = " + std::to_string(v.value) + ",\n";
                }
                out += "    }\n";
            }

            for (const auto &k : c.classes) {
                out += "    export class " + exposed_of(k) + " {\n";

                for (const auto &ct : k.ctors) {
                    out += "        constructor(" + ts_params(ct, c) + ");\n";
                }

                for (const auto &f : k.fields) {
                    if (f.type.is_sequence && !seq_ok(f.type)) {
                        continue; // not adaptable — the runtime backends skip it
                    }
                    if (f.type.kind == "object" &&
                        !(f.type.copy_constructible && f.type.copy_assignable)) {
                        // A non-copyable member object of a BOUND class is a
                        // read-only member-object property in the runtime
                        // backends (mesh.vertices aliasing the real store);
                        // anything else non-copyable stays hidden.
                        bool bound = false;
                        for (const auto &kk : c.classes) {
                            bound = bound || (f.type.object_qualified.empty()
                                                  ? kk.name == f.type.object
                                                  : qualified_of(kk) == f.type.object_qualified);
                        }
                        bool clashes = false;
                        for (const auto &m : k.methods) {
                            clashes = clashes || m.name == f.name;
                        }
                        if (bound && !clashes) {
                            if (!f.doc.empty()) {
                                out += "        /** " + f.doc + " */\n";
                            }
                            out += "        readonly " + f.name + ": " + ts_type(f.type, c) + ";\n";
                        }
                        continue;
                    }
                    if (!f.doc.empty()) {
                        out += "        /** " + f.doc + " */\n";
                    }
                    out += "        " + std::string(f.is_readonly ? "readonly " : "") + f.name +
                           ": " + ts_type(f.type, c) + ";\n";
                }

                for (const auto &m : k.methods) {
                    // Same visibility rule as the runtime backends: a
                    // non-copyable class return or a non-copyable by-value
                    // parameter is skipped there, so don't declare it here
                    // either. An overload set IS declared — the runtime
                    // backends bind its surviving (first-declared) entry via
                    // an explicit-signature cast / a by-name adapter. A
                    // signature touching a foreign sequence follows the
                    // adapter rule: declared iff adaptable, hidden otherwise.
                    bool visible;
                    if (seq_touches(m)) {
                        visible = seq_adaptable(m);
                    } else {
                        visible = !(m.ret.kind == "object" && !m.ret.copy_constructible);
                    }
                    for (const auto &p : m.params) {
                        visible = visible && !(p.type.kind == "object" && !p.is_ref &&
                                               !p.type.copy_constructible);
                    }
                    if (!visible) {
                        continue;
                    }
                    if (!m.doc.empty()) {
                        out += "        /** " + m.doc + " */\n";
                    }
                    out += "        " + std::string(m.is_static ? "static " : "") + m.name + "(" +
                           ts_params(m.params, c) + "): " + ts_type(m.ret, c) + ";\n";
                }

                out += "    }\n";
            }

            for (const auto &f : c.functions) {
                if (!f.doc.empty()) {
                    out += "    /** " + f.doc + " */\n";
                }
                out += "    export function " + f.name + "(" + ts_params(f.params, c) +
                       "): " + ts_type(f.ret, c) + ";\n";
            }

            out += "}\n";
            write_file(c.out_dir / "typescript" / (c.lib + ".d.ts"), out);
        }

    } // namespace gen_detail
} // namespace rosetta
