// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) embind backend. Included by inline/generate.hxx
// after wasm_backend.h and after python_expanded_backend.h (whose qualify_std()
// it reuses), plus the shared render helpers (subst / num_str / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // A stock-emsdk CMake: C++17, plain emscripten, the user's include dir
        // only. No clang-p2996, no -freflection/-fannotation-attributes, no
        // rosetta include dir.
        constexpr std::string_view WASMX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# These bindings are plain embind: NO C++26, NO reflection, NO rosetta headers.
# Configure with a stock emsdk:  emcmake cmake -S . -B build && cmake --build build
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

if(NOT EMSCRIPTEN)
    message(FATAL_ERROR "Configure via `emcmake cmake ...` (a stock emsdk, no fork needed).")
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

{{USER_ENABLE_C}}add_executable({{LIB}} auto_emscripten.cpp{{USER_SOURCES}})

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}){{USER_LIB_WASM_BLOCK}}

target_link_options({{LIB}} PRIVATE
    --bind -sMODULARIZE=1 -sEXPORT_NAME=createModule
    -sENVIRONMENT=node,web -sALLOW_MEMORY_GROWTH=1 -sDISABLE_EXCEPTION_CATCHING=0
    # A generated demo may mount a real directory via NODEFS and drive libc fopen()
    # through it. An embind-only module strips the JS filesystem as unused, so force
    # it in and export the FS/NODEFS runtime objects (M.FS, M.NODEFS).
    -sFORCE_FILESYSTEM=1
    -sEXPORTED_RUNTIME_METHODS=FS,NODEFS
    -lnodefs.js){{USER_DEFS_BLOCK}}

set_target_properties({{LIB}} PROPERTIES SUFFIX ".js")
{{OUT_DIR_BLOCK_WASM}}
)CMK";

        // Build section appended to the generated README. Unlike the thin wasm
        // backend, WASMX_CMAKE has no reflection flags and no rosetta include
        // dir, so any stock emsdk builds it; the FS/NODEFS note traces to the
        // -sFORCE_FILESYSTEM / -sEXPORTED_RUNTIME_METHODS link options above.
        constexpr std::string_view WASMX_README_BUILD = R"MD(## Build

Plain embind: any stock emsdk (activated in the shell) — no C++26, no
reflection toolchain, no rosetta headers. The CMakeLists refuses to configure
without `emcmake`.

```sh
emcmake cmake -S . -B build
cmake --build build
```

Produces `build/{{LIB}}.js` + `build/{{LIB}}.wasm`: a MODULARIZE'd factory
named `createModule`, for both node and the web. The JS filesystem is forced in
and exported (`M.FS`, `M.NODEFS`) so a demo can mount a real directory.

## Use

```sh
node -e "require('./build/{{LIB}}.js')().then(M => console.log(Object.keys(M)))"
```
)MD";

        // Emitted verbatim into auto_emscripten.cpp: converts an emscripten::val
        // to/from C++ and wraps a JS function into a std::function of any
        // val-convertible signature. `to_val`/`from_val` handle scalars, strings,
        // std::array (element-wise) and registered types (embind's built-in
        // val↔type). `make_fn` captures the JS function in the returned closure;
        // the C++ side invokes it synchronously (valid for calls made during a
        // JS-initiated call, e.g. a solver.run()).
        constexpr std::string_view WASMX_CALLBACK_HELPER =
            R"CB(
namespace rosetta_wx {
    template <typename T> struct is_std_array : std::false_type {};
    template <typename U, std::size_t N> struct is_std_array<std::array<U, N>> : std::true_type {};

    template <typename T> emscripten::val to_val(const T &x) {
        if constexpr (is_std_array<std::remove_cvref_t<T>>::value) {
            emscripten::val a = emscripten::val::array();
            for (std::size_t i = 0; i < x.size(); ++i) a.set(i, to_val(x[i]));
            return a;
        } else {
            return emscripten::val(x);
        }
    }
    template <typename T> T from_val(const emscripten::val &v) {
        if constexpr (is_std_array<T>::value) {
            T out{};
            for (std::size_t i = 0; i < out.size(); ++i)
                out[i] = from_val<typename T::value_type>(v[i]);
            return out;
        } else {
            return v.template as<T>();
        }
    }
    template <typename F> struct fn_wrap;
    template <typename R, typename... A> struct fn_wrap<std::function<R(A...)>> {
        static std::function<R(A...)> make(emscripten::val f) {
            return [f](A... args) -> R {
                emscripten::val r = f(to_val<std::remove_cvref_t<A>>(args)...);
                if constexpr (std::is_void_v<R>) { (void)r; }
                else { return from_val<std::remove_cvref_t<R>>(r); }
            };
        }
    };
    template <typename F> F make_fn(emscripten::val f) { return fn_wrap<F>::make(f); }
}
)CB";

        // A compilable C++ spelling for an IR type. Mirrors cpp_type_of for the
        // kinds embind needs to name explicitly (vector element types,
        // read-only/range setter parameters). Member pointers cover everything
        // else, so this is only reached for those few spots.
        inline std::string wx_cpp_type(const GenType &t) {
            if (t.kind == "vector") {
                return "std::vector<" +
                       (t.element.empty() ? std::string("emscripten::val")
                                          : wx_cpp_type(t.element.front())) +
                       ">";
            }
            if (t.kind == "object" || t.kind == "enum") {
                // Qualified when known: the unqualified identifier is ambiguous
                // once two bound namespaces declare it (the "expose" case).
                return t.object_qualified.empty() ? t.object : t.object_qualified;
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "void") {
                return "void";
            }
            if (t.kind == "number") {
                return t.spelling.empty() ? "double" : t.spelling;
            }
            return qualify_std(t.spelling);
        }

        // Can embind marshal this type? Scalars, bool, string, enums, user
        // objects, and vectors of marshalable types qualify; std::function and
        // anything else the IR tagged "unknown" do not.
        // Is the IR type one of the bound classes? Compared by qualified
        // spelling when the IR carries it (two bound classes may share an
        // unqualified identifier — the "expose" rename case). A raw pointer is
        // only marshalable when its pointee is itself registered with embind.
        inline bool wx_is_bound(const GenType &t, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (t.object_qualified.empty() ? (k.name == t.object)
                                               : (qualified_of(k) == t.object_qualified)) {
                    return true;
                }
            }
            return false;
        }

        // `.smart_ptr<std::shared_ptr<T>>("T_sp")` for a class the module hands
        // out inside a shared_ptr, and nothing at all for one it does not —
        // embind needs the pointee registered with a matching smart_ptr before
        // it will convert one, exactly as pybind11 needs a holder. The name is
        // embind's own registry key, not something JS ever types, so it only has
        // to be unique: the exposed class name plus a suffix.
        inline std::string wx_smart_ptr_seg(const GenClass &k, const GenContext &c) {
            const auto        need = shared_pointees(c);
            const std::string kq   = qualified_of(k);
            if (std::find(need.begin(), need.end(), kq) == need.end()) {
                return {};
            }
            return "\n        .smart_ptr<std::shared_ptr<" + kq + ">>(\"" + exposed_of(k) +
                   "_sp\")";
        }

        inline bool wx_marshalable(const GenType &t, const GenContext &c) {
            // Bare raw pointer to a bound class: embind handles it via
            // allow_raw_pointers (non-owning), returning/accepting a JS handle to
            // the C++ object.
            if (t.is_pointer) {
                return wx_is_bound(t, c);
            }
            if (t.kind == "unknown") {
                return false;
            }
            // std::shared_ptr<T>: embind marshals one natively once T is
            // registered with a matching `.smart_ptr<std::shared_ptr<T>>` (see
            // wx_smart_ptr_seg) — the JS side gets an ordinary handle to T that
            // keeps the C++ object alive. The question to ask is about the
            // POINTEE: `object` here is the literal identifier "shared_ptr",
            // which is bound nowhere. Must precede the "object" branch below,
            // which a shared_ptr's kind also satisfies.
            if (t.is_shared_ptr) {
                return wx_is_bound(shared_pointee(t), c);
            }
            // A by-value class is marshalable only when it is itself registered
            // (a bound class_). An unregistered/incomplete object — std::array,
            // std::initializer_list, a forward-declared helper like ModelRegions —
            // has no embind type and would abort the build.
            if (t.kind == "object") {
                return wx_is_bound(t, c);
            }
            if (t.kind == "vector") {
                if (t.element.empty()) {
                    return true;
                }
                // A vector *of* raw pointers would need register_vector<T*>, which
                // embind does not support — keep skipping those.
                if (t.element.front().is_pointer) {
                    return false;
                }
                return wx_marshalable(t.element.front(), c);
            }
            return true;
        }

        // Can a value of this type ride across the boundary INSIDE a JS callback,
        // i.e. through the emitted rosetta_wx::to_val / from_val helpers? That set
        // is: scalars, bool, strings, enums, std::array (element-wise), vectors of
        // such, and registered classes (embind val ↔ registered type). Raw
        // pointers, nested callbacks, and unbound by-value objects are out — so a
        // callback taking e.g. `Triangle*` or `Eigen::VectorXd&` stays skipped.
        inline bool wx_val_convertible(const GenType &t, const GenContext &c) {
            if (t.is_pointer || t.is_callback) {
                return false;
            }
            if (t.kind == "number" || t.kind == "boolean" || t.kind == "string" ||
                t.kind == "enum") {
                return true;
            }
            if (t.kind == "vector") {
                return !t.element.empty() && !t.element.front().is_pointer &&
                       wx_val_convertible(t.element.front(), c);
            }
            if (t.kind == "object") {
                // display_string_of drops the std:: prefix (see qualify_std), so a
                // std::array spelling arrives as "array<...>" — qualify then test.
                if (qualify_std(t.spelling).rfind("std::array<", 0) == 0) {
                    return true; // handled element-wise by the rosetta_wx helper
                }
                return wx_is_bound(t, c); // registered class ↔ emscripten::val
            }
            return false;
        }

        // A std::function param is bindable via an emscripten::val adapter iff its
        // whole signature is val-convertible (return may additionally be void).
        inline bool wx_callback_convertible(const GenType &t, const GenContext &c) {
            if (!t.is_callback || t.callback_sig.empty()) {
                return false;
            }
            const GenType &ret = t.callback_sig.front();
            if (!(ret.kind == "void" || wx_val_convertible(ret, c))) {
                return false;
            }
            for (std::size_t i = 1; i < t.callback_sig.size(); ++i) {
                if (!wx_val_convertible(t.callback_sig[i], c)) {
                    return false;
                }
            }
            return true;
        }

        // A parameter is bindable when embind marshals it directly, OR it is a
        // callback we can wrap with an emscripten::val adapter.
        inline bool wx_param_ok(const GenType &t, const GenContext &c) {
            return wx_marshalable(t, c) || (t.is_callback && wx_callback_convertible(t, c));
        }

        inline bool wx_params_have_callback(const std::vector<GenParam> &params) {
            for (const auto &p : params) {
                if (p.type.is_callback) {
                    return true;
                }
            }
            return false;
        }

        // A signature that names a raw pointer needs the allow_raw_pointers policy.
        inline bool wx_type_has_raw_ptr(const GenType &t) {
            if (t.is_pointer) {
                return true;
            }
            if (t.kind == "vector" && !t.element.empty()) {
                return wx_type_has_raw_ptr(t.element.front());
            }
            return false;
        }

        inline bool wx_method_has_raw_ptr(const GenMethod &m) {
            if (wx_type_has_raw_ptr(m.ret)) {
                return true;
            }
            for (const auto &p : m.params) {
                if (wx_type_has_raw_ptr(p.type)) {
                    return true;
                }
            }
            return false;
        }

        // --- Foreign containers (rosetta::is_sequence / is_matrix) -------------
        // A method touching a trait-registered sequence binds through a lambda
        // adapter whose boundary is std::vector<element> (registered above):
        // the adapter builds the foreign container before the call and flattens
        // a returned one after. A mutable `Seq&` parameter binds input-only
        // (the adapter's local is a real lvalue; mutations are discarded), and
        // an overload set whose surviving IR entry is the sequence one binds
        // too — the adapter calls by NAME with concrete arguments.
        inline bool wx_seq_rest_ok(const GenMethod &m, const GenContext &c) {
            if (!is_adapted(m.ret)) {
                if (m.ret.kind != "void" && !wx_marshalable(m.ret, c)) {
                    return false;
                }
                if (m.ret.kind == "object" && !m.ret.copy_constructible) {
                    return false;
                }
            }
            for (const auto &p : m.params) {
                if (is_adapted(p.type) || is_out_param(p)) {
                    continue;
                }
                if (p.type.is_callback) {
                    return false; // keep the two adapter mechanisms apart
                }
                if (!wx_param_ok(p.type, c)) {
                    return false;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false;
                }
                if (p.type.kind != "object" && p.is_mutable_ref) {
                    return false;
                }
            }
            return true;
        }
        inline bool wx_seq_eligible(const GenMethod &m, const GenContext &c) {
            return seq_adaptable(m) && wx_seq_rest_ok(m, c);
        }

        // The adapter's (param decls, pre-call statements, call args). Non-seq
        // params keep their exact spellings (param_cpp) when available.
        struct WxSeqSig {
            std::string           decls;
            std::string           pre;
            std::string           args;
            std::vector<OutParam> outs; // manifest "out_params" — joined to the return
        };
        inline WxSeqSig wx_seq_sig(const std::vector<GenParam>    &params,
                                   const std::vector<std::string> &param_cpp) {
            WxSeqSig   o;
            const bool exact = param_cpp.size() == params.size();
            // Declarations and arguments are collected separately: an
            // out-parameter contributes an ARGUMENT (its local) but no
            // DECLARATION.
            std::vector<std::string> decls, args;
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                const GenType    &t  = params[j].type;
                if (is_out_param(params[j])) {
                    const std::string on = "out" + std::to_string(j);
                    o.pre += "            " + out_local_cpp(t) + " " + on + "{};\n";
                    args.push_back(on);
                    o.outs.push_back({on, out_expr(t, on)});
                    continue;
                }
                if (is_adapted(t)) {
                    const std::string sn = adapt_local(t, j);
                    decls.push_back(adapt_boundary_cpp(t) + " " + an);
                    o.pre += adapt_decl_stmts(t, an, sn, "            ");
                    args.push_back(sn);
                } else if (exact) {
                    decls.push_back(qualify_objects(qualify_std(param_cpp[j]), t) + " " + an);
                    args.push_back(an);
                } else if (t.kind == "object") {
                    decls.push_back(wx_cpp_type(t) + " &" + an);
                    args.push_back(an);
                } else {
                    decls.push_back(wx_cpp_type(t) + " " + an);
                    args.push_back(an);
                }
            }
            o.decls = join(decls, ", ");
            o.args  = join(args, ", ");
            return o;
        }

        // The lambda body: conversions, the call, the (possibly flattened) return.
        inline std::string wx_seq_body(const GenMethod &m, const WxSeqSig &sig,
                                       const std::string &call) {
            std::string body = sig.pre;
            if (!sig.outs.empty()) {
                // embind marshals no tuple, so the out-parameters come back as
                // an emscripten::val ARRAY — the same JS shape node hands out,
                // reached a different way.
                body += out_return_stmts(m, sig.outs, call, "            ",
                                         OutStyle::val_array);
            } else if (is_adapted(m.ret)) {
                body += "            auto &&r = " + call + ";\n";
                body += "            return " + adapt_from_expr(m.ret, "r") + ";\n";
            } else if (m.ret.kind == "void") {
                body += "            " + call + ";\n";
            } else {
                body += "            return " + call + ";\n";
            }
            return body;
        }

        // Does this method hand out a REFERENCE to a bound class? embind's
        // toWireType copies a class return — including an lvalue-ref one — so
        // such a method is emitted as a lambda returning the ADDRESS, under
        // allow_raw_pointers: a non-owning handle to the real object, the same
        // borrowed-handle shape the member-object getters use. (As there, and
        // unlike pybind's reference_internal, nothing pins the parent: the
        // handle dangles if the owner dies first.)
        inline bool wx_alias_return(const GenMethod &m, const GenContext &c) {
            return m.ret_is_ref && m.ret.kind == "object" && !m.ret.is_shared_ptr &&
                   !m.is_static && !m.is_extension && wx_is_bound(m.ret, c);
        }

        inline bool wx_method_ok(const GenMethod &m, const GenContext &c) {
            // An overload set is fine here: the emitter always spells an
            // explicit static_cast to the exact signature, so the surviving
            // (first-declared) entry binds unambiguously.
            // An overload needs its exact signature spelled for the cast; a
            // type with no name of its own cannot be. See sig_spellable().
            if (m.is_overloaded && !sig_spellable(m)) {
                return false;
            }
            if (m.ret.kind != "void" && !wx_marshalable(m.ret, c)) {
                return false;
            }
            // embind's toWireType COPIES a class return (also for an lvalue-ref
            // return), so a non-copyable class return would not compile —
            // unless it is handed out as a borrowed handle instead
            // (wx_alias_return).
            if (m.ret.kind == "object" && !m.ret.copy_constructible && !wx_alias_return(m, c)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!wx_param_ok(p.type, c)) {
                    return false;
                }
                // A by-value class parameter copy-constructs; by-ref never does.
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false;
                }
                // Mutable ref to a NON-class type (std::string&, index_t&): an
                // out-parameter — embind's converted argument is a temporary,
                // which cannot bind to a non-const reference. Unless the
                // manifest declared it an output, in which case the adapter
                // above owns it and this method never reaches here.
                if (p.type.kind != "object" && p.is_mutable_ref && !is_out_param(p)) {
                    return false;
                }
            }
            return true;
        }

        // Can this field ride an embind .property()? Both accessors copy
        // (getter by value, setter by copy assignment), and the type must be
        // registered.
        inline bool wx_field_ok(const GenField &f, const GenContext &c) {
            if (!wx_marshalable(f.type, c)) {
                return false;
            }
            if (f.type.kind == "object") {
                return f.type.copy_constructible && (f.is_readonly || f.type.copy_assignable);
            }
            if (f.type.kind == "vector" && !f.type.element.empty()) {
                const GenType &e = f.type.element.front();
                if (e.kind == "object" && !e.copy_constructible) {
                    return false;
                }
            }
            return true;
        }

        // Emit the (lambda parameter decls, forwarded call args) for a parameter
        // list that may contain callbacks. A callback param is received as an
        // `emscripten::val` and wrapped into its std::function via the rosetta_wx
        // helper; every other param passes through with its exact C++ spelling.
        struct WxAdapterParams {
            std::string decls; // e.g. "emscripten::val arg0, bool arg1"
            std::string args;  // e.g. "rosetta_wx::make_fn<...>(arg0), arg1"
        };
        inline WxAdapterParams wx_adapter_params(const std::vector<std::string> &param_cpp,
                                                 const std::vector<GenParam>    &params) {
            WxAdapterParams a;
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                if (j) {
                    a.decls += ", ";
                    a.args += ", ";
                }
                if (params[j].type.is_callback) {
                    a.decls += "emscripten::val " + an;
                    a.args += "rosetta_wx::make_fn<" +
                              qualify_objects(qualify_std(params[j].type.spelling),
                                              params[j].type) +
                              ">(" + an + ")";
                } else {
                    a.decls += qualify_objects(qualify_std(param_cpp[j]), params[j].type) +
                               " " + an;
                    a.args += an;
                }
            }
            return a;
        }

        // Accumulate the distinct vector types reachable from the surface, so a
        // register_vector<element>() can be emitted for each. Keyed by the
        // element's C++ spelling to dedup (vector<int> vs vector<double>).
        inline void wx_collect_vectors(const GenType &t, std::vector<GenType> &out) {
            if (t.is_callback) {
                for (const auto &s : t.callback_sig) {
                    wx_collect_vectors(s, out); // a vector inside a callback still needs registering
                }
                return;
            }
            if (t.is_path) {
                return; // the boundary is a std::string — nothing to register
            }
            if (is_adapted(t) && adapt_ok(t)) {
                // A foreign sequence marshals through std::vector<element> —
                // that boundary vector needs registering like any other. A
                // matrix marshals through a vector OF those, so it registers
                // both levels (the recursion below walks into the inner one).
                GenType v;
                v.kind    = "vector";
                v.element = t.element;
                if (t.is_matrix) {
                    GenType rows;
                    rows.kind = "vector";
                    rows.element.push_back(v);
                    wx_collect_vectors(rows, out);
                    return;
                }
                wx_collect_vectors(v, out);
                return;
            }
            if (t.kind == "vector" && !t.element.empty()) {
                const std::string key = wx_cpp_type(t.element.front());
                bool              seen = false;
                for (const auto &v : out) {
                    if (wx_cpp_type(v.element.front()) == key) {
                        seen = true;
                        break;
                    }
                }
                if (!seen) {
                    out.push_back(t);
                }
                wx_collect_vectors(t.element.front(), out); // vector<vector<...>>
            }
        }

        inline std::vector<GenType> wx_all_vectors(const GenContext &c) {
            std::vector<GenType> out;
            for (const auto &k : c.classes) {
                for (const auto &f : k.fields) {
                    wx_collect_vectors(f.type, out);
                }
                for (const auto &m : k.methods) {
                    if (!wx_method_ok(m, c) && !wx_seq_eligible(m, c)) {
                        continue;
                    }
                    wx_collect_vectors(m.ret, out);
                    for (const auto &p : m.params) {
                        wx_collect_vectors(p.type, out);
                    }
                }
                for (const auto &params : k.ctors) {
                    bool ok = true;
                    for (const auto &p : params) {
                        ok = ok && wx_param_ok(p.type, c);
                    }
                    if (!ok) {
                        continue;
                    }
                    for (const auto &p : params) {
                        wx_collect_vectors(p.type, out);
                    }
                }
            }
            for (const auto &f : c.functions) {
                wx_collect_vectors(f.ret, out);
                for (const auto &p : f.params) {
                    wx_collect_vectors(p.type, out);
                }
            }
            return out;
        }

        // A JS-visible registry name for a vector type: "vector_<element>" with
        // non-identifier characters flattened to '_'.
        inline std::string wx_vector_name(const GenType &vt) {
            std::string s = "vector_" + wx_cpp_type(vt.element.front());
            for (char &ch : s) {
                const bool ok = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                                (ch >= '0' && ch <= '9') || ch == '_';
                if (!ok) {
                    ch = '_';
                }
            }
            return s;
        }

        // One enum: emscripten::enum_<E>("E").value("A", E::A)...;
        inline std::string wx_enum(const GenEnum &e) {
            const std::string eq = qualified_of(e);
            std::string       s = "    emscripten::enum_<" + eq + ">(\"" + exposed_of(e) + "\")";
            for (const auto &v : e.values) {
                s += "\n        .value(\"" + v.name + "\", " + eq + "::" + v.name + ")";
            }
            s += ";\n";
            return s;
        }

        // One field as an embind chain segment (leading '.', no newline). Mirrors
        // EmscriptenVisitor::field: readonly -> getter + throwing setter; range +
        // arithmetic -> validating setter; otherwise the member-pointer property.
        inline std::string wx_field_segment(const GenClass &k, const GenField &f) {
            const std::string self = qualified_of(k);
            if (f.is_readonly) {
                const std::string ty = wx_cpp_type(f.type);
                return ".property(\"" + f.name + "\",\n            +[](const " + self +
                       " &s) { return s." + f.name + "; },\n            +[](" + self + " &, " + ty +
                       ") { throw std::runtime_error(\"" + f.name + " is read-only\"); })";
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string ty = wx_cpp_type(f.type);
                const std::string lo = num_str(f.range.min);
                const std::string hi = num_str(f.range.max);
                return ".property(\"" + f.name + "\",\n            +[](const " + self +
                       " &s) { return s." + f.name + "; },\n            +[](" + self + " &s, " + ty +
                       " v) {\n                if (v < " + lo + " || v > " + hi +
                       ")\n                    throw std::runtime_error(\"" + f.name +
                       " out of range [" + lo + ", " + hi + "]\");\n                s." + f.name +
                       " = v;\n            })";
            }
            return ".property(\"" + f.name + "\", &" + self + "::" + f.name + ")";
        }

        inline std::string wx_class(const GenClass &k, const GenContext &c) {
            // A class whose destructor is not public cannot be wrapped: every
            // runtime backend destroys what it holds. Skip it with a note —
            // the alternative is a compile error inside the framework headers.
            if (!k.is_destructible) {
                std::fprintf(stderr,
                             "rosetta::%s: class '%s' has a non-public destructor "
                             "(ref-counted?) — skipped\n",
                             "wasm-expanded", k.name.c_str());
                return {};
            }

            std::vector<std::string> segs;
            // Qualified spelling for emitted C++, exposed name for the JS side —
            // see the "expose" rename notes in generate.h.
            const std::string kn = qualified_of(k);

            // First bound base, spelled with emscripten::base<> so embind wires up
            // the prototype chain and up-casts. embind supports single inheritance,
            // so only the first base that is itself bound is used.
            std::string base_arg;
            {
                for (const auto &b : k.bases) {
                    bool bound = false;
                    for (const auto &g : c.classes) {
                        if (qualified_of(g) == b) {
                            bound = true;
                            break;
                        }
                    }
                    if (bound) {
                        base_arg = ", emscripten::base<" + b + ">";
                        break;
                    }
                }
            }

            // Constructors (exact spellings, std::-qualified). ctor_param_cpp is
            // parallel to ctors, which carries the IR used for the skip check. An
            // abstract class cannot be constructed, so emit no constructors for it.
            bool                     saw_default = false;
            std::vector<std::size_t> seen_arities; // embind dispatches ctors by arity
            for (std::size_t i = 0; !k.is_abstract && i < k.ctor_param_cpp.size(); ++i) {
                const auto &ir      = k.ctors[i];
                bool        ok      = true;
                bool        raw_ptr = false;
                for (const auto &p : ir) {
                    ok = ok && wx_param_ok(p.type, c);
                    raw_ptr = raw_ptr || wx_type_has_raw_ptr(p.type);
                }
                if (!ok) {
                    continue;
                }
                const bool has_cb = wx_params_have_callback(ir);
                const auto &params = k.ctor_param_cpp[i];
                // embind resolves overloaded constructors by parameter COUNT only,
                // and throws at registration if two share an arity — so keep just
                // the first marshalable constructor of each arity.
                bool dup = false;
                for (std::size_t a : seen_arities) {
                    if (a == params.size()) {
                        dup = true;
                        break;
                    }
                }
                if (dup) {
                    continue;
                }
                seen_arities.push_back(params.size());
                if (params.empty()) {
                    saw_default = true;
                }
                if (has_cb) {
                    // A ctor taking a callback can't be spelled as .constructor<...>
                    // (embind has no type for std::function). Emit a factory lambda
                    // that receives the callback as an emscripten::val, wraps it, and
                    // heap-allocates the object (embind owns the returned pointer).
                    const WxAdapterParams ad = wx_adapter_params(params, ir);
                    segs.push_back(".constructor(+[](" + ad.decls + ") -> " + kn +
                                   " * {\n            return new " + kn + "(" + ad.args +
                                   ");\n        }, emscripten::allow_raw_pointers())");
                    continue;
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    std::string one = qualify_std(params[j]);
                    if (j < ir.size()) {
                        one = qualify_objects(std::move(one), ir[j].type);
                    }
                    args += (j ? ", " : "") + one;
                }
                const std::string policy = raw_ptr ? "emscripten::allow_raw_pointers()" : "";
                segs.push_back(".constructor<" + args + ">(" + policy + ")");
            }
            if (!saw_default && k.is_default_constructible) {
                segs.push_back(".constructor<>()");
            }

            for (const auto &f : k.fields) {
                if (is_adapted(f.type)) {
                    // Foreign sequence field: property copying through the
                    // boundary vector both ways (a member-pointer property
                    // would name the unregistered foreign type).
                    if (adapt_ok(f.type)) {
                        const std::string vt  = adapt_boundary_cpp(f.type);
                        const std::string get = "+[](const " + kn + " &s) { return " +
                                                adapt_from_expr(f.type, "s." + f.name) + "; }";
                        std::string set;
                        if (f.is_readonly) {
                            set = "+[](" + kn + " &, " + vt +
                                  ") { throw std::runtime_error(\"" + f.name +
                                  " is read-only\"); }";
                        } else {
                            set = "+[](" + kn + " &s, " + vt + " v) { s." + f.name +
                                  ".resize(v.size()); std::copy(v.begin(), v.end(), s." +
                                  f.name + ".begin()); }";
                        }
                        segs.push_back(".property(\"" + f.name + "\",\n            " + get +
                                       ",\n            " + set + ")");
                    }
                    continue;
                }
                if (!wx_field_ok(f, c)) {
                    // A non-copyable member object of a BOUND class becomes a
                    // borrowed-handle getter METHOD — embind properties copy,
                    // but a raw-pointer return (allow_raw_pointers) hands out
                    // a non-owning handle to the member living inside the
                    // parent: mesh.vertices().nb(). NOTE: unlike pybind's
                    // reference_internal, nothing pins the parent — the handle
                    // dangles if the parent is destroyed first.
                    bool clashes = false;
                    for (const auto &m : k.methods) {
                        clashes = clashes || m.name == f.name;
                    }
                    if (f.type.kind == "object" && wx_is_bound(f.type, c) && !clashes) {
                        segs.push_back(".function(\"" + f.name + "\", +[](" + kn +
                                       " &s) { return &s." + f.name +
                                       "; }, emscripten::allow_raw_pointers())");
                    }
                    continue; // anything else unmarshalable / non-copyable
                }
                segs.push_back(wx_field_segment(k, f));
            }
            for (const auto &m : k.methods) {
                // embind registers a method BY NAME: a second .function("f", …)
                // on the same class is not an overload, it is a duplicate
                // registration that throws BindingError when the module
                // initialises. Only the first-declared overload can bind; the
                // rest are recorded for the coverage report.
                if (!coverage::emit_overload(coverage::overloads::first_only, "wasm-expanded", k,
                                             m)) {
                    continue;
                }
                if (seq_touches(m)) {
                    // Foreign sequence in the signature: adapter or nothing
                    // (embind has no type for the foreign container).
                    if (!wx_seq_eligible(m, c)) {
                        coverage::note_skip("wasm-expanded", k, m, "sequence_not_adaptable",
                                            "a registered sequence in the signature has no "
                                            "std::vector boundary adapter for this backend");
                        continue;
                    }
                    const WxSeqSig sig = wx_seq_sig(m.params, m.param_cpp);
                    std::string    decls, call;
                    if (m.is_extension) {
                        decls = kn + " &self" +
                                (sig.decls.empty() ? "" : ", " + sig.decls);
                        call = m.ext_qualified + "(self" +
                               (sig.args.empty() ? "" : ", " + sig.args) + ")";
                    } else if (m.is_static) {
                        decls = sig.decls;
                        call  = kn + "::" + m.name + "(" + sig.args + ")";
                    } else {
                        decls = kn + " &self" +
                                (sig.decls.empty() ? "" : ", " + sig.decls);
                        call = "self." + m.name + "(" + sig.args + ")";
                    }
                    const std::string body = wx_seq_body(m, sig, call);
                    segs.push_back((m.is_static ? ".class_function(\"" : ".function(\"") +
                                   m.name + "\", +[](" + decls + ") {\n" + body +
                                   "        })");
                    coverage::note_bound("wasm-expanded", k, m);
                    continue;
                }
                if (!wx_method_ok(m, c)) {
                    coverage::note_skip("wasm-expanded", k, m, "unmarshalable_signature",
                                        "embind has no conversion for a type in this signature "
                                        "(e.g. a std::function parameter, or a pointer to an "
                                        "unbound class)");
                    continue; // unmarshalable signature (e.g. std::function param)
                }
                // A reference to a bound class: hand out the ADDRESS under
                // allow_raw_pointers — a borrowed handle to the real object,
                // the same shape the member-object getters use, where embind's
                // own conversion would copy.
                if (wx_alias_return(m, c)) {
                    std::string args, params;
                    const bool  exact = m.param_cpp.size() == m.params.size();
                    for (std::size_t j = 0; j < m.params.size(); ++j) {
                        const std::string an = "arg" + std::to_string(j);
                        params += ", " + (exact ? qualify_objects(qualify_std(m.param_cpp[j]),
                                                                  m.params[j].type)
                                                : wx_cpp_type(m.params[j].type)) +
                                  " " + an;
                        args += (args.empty() ? "" : ", ") + an;
                    }
                    segs.push_back(".function(\"" + m.name + "\", +[](" + kn + " &self" + params +
                                   ") { return &self." + m.name + "(" + args +
                                   "); }, emscripten::allow_raw_pointers())");
                    coverage::note_bound("wasm-expanded", k, m);
                    continue;
                }
                // Extension method: bind the free function directly — embind
                // treats a non-member whose first parameter is the class type
                // (by ref) as an instance method.
                if (m.is_extension) {
                    segs.push_back(".function(\"" + m.name + "\", &" + m.ext_qualified + ")");
                    coverage::note_bound("wasm-expanded", k, m);
                    continue;
                }
                if (wx_params_have_callback(m.params)) {
                    // A method taking a callback: bind a free-function-style lambda
                    // whose first arg is the receiver, converting the callback from
                    // an emscripten::val. embind's static member functions can't take
                    // a receiver this way, so a static callback method is left out.
                    if (m.is_static) {
                        coverage::note_skip("wasm-expanded", k, m, "static_callback_receiver",
                                            "embind cannot give a static member function the "
                                            "receiver argument the callback adapter needs");
                        continue;
                    }
                    const WxAdapterParams ad = wx_adapter_params(m.param_cpp, m.params);
                    const std::string     decls =
                        kn + " &self" + (ad.decls.empty() ? "" : ", " + ad.decls);
                    const std::string call = "self." + m.name + "(" + ad.args + ")";
                    const std::string body = (m.ret.kind == "void")
                                                 ? ("            " + call + ";\n")
                                                 : ("            return " + call + ";\n");
                    const std::string policy =
                        wx_method_has_raw_ptr(m) ? ", emscripten::allow_raw_pointers()" : "";
                    segs.push_back(".function(\"" + m.name + "\", +[](" + decls + ") {\n" + body +
                                   "        }" + policy + ")");
                    coverage::note_bound("wasm-expanded", k, m);
                    continue;
                }
                // Disambiguate the member-function pointer with an explicit cast to
                // the exact signature: a plain `&T::m` is ambiguous for an
                // overloaded method (embind then reports "no matching function").
                std::string args;
                for (std::size_t j = 0; j < m.param_cpp.size(); ++j) {
                    std::string one = qualify_std(m.param_cpp[j]);
                    if (j < m.params.size()) {
                        one = qualify_objects(std::move(one), m.params[j].type);
                    }
                    args += (j ? ", " : "") + one;
                }
                std::string quals;
                if (m.is_const) {
                    quals += " const";
                }
                if (m.is_noexcept) {
                    quals += " noexcept";
                }
                const std::string ret = qualify_objects(qualify_std(m.ret_cpp), m.ret);
                const std::string fp =
                    m.is_static ? (ret + " (*)(" + args + ")" + quals)
                                : (ret + " (" + kn + "::*)(" + args + ")" + quals);
                const std::string mp =
                    "static_cast<" + fp + ">(&" + kn + "::" + m.name + ")";
                // A raw pointer to a bound class needs the allow_raw_pointers policy.
                const std::string policy =
                    wx_method_has_raw_ptr(m) ? ", emscripten::allow_raw_pointers()" : "";
                segs.push_back((m.is_static ? ".class_function(\"" : ".function(\"") + m.name +
                               "\", " + mp + policy + ")");
                coverage::note_bound("wasm-expanded", k, m);
            }

            std::string s =
                "    emscripten::class_<" + kn + base_arg + ">(\"" + exposed_of(k) + "\")" +
                wx_smart_ptr_seg(k, c);
            if (segs.empty()) {
                return s + ";\n";
            }
            for (const auto &seg : segs) {
                s += "\n        " + seg;
            }
            s += ";\n";
            return s;
        }

        inline std::string wasm_expanded_source(const GenContext &c) {
            std::string body;
            for (const auto &e : c.enums) {
                body += wx_enum(e);
            }
            for (const auto &vt : wx_all_vectors(c)) {
                body += "    emscripten::register_vector<" + wx_cpp_type(vt.element.front()) +
                        ">(\"" + wx_vector_name(vt) + "\");\n";
            }
            for (const auto &k : c.classes) {
                body += wx_class(k, c);
            }
            for (const auto &f : c.functions) {
                GenMethod probe;
                probe.ret    = f.ret;
                probe.params = f.params;
                if (seq_touches(probe)) {
                    if (wx_seq_eligible(probe, c)) {
                        const WxSeqSig    sig  = wx_seq_sig(f.params, {});
                        const std::string call = fn_call_expr(f) + "(" + sig.args + ")";
                        body += "    emscripten::function(\"" + f.name + "\", +[](" +
                                sig.decls + ") {\n" + wx_seq_body(probe, sig, call) +
                                "        });\n";
                    }
                    continue;
                }
                bool ok = (f.ret.kind == "void" ||
                           (wx_marshalable(f.ret, c) &&
                            (f.ret.kind != "object" || f.ret.copy_constructible)));
                bool raw_ptr = wx_type_has_raw_ptr(f.ret);
                for (const auto &p : f.params) {
                    ok = ok && wx_marshalable(p.type, c) &&
                         (p.type.kind != "object" || p.is_ref || p.type.copy_constructible) &&
                         (p.type.kind == "object" || !p.is_mutable_ref);
                    raw_ptr = raw_ptr || wx_type_has_raw_ptr(p.type);
                }
                if (ok) {
                    const std::string policy =
                        raw_ptr ? ", emscripten::allow_raw_pointers()" : "";
                    body += "    emscripten::function(\"" + f.name + "\", " + fn_addr(f) +
                            policy + ");\n";
                }
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += "#include <emscripten/bind.h>\n";
            out += "#include <algorithm>\n";
            out += "#include <array>\n";
            out += "#include <filesystem>\n";
            out += "#include <functional>\n";
            out += "#include <memory>\n";
            out += "#include <stdexcept>\n";
            out += "#include <string>\n";
            out += "#include <type_traits>\n";
            out += "#include <vector>\n";
            // pybind-free: just the user's (stock) headers below.
            auto add = [&](const std::string &h) { append_include(out, h); };
            out += init_includes(c);
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += WASMX_CALLBACK_HELPER;  // rosetta_wx::make_fn / to_val / from_val
            out += "\nEMSCRIPTEN_BINDINGS(" + c.lib + ") {\n";
            out += init_block(c);
            out += body;
            out += "}\n";
            return out;
        }

        inline std::string WasmExpandedBackend::render(const GenContext &c) const {
            return wasm_expanded_source(c);
        }

        inline void WasmExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "wasm-expanded";
            write_file(dir / "auto_emscripten.cpp", wasm_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(WASMX_CMAKE, c));
            write_file(dir / "README.md",
                       readme("wasm-expanded", c,
                              subst(WASMX_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
