// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// WebAssembly (emscripten/embind) generation backend — registered under the
// "wasm" target. Included by inline/generate.hxx, which provides the shared
// render helpers this file relies on.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view WASM_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/wasm_visitor.h>

EMSCRIPTEN_BINDINGS({{LIB}}) {
{{BINDINGS}}}
)CPP";

        constexpr std::string_view WASM_CMAKE =
            R"CMK(# Generated by rosetta::generate — do not edit by hand.
cmake_minimum_required(VERSION 3.28)
project({{LIB}}_binding CXX)

if(NOT EMSCRIPTEN)
    message(FATAL_ERROR "Configure via `emcmake cmake ...` (emsdk required).")
endif()

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

{{USER_ENABLE_C}}add_executable({{LIB}} auto_emscripten.cpp{{USER_SOURCES}})

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}}){{USER_LIB_WASM_BLOCK}}

target_compile_options({{LIB}} PRIVATE
    {{REFLECTION_FLAGS}})

target_link_options({{LIB}} PRIVATE
    --bind -sMODULARIZE=1 -sEXPORT_NAME=createModule
    -sENVIRONMENT=node,web -sALLOW_MEMORY_GROWTH=1 -sDISABLE_EXCEPTION_CATCHING=0){{USER_DEFS_BLOCK}}

set_target_properties({{LIB}} PROPERTIES SUFFIX ".js")
{{OUT_DIR_BLOCK_WASM}}
)CMK";

        // Build section appended to the generated README. WASM_CMAKE hard-fails
        // outside emcmake AND injects {{REFLECTION_FLAGS}} — the source runs
        // reflection at compile time, so the emsdk's clang must be the p2996
        // fork (a stock emsdk rejects -freflection). There is no
        // CLANG_P2996_ROOT cache var here: emcmake pins the compiler itself.
        constexpr std::string_view WASM_README_BUILD = R"MD(## Build

Needs an activated emsdk whose clang understands the P2996 reflection flags
(`-freflection` etc., i.e. an emscripten built on the clang-p2996 fork) — the
emitted source runs reflection at compile time, so a stock emsdk will not do.
The CMakeLists refuses to configure without `emcmake`.

```sh
emcmake cmake -S . -B build
cmake --build build
```

Produces `build/{{LIB}}.js` + `build/{{LIB}}.wasm`: a MODULARIZE'd factory
named `createModule`, for both node and the web.

## Use

```sh
node -e "require('./build/{{LIB}}.js')().then(M => console.log(Object.keys(M)))"
```
)MD";

        inline void WasmBackend::emit(const GenContext &c) const {
            std::string binds = init_block(c);
            // Enums first so class fields/methods can resolve them.
            for (const auto &e : c.enums) {
                binds += "    rosetta::bind_wasm_enum<" + qualified_of(e) + ">(\"" + exposed_of(e) +
                         "\");\n";
            }
            for (const auto &k : c.classes) {
                binds += "    rosetta::bind_wasm<" + qualified_of(k) + ">(\"" + exposed_of(k) + "\");\n";
            }
            for (const auto &f : c.functions) {
                binds += "    emscripten::function(\"" + f.name + "\", " + fn_addr(f) +
                         ");\n";
            }
            auto dir = c.out_dir / "wasm";
            write_file(dir / "auto_emscripten.cpp", render_source(WASM_CPP, c, binds));
            write_file(dir / "CMakeLists.txt", render_meta(WASM_CMAKE, c));
            write_file(dir / "README.md",
                       readme("wasm", c, subst(WASM_README_BUILD, {{"LIB", c.lib}})));
        }

    } // namespace gen_detail
} // namespace rosetta
