// Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
#include <napi.h>
#include <rosetta/backends/node_runtime.h>
#include "shapes.h"

namespace rosetta_node {
using namespace std;
class Js_Shape : public Shape, public rosetta::NapiTrampoline {
public:
    using Shape::Shape;
    double area() const override {
        return rosetta::napi_call_override_pure<Shape, double>(*this, "area");
    }
    std::string describe() const override {
        return rosetta::napi_call_override<Shape, std::string>(*this, "describe", [&]{ return this->Shape::describe(); });
    }
};
} // namespace rosetta_node

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    {
        using This = rosetta::Wrap<Shape, rosetta_node::Js_Shape>;
        std::vector<Napi::ClassPropertyDescriptor<This>> props;
        props.push_back(This::InstanceAccessor<&This::get_field<&Shape::label>, &This::set_field<&Shape::label>>("label"));
        props.push_back(This::InstanceMethod<&This::call_method<&Shape::area>>("area"));
        props.push_back(This::InstanceMethod<&This::call_method<&Shape::describe>>("describe"));
        props.push_back(This::InstanceMethod<&This::call_method<&Shape::scaled_area>>("scaled_area"));
        Napi::Function ctor = This::DefineClass(env, "Shape", props);
        rosetta::ctor_ref<Shape>() = Napi::Persistent(ctor);
        rosetta::ctor_ref<Shape>().SuppressDestruct();
        {
            Napi::Object proto = ctor.Get("prototype").As<Napi::Object>();
            auto &guard = rosetta::napi_override_guard<Shape>();
            if (proto.Get("area").IsFunction()) {
                guard["area"] = Napi::Persistent(proto.Get("area").As<Napi::Function>());
                guard["area"].SuppressDestruct();
            }
            if (proto.Get("describe").IsFunction()) {
                guard["describe"] = Napi::Persistent(proto.Get("describe").As<Napi::Function>());
                guard["describe"].SuppressDestruct();
            }
        }
        exports.Set("Shape", ctor);
    }
    return exports;
}

NODE_API_MODULE(shapes, Init)
