// Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
#include <napi.h>
#include <rosetta/backends/node_runtime.h>
#include "../../person.h"

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    {
        using This = rosetta::Wrap<Person, Person>;
        std::vector<Napi::ClassPropertyDescriptor<This>> props;
        props.push_back(This::InstanceAccessor<&This::get_field<&Person::name>, &This::set_field<&Person::name>>("name"));
        props.push_back(This::InstanceAccessor<&This::get_field<&Person::age>, &This::set_field_ranged<&Person::age, "age", 0.0, 150.0>>("age"));
        props.push_back(This::InstanceAccessor<&This::get_field<&Person::id>, &This::set_field_readonly<&Person::id, "id">>("id"));
        props.push_back(This::InstanceAccessor<&This::get_field<&Person::color>, &This::set_field<&Person::color>>("color"));
        props.push_back(This::InstanceAccessor<&This::get_field<&Person::verified>, &This::set_field<&Person::verified>>("verified"));
        props.push_back(This::InstanceMethod<&This::call_method<&Person::greet>>("greet"));
        props.push_back(This::InstanceMethod<&This::call_method<&Person::clear>>("clear"));
        Napi::Function ctor = This::DefineClass(env, "Person", props);
        rosetta::ctor_ref<Person>() = Napi::Persistent(ctor);
        rosetta::ctor_ref<Person>().SuppressDestruct();
        rosetta::ctor_table<Person>()[3] =
            [](const Napi::CallbackInfo &info) { return Person(rosetta::from_napi<std::remove_cvref_t<std::string>>(info[0]), rosetta::from_napi<std::remove_cvref_t<int>>(info[1]), rosetta::from_napi<std::remove_cvref_t<std::string>>(info[2])); };
        exports.Set("Person", ctor);
    }
    return exports;
}

NODE_API_MODULE(reflected_person, Init)
