// Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
#include <emscripten/bind.h>
#include <algorithm>
#include <array>
#include <filesystem>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
#include "../../person.h"

namespace rosetta_wx {
    template <typename T> struct is_std_array : std::false_type {};
    template <typename U, std::size_t N> struct is_std_array<std::array<U, N>> : std::true_type {};

    template <typename T> emscripten::val to_val(const T &x) {
        if constexpr (is_std_array<std::remove_cvref_t<T>>::value) {
            emscripten::val a = emscripten::val::array();
            for (std::size_t i = 0; i < x.size(); ++i) a.set(i, to_val(x[i]));
            return a;
        } else {
            return emscripten::val(x);
        }
    }
    template <typename T> T from_val(const emscripten::val &v) {
        if constexpr (is_std_array<T>::value) {
            T out{};
            for (std::size_t i = 0; i < out.size(); ++i)
                out[i] = from_val<typename T::value_type>(v[i]);
            return out;
        } else {
            return v.template as<T>();
        }
    }
    template <typename F> struct fn_wrap;
    template <typename R, typename... A> struct fn_wrap<std::function<R(A...)>> {
        static std::function<R(A...)> make(emscripten::val f) {
            return [f](A... args) -> R {
                emscripten::val r = f(to_val<std::remove_cvref_t<A>>(args)...);
                if constexpr (std::is_void_v<R>) { (void)r; }
                else { return from_val<std::remove_cvref_t<R>>(r); }
            };
        }
    };
    template <typename F> F make_fn(emscripten::val f) { return fn_wrap<F>::make(f); }
}

EMSCRIPTEN_BINDINGS(reflected_person) {
    emscripten::class_<Person>("Person")
        .constructor<>()
        .constructor<std::string, int, std::string>()
        .property("name", &Person::name)
        .property("age",
            +[](const Person &s) { return s.age; },
            +[](Person &s, int v) {
                if (v < 0 || v > 150)
                    throw std::runtime_error("age out of range [0, 150]");
                s.age = v;
            })
        .property("id",
            +[](const Person &s) { return s.id; },
            +[](Person &, std::string) { throw std::runtime_error("id is read-only"); })
        .property("color", &Person::color)
        .property("verified", &Person::verified)
        .function("greet", static_cast<std::string (Person::*)(const std::string &) const>(&Person::greet))
        .function("clear", static_cast<void (Person::*)()>(&Person::clear));
}
