// Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl/filesystem.h>
#include <pybind11/functional.h>
#include <algorithm>
#include <filesystem>
#include <memory>
#include <type_traits>
#include <vector>
#include "../../person.h"

namespace py = pybind11;

PYBIND11_MODULE(reflected_person, m) {
    m.doc() = "Auto-generated (expanded) bindings for reflected_person.";
    {
        py::class_<Person> c(m, "Person");
        c.def(py::init<>());
        c.def(py::init<std::string, int, std::string>());
        c.def_readwrite("name", &Person::name, "the person's display name");
        c.def_property("age",
            [](const Person &s) { return s.age; },
            [](Person &s, int v) {
                if (v < 0 || v > 150)
                    throw py::value_error("age out of range [0, 150]");
                s.age = v;
            }, "age in whole years");
        c.def_readonly("id", &Person::id, "server-assigned identifier");
        c.def_readwrite("color", &Person::color, "favourite colour");
        c.def_readwrite("verified", &Person::verified, "account verified flag (0/1)");
        c.def("greet", &Person::greet, "Returns a greeting prefixed by the given salutation.");
        c.def("clear", &Person::clear);
    }
}
