// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// ---------------------------------------------------------------------------
// --clean: remove everything the pipeline generated for a manifest — the
// generator project dir, the generator binary beside it, and the manifest's
// backend folders under the bindings dir. Never the manifest itself, and
// never a folder that lacks the "Generated by rosetta" stamp the emitters
// write into their CMakeLists (so a hand-made folder sharing the name
// survives).
// ---------------------------------------------------------------------------

#include "clean.h"
#include "manifest.h"
#include "util.h"

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

static bool has_generated_marker(const fs::path &cmakelists) {
    std::ifstream in(cmakelists);
    std::string   line;
    for (int i = 0; i < 3 && std::getline(in, line); ++i) {
        if (line.find("Generated by rosetta") != std::string::npos) {
            return true;
        }
    }
    return false;
}

static bool remove_reported(const fs::path &p) {
    std::error_code ec;
    const auto      n = fs::remove_all(p, ec);
    if (ec || n == 0) {
        return false;
    }
    std::fprintf(stderr, "removed %s\n", p.string().c_str());
    return true;
}

static int run_clean(const fs::path &manifest, fs::path gen_dir, fs::path bindings_dir) {
    const Manifest m            = load(manifest);
    const fs::path manifest_dir = fs::absolute(manifest).parent_path();
    if (bindings_dir.empty()) {
        bindings_dir = manifest_dir / "bindings";
    }

    // The generator project: the explicit --gen-dir, or both defaults (`gen`
    // from --build, `generated` from the plain mode). Marker-guarded.
    std::vector<fs::path> gen_candidates;
    if (!gen_dir.empty()) {
        gen_candidates.push_back(gen_dir);
    } else {
        gen_candidates.push_back(manifest_dir / "gen");
        gen_candidates.push_back(manifest_dir / "generated");
    }
    std::vector<fs::path> gen_parents; // where a generator binary may sit
    for (const auto &g : gen_candidates) {
        if (!fs::exists(g)) {
            continue;
        }
        if (!has_generated_marker(g / "CMakeLists.txt")) {
            std::fprintf(stderr, "not removing %s (no rosetta_gen marker in its CMakeLists)\n",
                         g.string().c_str());
            continue;
        }
        if (remove_reported(g)) {
            gen_parents.push_back(fs::absolute(g).parent_path());
        }
    }

    // The generator binary dropped next to a removed project dir (incl. the
    // per-config subdirs a multi-config generator uses).
    for (const auto &parent : gen_parents) {
        for (fs::path bin = find_generator(parent); !bin.empty(); bin = find_generator(parent)) {
            if (!remove_reported(bin)) {
                break;
            }
        }
    }

    // The per-backend folders the manifest declares — and only those, so
    // anything else a user parked under the bindings dir survives.
    for (const auto &t : m.targets) {
        remove_reported(bindings_dir / t.lang);
    }
    std::error_code ec;
    if (fs::exists(bindings_dir, ec) && fs::is_empty(bindings_dir, ec)) {
        remove_reported(bindings_dir);
    } else if (fs::exists(bindings_dir, ec)) {
        std::fprintf(stderr, "kept %s (holds files not generated from this manifest)\n",
                     bindings_dir.string().c_str());
    }
    return 0;
}

static const char *kCleanUsage =
    "usage: rosetta_gen --clean <manifest.json> [options]\n"
    "  --gen-dir DIR            generator project dir   (default: <manifest dir>/gen\n"
    "                           and <manifest dir>/generated)\n"
    "  --bindings-dir DIR       generated bindings dir  (default: <manifest dir>/bindings)\n";

int clean_main(int argc, char **argv) {
    fs::path manifest, gen_dir, bindings_dir;
    for (int i = 2; i < argc; ++i) {
        const std::string a    = argv[i];
        auto              next = [&]() -> std::string {
            if (i + 1 >= argc) {
                std::fprintf(stderr, "rosetta_gen: %s needs a value\n%s", a.c_str(),
                             kCleanUsage);
                std::exit(1);
            }
            return argv[++i];
        };
        if (a == "--gen-dir") {
            gen_dir = next();
        } else if (a == "--bindings-dir") {
            bindings_dir = next();
        } else if (a == "-h" || a == "--help") {
            std::fprintf(stdout, "%s", kCleanUsage);
            return 0;
        } else if (a[0] == '-') {
            std::fprintf(stderr, "rosetta_gen: unknown --clean option %s\n%s", a.c_str(),
                         kCleanUsage);
            return 1;
        } else if (manifest.empty()) {
            manifest = a;
        } else {
            std::fprintf(stderr, "rosetta_gen: unexpected argument %s\n%s", a.c_str(),
                         kCleanUsage);
            return 1;
        }
    }
    if (manifest.empty()) {
        std::fprintf(stderr, "%s", kCleanUsage);
        return 1;
    }
    if (!fs::exists(manifest)) {
        std::fprintf(stderr, "rosetta_gen: manifest not found: %s\n", manifest.string().c_str());
        return 1;
    }
    try {
        return run_clean(manifest, gen_dir, bindings_dir);
    } catch (const std::exception &e) {
        std::fprintf(stderr, "rosetta_gen: %s\n", e.what());
        return 1;
    }
}
