// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// --clean: remove everything the pipeline generated for a manifest — never
// the manifest itself, and never a folder lacking the "Generated by rosetta"
// stamp.

#pragma once

// Parse `rosetta_gen --clean ...` arguments and run the cleanup.
int clean_main(int argc, char **argv);
