// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Framework-level rosetta_gen tool. Reads manifest.json and emits a
// per-project tool source tree:
//
//   <out_dir>/bindings.h               rosetta::binding_info<T> specializations
//   <out_dir>/<generator_name>.cpp     main() with one generate<T> per class
//   <out_dir>/CMakeLists.txt           builds <generator_name>
//
// `<generator_name>` is the manifest-level `generator_name` field — the
// driver tool's name. The user compiles `<generator_name>` and runs it
// to emit the per-backend bindings.
//
// Usage:
//   rosetta_gen <manifest.json> [out_dir]    emit the tool source tree
//   rosetta_gen --build <manifest.json> [..] the whole pipeline in one command:
//                                            emit + build + run the generator,
//                                            then compile every backend
//                                            (--build --help lists the options)
//   rosetta_gen --clean <manifest.json> [..] remove everything generated for
//                                            the manifest (gen/, bindings/,
//                                            the generator binary) — never the
//                                            manifest itself
//   rosetta_gen --init [manifest.json] [src_dir]
//                                            write a starter manifest (default
//                                            ./manifest.json; refuses to overwrite
//                                            an existing file). Without src_dir: a
//                                            commented example. With src_dir: scan
//                                            its headers/sources and pre-fill the
//                                            "classes" / "functions" /
//                                            "user_sources" arrays
//
// The implementation lives in one file per concern:
//   manifest.h/.cpp   the Manifest structs + load() (manifest field docs there)
//   emit.h/.cpp       generator-project emission (bindings.h / driver / CMake)
//   init.h/.cpp       --init (example manifest + heuristic source scan)
//   build.h/.cpp      --build (the whole pipeline in one command)
//   clean.h/.cpp      --clean
//   util.h/.cpp       file I/O + portable command running
// This file holds only main() and the help text.

#include "build.h"
#include "clean.h"
#include "emit.h"
#include "init.h"
#include "manifest.h"

#include <cstdio>
#include <string>

static const char *kUsage =
    "usage: rosetta_gen <manifest.json> [out_dir]\n"
    "       rosetta_gen --build <manifest.json> [options]\n"
    "       rosetta_gen --clean <manifest.json> [options]\n"
    "       rosetta_gen --init [manifest.json] [src_dir]\n"
    "try `rosetta_gen --help` for details and examples\n";

// Full -h / --help: the three modes, the --build options, and worked examples.
static void print_help() {
    std::fprintf(
        stdout,
        "rosetta_gen — turn a manifest.json into language bindings for a C++ library.\n"
        "\n"
        "Modes:\n"
        "  rosetta_gen <manifest.json> [out_dir]\n"
        "      Emit the generator project (bindings.h + <generator_name>.cpp +\n"
        "      CMakeLists.txt) into out_dir (default: <manifest dir>/generated).\n"
        "      Build it with CMake (needs the clang-p2996 toolchain), then run the\n"
        "      `generator` binary it drops next to out_dir to write one\n"
        "      self-contained project per backend.\n"
        "\n"
        "  rosetta_gen --build <manifest.json> [options]\n"
        "      The whole pipeline in one command: emit the generator project,\n"
        "      build and run it, then compile every backend the manifest declares\n"
        "      — plain CMake for most, npm for node, emcmake for wasm, and the\n"
        "      dotnet / mvn second stages for csharp / java. A backend whose\n"
        "      toolchain is missing (no emsdk, no julia, …) is skipped with a\n"
        "      note; the run ends with a per-backend summary and exits non-zero\n"
        "      if any attempted build failed.\n"
        "\n"
        "  rosetta_gen --clean <manifest.json> [--gen-dir DIR] [--bindings-dir DIR]\n"
        "      Remove everything generated for this manifest: the generator\n"
        "      project dir (gen/ or generated/), the generator binary, and the\n"
        "      manifest's backend folders under bindings/. Never the manifest\n"
        "      itself — and never a folder missing the \"Generated by rosetta\"\n"
        "      stamp, so hand-written folders sharing a name survive.\n"
        "\n"
        "  rosetta_gen --init [manifest.json] [src_dir]\n"
        "      Write a starter manifest (default ./manifest.json; never\n"
        "      overwrites an existing file). Without src_dir: a commented\n"
        "      example to fill in. With src_dir: the directory is scanned\n"
        "      (.h/.hh/.hpp/.hxx headers, .cpp/.cxx/.cc sources) and the\n"
        "      manifest is pre-filled with the classes and free functions\n"
        "      found, plus the sources as user_sources. The scan is heuristic\n"
        "      — template classes, overload sets and anonymous namespaces are\n"
        "      skipped — so review the result before building.\n"
        "\n"
        "--build options:\n"
        "%s"
        "\n"
        "Examples:\n"
        "  rosetta_gen --init\n"
        "      Start here — writes a commented manifest.json to fill in.\n"
        "\n"
        "  rosetta_gen --init manifest.json ./src\n"
        "      Scan ./src and pre-fill the manifest with the classes and free\n"
        "      functions it declares.\n"
        "\n"
        "  rosetta_gen --build manifest.json\n"
        "      Everything: bindings generated into ./bindings and compiled.\n"
        "\n"
        "  rosetta_gen --build manifest.json --only python,node --jobs 8\n"
        "      Only the python and node backends, 8-way parallel builds.\n"
        "\n"
        "  rosetta_gen --build manifest.json \\\n"
        "      --clang-p2996-root ~/devs/clang-p2996/build --fresh\n"
        "      Point the thin (reflection) backends at your toolchain and start\n"
        "      from a clean gen/ + bindings/.\n"
        "\n"
        "  rosetta_gen --clean manifest.json\n"
        "      Back to sources: delete gen/, bindings/ and the generator binary.\n"
        "\n"
        "  rosetta_gen manifest.json gen\n"
        "      Generate only, then run the steps by hand:\n"
        "        cmake -S gen -B gen/build && cmake --build gen/build\n"
        "        ./generator bindings\n"
        "        cmake -S bindings/python -B bindings/python/build\n"
        "        cmake --build bindings/python/build\n"
        "\n"
        "Every manifest field is documented in docs/MANIFEST.md; the full\n"
        "walkthrough is docs/QUICKSTART.md. Each generated backend folder also\n"
        "carries a README.md with its own build/use instructions.\n",
        kBuildOptions);
}

int main(int argc, char **argv) {
    // `-h` / `--help` prints the full help: modes, options, examples.
    if (argc >= 2 &&
        (std::string(argv[1]) == "-h" || std::string(argv[1]) == "--help")) {
        print_help();
        return 0;
    }

    // `--init [manifest.json] [src_dir]` writes a starter manifest (default
    // ./manifest.json) and exits, without clobbering an existing one. An
    // argument naming an existing DIRECTORY is the source tree to scan; the
    // other (if any) is the manifest path.
    if (argc >= 2 && std::string(argv[1]) == "--init") {
        fs::path manifest, scan_dir;
        bool     bad = false;
        for (int i = 2; i < argc; ++i) {
            const fs::path a = argv[i];
            if (fs::is_directory(a)) {
                bad      = bad || !scan_dir.empty();
                scan_dir = a;
            } else if (manifest.empty()) {
                manifest = a;
            } else {
                bad = true;
            }
        }
        if (bad) {
            std::fprintf(stderr, "usage: rosetta_gen --init [manifest.json] [src_dir]\n");
            return 1;
        }
        if (manifest.empty()) {
            manifest = "manifest.json";
        }
        try {
            return init_manifest(manifest, scan_dir, argv[0]);
        } catch (const std::exception &e) {
            std::fprintf(stderr, "rosetta_gen: %s\n", e.what());
            return 1;
        }
    }

    // `--build manifest.json [...]` runs the whole pipeline (generate + build
    // the generator + generate the bindings + compile every backend).
    if (argc >= 2 && std::string(argv[1]) == "--build") {
        return build_main(argc, argv);
    }

    // `--clean manifest.json [...]` removes everything the pipeline generated
    // for that manifest (never the manifest itself).
    if (argc >= 2 && std::string(argv[1]) == "--clean") {
        return clean_main(argc, argv);
    }

    // Any other leading option is a mistake — don't treat it as a manifest path.
    if (argc >= 2 && argv[1][0] == '-') {
        std::fprintf(stderr, "rosetta_gen: unknown option %s\n%s", argv[1], kUsage);
        return 1;
    }

    if (argc < 2 || argc > 3) {
        std::fprintf(stderr, "%s", kUsage);
        return 1;
    }
    const fs::path manifest_path = argv[1];
    const fs::path out_dir =
        (argc == 3) ? fs::path(argv[2]) : fs::absolute(manifest_path).parent_path() / "generated";

    try {
        const bool changed = emit_generator_project(load(manifest_path), out_dir);

        // Plain mode ends here — the user configures / builds the emitted
        // project themselves. Two footguns worth a printed note:
        // - out_dir/build not configured yet (fresh checkout, or a --clean
        //   removed it): `cmake --build` alone fails, so spell out the
        //   configure step;
        // - a generator binary from a previous emit still sits next to
        //   out_dir: run without rebuilding, it would silently re-emit the
        //   OLD bindings.
        const fs::path build_dir = out_dir / "build";
        if (!fs::exists(build_dir / "CMakeCache.txt")) {
            std::fprintf(stderr,
                         "next: cmake -S %s -B %s && cmake --build %s\n",
                         out_dir.string().c_str(), build_dir.string().c_str(),
                         build_dir.string().c_str());
        } else if (changed) {
            std::fprintf(stderr,
                         "note: sources changed — rebuild the generator "
                         "(cmake --build %s) before running it, or a stale "
                         "binary will re-emit the previous bindings\n",
                         build_dir.string().c_str());
        }
    } catch (const std::exception &e) {
        std::fprintf(stderr, "rosetta_gen: %s\n", e.what());
        return 1;
    }

    return 0;
}
