#!/usr/bin/env python3
"""
Generate a blank rosetta binding project (CMakeLists.txt, .gitignore,
manifest.json, README.md), following the layout of stressinv/rosetta/.

Usage:
    python3 rosetta_init.py --dir ../mylib/rosetta --name mylib
    python3 rosetta_init.py --dir ./out --name MyLib --module mylib \
        --targets nanobind-expanded node-expanded wasm-expanded typescript
"""

import argparse
import json
import sys
from pathlib import Path

ALL_TARGETS = [
    "nanobind-expanded",
    "node-expanded",
    "wasm-expanded",
    "typescript",
]

CMAKELISTS = """\
# -------------------------------------------------------------------
# Bootstrap only: fetches rosetta into extern/ and builds the
# rosetta_gen tool (-> extern/rosetta/bin/rosetta_gen). The bindings
# themselves are NOT built here — see README.md
# (rosetta_gen -> generator -> per-language projects under bindings/).
#
#   cmake -B build && cmake --build build
# -------------------------------------------------------------------
cmake_minimum_required(VERSION 3.28)
project({name}-rosetta VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS on)

include(FetchContent)

# ----------------------------------------------------------------------------
# ROSETTA library — fetched into extern/ (sources only; the manifest's
# "rosetta_include" points to extern/rosetta/include). An existing
# checkout (or a symlink to a local working copy) is left untouched.
# ----------------------------------------------------------------------------
if(NOT EXISTS ${{CMAKE_SOURCE_DIR}}/extern/rosetta/include/rosetta/generate.h)
    message(STATUS "Fetching Rosetta library...")
    FetchContent_Declare(
        rosetta
        GIT_REPOSITORY https://github.com/xaliphostes/rosetta.git
        GIT_TAG        main
        GIT_SHALLOW    TRUE
        SOURCE_DIR ${{CMAKE_SOURCE_DIR}}/extern/rosetta
        BINARY_DIR ${{CMAKE_BINARY_DIR}}/extern/rosetta-build
    )
    FetchContent_Populate(rosetta)
endif()

# The rosetta_gen code generator lives in tools/ and has its own standalone
# CMakeLists.txt — build it as a subdirectory. Its binary always lands in
# <rosetta>/bin, i.e. extern/rosetta/bin/rosetta_gen.
# NOTE: rosetta_gen requires CMake >= 3.28.
message(STATUS "Building rosetta_gen tool...")
add_subdirectory(
    ${{CMAKE_SOURCE_DIR}}/extern/rosetta/tools/rosetta_gen
    ${{CMAKE_BINARY_DIR}}/extern/rosetta_gen-build
)
"""

GITIGNORE = """\
build/
bin/
dist/
extern/
output/
.DS_Store
generator
bindings
gen
generated
*.png
*.html
"""

README = """\
# {title} binding

Language bindings for **{title}** generated by
[rosetta](https://github.com/xaliphostes/rosetta) — **Python**, **Node.js**
and **WebAssembly**, from one `manifest.json`, without touching a line of
{name}'s source.

## Build

One-time bootstrap: fetch `rosetta` into `extern/` and build `rosetta_gen`:

```bash
cmake -B build && cmake --build build
```

Then, generate the `generator` + all the bindings and compile all of them:

```bash
./extern/rosetta/bin/rosetta_gen --build manifest.json    # → bindings/, compiled; --help lists the options
```
"""


def make_manifest(name: str, module: str, targets: list[str]) -> dict:
    target_entries = []
    for t in targets:
        if t == "typescript":
            target_entries.append({"lang": t})
        else:
            target_entries.append({"lang": t, "name": module})
    return {
        "sequences": [],
        "compile_definitions": [],
        "cpp26_root": "$ENV{HOME}/devs/c++/clang-p2996/build",
        "cpp26_cxx": "$ENV{HOME}/devs/c++/clang-p2996/build/bin/clang++",
        "cpp26_cc": "$ENV{HOME}/devs/c++/clang-p2996/build/bin/clang",
        "cpp26_lib": "$ENV{HOME}/devs/c++/clang-p2996/build/lib",
        "build_type": "release",
        "optimization": "O2",
        "user_include": ["../include"],
        "rosetta_include": "./extern/rosetta/include",
        "generator_name": f"{name}_gen",
        "module_name": module,
        "targets": target_entries,
        "user_sources": ["../src/*.cxx"],
        "classes": [],
        "functions": [],
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a blank rosetta binding project."
    )
    parser.add_argument(
        "--dir",
        required=True,
        help="Folder where the project is generated (created if missing), "
        "e.g. ../mylib/rosetta",
    )
    parser.add_argument(
        "--name",
        required=True,
        help="Project name, e.g. mylib (used for CMake project, "
        "generator_name and README title)",
    )
    parser.add_argument(
        "--module",
        default=None,
        help="Binding module name (default: --name lowercased)",
    )
    parser.add_argument(
        "--targets",
        nargs="+",
        default=ALL_TARGETS,
        choices=ALL_TARGETS,
        metavar="TARGET",
        help=f"Binding targets (default: all). Choices: {', '.join(ALL_TARGETS)}",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files in the target folder",
    )
    args = parser.parse_args()

    name = args.name
    module = args.module or name.lower()
    out = Path(args.dir).expanduser()

    files = {
        "CMakeLists.txt": CMAKELISTS.format(name=name),
        ".gitignore": GITIGNORE,
        "manifest.json": json.dumps(make_manifest(name, module, args.targets), indent=4)
        + "\n",
        "README.md": README.format(title=name, name=name),
    }

    existing = [f for f in files if (out / f).exists()]
    if existing and not args.force:
        sys.exit(
            f"error: {', '.join(existing)} already exist(s) in {out} "
            "(use --force to overwrite)"
        )

    out.mkdir(parents=True, exist_ok=True)
    (out / "examples").mkdir(exist_ok=True)
    for fname, content in files.items():
        (out / fname).write_text(content)
        print(f"  created {out / fname}")

    print(
        f"\nBlank rosetta project '{name}' generated in {out}.\n"
        "Next steps:\n"
        f"  1. Edit {out / 'manifest.json'}: add your classes/functions and "
        "adjust user_include/user_sources\n"
        f"  2. cd {out} && cmake -B build && cmake --build build\n"
        "  3. ./extern/rosetta/bin/rosetta_gen --build manifest.json"
    )


if __name__ == "__main__":
    main()
