// Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl/filesystem.h>
#include <pybind11/functional.h>
#include <algorithm>
#include <filesystem>
#include <memory>
#include <type_traits>
#include <vector>
#include "shapes.h"

namespace py = pybind11;

namespace rosetta_py {
using namespace std;
class Py_Shape : public Shape {
public:
    using Shape::Shape;
    double area() const override {
        PYBIND11_OVERRIDE_PURE(double, Shape, area, );
    }
    std::string describe() const override {
        PYBIND11_OVERRIDE(std::string, Shape, describe, );
    }
};
} // namespace rosetta_py

PYBIND11_MODULE(shapes, m) {
    m.doc() = "Auto-generated (expanded) bindings for shapes.";
    {
        py::class_<Shape, rosetta_py::Py_Shape> c(m, "Shape");
        [](auto &c) {
            if constexpr (!std::is_abstract_v<rosetta_py::Py_Shape>) {
                c.def(py::init<>());
            }
        }(c);
        c.def_readwrite("label", &Shape::label);
        c.def("area", &Shape::area);
        c.def("describe", &Shape::describe);
    }
}
